### ISSUE TITLE
Option to use space-drag instead of space-mousemove to pan

### ISSUE THREAD

**Issue by MKRhere** [penpot/penpot#1007]
**Is your feature request related to a problem? Please describe.**

Coming from other software, I'm used to space (or alt) + click-drag to pan. But penpot seems to have space + mouse move. I thought I'd try and get used to it, but it's frustrating because I can't get left-right hand coordination (instead of releasing LMB and dragging again, you have to release space with left hand and move mouse to another spot with right, then space again with left). It works, but I'm nowhere nearly as efficient.

**Describe the solution you'd like**

If it's too much to change the default behaviour, perhaps an option to switch behaviour would be appreciated.

**Describe alternatives you've considered**

Down the road, perhaps fully customisable keybindings, or expose the functionality through plugins.

**Comment by myfunnyandy** [comment]
We've been evaluanting internally your proposal and we decided that is a change that's worth making. You can follow the progress at Taiga: https://tree.taiga.io/project/penpot/us/1800?no-milestone=1

Thanks for such well argued proposal.

**Comment by MKRhere** [comment]
That's excellent news! Thanks for taking it up.

**Comment by hirunatan** [comment]
This is solved now! You'll see it in the next release.

**Comment by MKRhere** [comment]
Thanks a lot :) I look forward to it
