### ISSUE TITLE
Lock axis while dragging by using shift

### ISSUE THREAD

**Issue by Manueljlin** [penpot/penpot#1015]
**Is your feature request related to a problem? Please describe.**
Not a bug, but an UX issue (imo). A way to easily make small position adjustments without having to type it on the coordinates input box like on other design applications.

**Describe the solution you'd like**
Personally I'd like to see the tried and tested approach of locking movement in one axis while holding the shift key.

The behavior would be the following:

- Hold Shift and drag horizontally: Y axis stays the same, X axis is free on both directions 
- Hold Shift and drag vertically: X axis stays the same, Y axis is free on both directions 

https://youtu.be/9mUL-O4Q68c

**Comment by claragvinola** [comment]
Hi Manueljlin! thank you so much for your feedback! 

We've already have an enhacement to make this! https://tree.taiga.io/project/penpot/us/1384?no-milestone=1 (you can follow the progress in this link)

**Comment by myfunnyandy** [comment]
This is done.
