### ISSUE TITLE
Multiple errors in text tool

### ISSUE THREAD

**Issue by soultipsy** [penpot/penpot#1025]
Hi, I found multiple errors while using the text tool, and since they are similar issues, I decided to report them in the same bug report, each one will be denoted by a capital letter (A,B,C ......) Thanks!

***[A]***
**Describe the bug**
 In text editing mode, if you delete all the content, when you type again, the fill color will be lost and go back to the default text style.

**To Reproduce**
Steps to reproduce the behavior
1.  Double click the text to enter edit mode
2.  Delete all the text
3.  Re-type the text
4.  The text fill becomes default

**Expected behavior**
When you delete all the text and retype, the new text color should be the same as the last deleted text color.

**Screenshots**

https://user-images.githubusercontent.com/40300919/121455505-2c1a3a00-c9d7-11eb-83cf-1c67a7288e4d.mp4

------------------------------------------------------------

***[B]***
**Describe the bug**
After inserting an empty text with the text tool, or deleting all the content, when the text editor loses focus, the page crashes with an error.

**To Reproduce**
1.  inserting a text box without typing anything, or deleting all the contents of a text box
2. Click on the blank area or press esc to make the text box lose focus
3. The page crashes to report an error

**Expected behavior**
When the content of a text box is empty, the text box should be automatically deleted after it loses focus, and the page will not report an error.

**Screenshots**

https://user-images.githubusercontent.com/40300919/121455697-7f8c8800-c9d7-11eb-8d52-4c798cfa2bc7.mp4

https://user-images.githubusercontent.com/40300919/121455711-874c2c80-c9d7-11eb-8b0e-f76ccb091c07.mp4

-----------------------------------------------------------

***[C]***
**Describe the bug**
When typing Chinese, if the Chinese preselected items are not selected, the page will probably crash and report an error (the input method is Microsoft's own Chinese input method).

**To Reproduce**
1.  Type Chinese in the text box
2. Do not select any Chinese preselected items
3.  Click on the blank area to make the text box lose focus
4. The page crashes and reports an error

**Expected behavior**
If the focus is lost when no Chinese preselected item is selected, the English letters should be retained directly and the page will not report an error.

**Screenshots**

https://user-images.githubusercontent.com/40300919/121456100-15281780-c9d8-11eb-8559-b71f26b996eb.mp4

--------------------------------------------------------

***[D]This is an enhancement suggestion***
in text editing mode, it should provide undo option for each step of adding or deleting, otherwise when editing a large text, it is impossible to undo single step operation, only all of them can be undone.

https://user-images.githubusercontent.com/40300919/121456359-87006100-c9d8-11eb-9510-46f5be6f76fd.mp4

--------------------------------------------------------

**Desktop :**

-   OS: Windows
-   Browser : Microsoft Edge & Firefox
-   Version : 92.0.902.9 beta & 89.0 

**Environment :**
 SAAS (https://design.penpot.app)

**Comment by niwinz** [comment]
Thanks so much @soultipsy for this detailed report.

We already aware of the crash with chinese input method. We use the facebook draft-js editor and it has a bug that causes that, we  reported it here: https://github.com/facebook/draft-js/issues/2961, this is just FYI. We will conttinue to look into the rest of reports.

**Comment by myfunnyandy** [comment]
Also added to our Taiga issues the [A]: https://tree.taiga.io/project/penpot/issue/1829

And we found [D] to be a very reasonable suggestion, so we added to our backlog as an enhancement: https://tree.taiga.io/project/penpot/us/1830?no-milestone=1

Still could not reproduce [B], it could be related to the browser/OS.

Thanks for the report @soultipsy !

**Comment by soultipsy** [comment]
Yes, error [B] is not reproducible now, it is functioning perfectly fine.

**Comment by myfunnyandy** [comment]
Except point [D], which we are managing in a different User Story, everything sould be solved. Thanks.
