### ISSUE TITLE
Resize from center

### ISSUE THREAD

**Issue by ghost** [penpot/penpot#1029]
**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
Resize from center

**Comment by myfunnyandy** [comment]
Hi, this is already on our backlog: https://tree.taiga.io/project/penpot/us/1537?no-milestone=1 
I will add your request to the user story to better track the interest.

**Comment by hirunatan** [comment]
This is done now. You will see it in the next release.

**Comment by ghost** [comment]
@hirunatan Thank you
