### ISSUE TITLE
Issues when Flip horizontal/Flip vertical  and Transformation

### ISSUE THREAD

**Issue by soultipsy** [penpot/penpot#1040]
**Describe the bug**
When a horizontally/vertically flipped shape is edited, there is a problem with the scaling of the shape, the borders are misaligned and the scaling is shifted, the more times you adjust the scaling, the more obvious the shift is.

**To Reproduce**
1.  Create a new arbitrary shape/path
2.  Perform horizontal/vertical flip operation on it
3.  Edit its path
4.  Resize it
5. The border misalignment issues appears
6. Resize it again
7. Issues with uncontrolled shift in scaling

**Expected behavior**

Scaling and resizing should be as normal.

**Screenshots**

https://user-images.githubusercontent.com/40300919/122172027-f1227580-ceb2-11eb-96e0-514ec8b5219f.mp4

**Desktop (please complete the following information):**

-   OS: Windows
-   Browser : Firefox
-   Version :89.0

**Environment (please complete the following information):**
SAAS (https://design.penpot.app)

**Comment by Alotor** [comment]
Thanks for the report. I'll address the issue soon.

**Comment by niwinz** [comment]
Should be fixed.
