### ISSUE TITLE
Export shape suddenly doesn't work (for text elements)

### ISSUE THREAD

**Issue by Quin452** [penpot/penpot#1042]
Earlier today, I was able to export two shapes from penpot as PNG.

These worked fine, and there was no issue.

However now, I suddenly cannot export anything which includes text (tried PNG, tried SVG).  I originally tried to export a colour-variation of a shape/group that was previously exported, and it came back with "An unexpected error occurred", after about 30 seconds.
I tried with one that did work, and it resulted the same.

After some testing, it seems that Text elements cannot be exported.  I've tried images that were imported, and SVGs too, and they work just fine.
Originally, I created a logo with FontAwesome SVGs and some text.  The SVGs export fine, the text do not, and when I try and export the logo group, it fails (assuming it's because the text is included).

**Comment by niwinz** [comment]
Hi @Quin452,

Are you using selfhosted or SAAS? On our saas we have detected some issues but they are now should be solved.
