### ISSUE TITLE
Adapt scaling of text boxes

### ISSUE THREAD

**Issue by burnoutberni** [penpot/penpot#1045]
**Is your feature request related to a problem? Please describe.**
When scaling a text box, the behavior is a bit counter-intuitive. I figured out that you can scale the text with the shortcut "K" and then dragging, but there's no indication whether or not you're in scaling or text box resizing mode. Proportional text box resizing doesn't seem like something I ever need to do without scaling. Even if, I can achieve that by other means (e.g. entering the calculated dimensions myself).

**Describe the solution you'd like**
I think this could be simplified: There's already the locking symbol, which locks the dimensions of the text box. I propose that when you lock it, you enter scaling mode. In my opinion, this is also much more intuitive.

**Describe alternatives you've considered**
Adding another indicator somewhere in this area.

**Comment by elhombretecla** [comment]
Hi @burnoutberni thank you so much for your feedback!

We will review and approach this as soon as we can. 

Track the enhancement here [https://tree.taiga.io/project/penpot/issue/1852](https://tree.taiga.io/project/penpot/issue/1852)
