### ISSUE TITLE
Font size selector improvements

### ISSUE THREAD

**Issue by burnoutberni** [penpot/penpot#1047]
**Is your feature request related to a problem? Please describe.**
When changing the font size of some text, I found two issues: First, I cannot enter floating numbers, only integers. Second, when using the arrow buttons to change the values up/down, sometimes I cannot go up, only down (I can open two separate issues as bugs, if you want to, but I feel this needs improvement anyways).

**Describe the solution you'd like**
Both issues should be fixed. Additionally, it would be really nice if the font size selector could be improved. The Firefox Web Inspector (Chromium too!) has a feature where you can use shortcuts to tweak values like this.

`Ctrl` + `Up/Down` = +/- 100
`Shift` + `Up/Down` = +/- 10
`Up/Down` = +/- 1
`Alt` + `Up/Down` = +/- 0.1

**Additional context**
This probably applies to other dropdown number selectors too.

**Comment by myfunnyandy** [comment]
This request matches with a user story that we already have at our backlog (https://tree.taiga.io/project/penpot/us/1382), although it has a bit more detail. We've attached this issue to the story and will consider your suggestions at the moment we start its development.

Thanks!

**Comment by hirunatan** [comment]
Done. Now you can increment or decrement by 1 and by 10, with arrows and shift, and enter decimal values. This occurs too in other dropdown numeric fields, like artboard grid size.

You will see it in the next release.

**Comment by burnoutberni** [comment]
@hirunatan thank you, this is great. One thing though: I think it would be great to also implement the `Ctrl` and `Alt` key combos – I use especially the `Alt` one for +/- .1 a lot. This is somewhat connected to another problem though, that you currently can't enter floating numbers in this field.

**Comment by hirunatan** [comment]
Ok. We open a new US for the Alt+arrows shortcut: https://tree.taiga.io/project/penpot/us/1945

For font sizes, we see not much utility of incrementing by 100 with Ctrl.

**Comment by timfx94** [comment]
related, happy to create a new issue though, when typing in a font size, i'm unable to backspace to get an empty field to type a number into. The work around i have been using is to backspace to 1 then use arrow keys to set the value to 0 then I can enter my value. i've attached an example 

https://user-images.githubusercontent.com/88827699/132681497-79944b00-c513-4af9-bd79-f6246b3b387d.mov

**Comment by ck1ldn** [comment]
Place your cursor where the arrow is. Then, shift + arrow keys to increase or decrease font size
![image](https://user-images.githubusercontent.com/13010623/193318984-4061d2e1-c057-4262-8bc8-aae62cc5d3e1.png)

**Comment by myfunnyandy** [comment]
Last release we've implemented a lot of [text formatting shortcuts](https://tree.taiga.io/project/penpot/us/2052?milestone=333185) and the issue with the backspace is fixed too, so I'm closing the issue. 

Thanks to all.
