### ISSUE TITLE
The pick color position of some fonts is offset

### ISSUE THREAD

**Issue by soultipsy** [penpot/penpot#1049]
**Describe the bug**
When taking a color for some fonts, such as Noto Sans SC or Source Sans Pro, the color picker does not pick up the actual position of the color, resulting in an inaccurate pick up color. This may be related to the font baseline position and height.(Noto Sans and Source Sans belong to the same family, I guess all fonts in this family have this problem).

**To Reproduce**
1.  Turn on the color picker
2.  Pick color for Source Sans font family 
3.  The position and color of the color picker preview window are not consistent with the position and color pointed by the actual cursor

**Expected behavior**
The position of the color in the preview window should be the same as that of the cursor

**Screenshots**
Screenshots show that the first two fonts do not deviate like the Sources Sans family of fonts.

https://user-images.githubusercontent.com/40300919/122513828-881b3900-d03d-11eb-9b70-050fa6842533.mp4

**Desktop (please complete the following information):**

-   OS: Windows
-   Browser : Firefox&Microsoft Edge
-   Version :89.0&92.0.902.15 Beta

**Environment (please complete the following information):**
SAAS (https://design.penpot.app)

**Comment by myfunnyandy** [comment]
We've opened an issue at Taiga, thanks for the report: https://github.com/penpot/penpot/issues/1049
