### ISSUE TITLE
German translation on weblate

### ISSUE THREAD

**Issue by nautilusx** [penpot/penpot#1051]
Thanks for your great work.

I want to improve the german translation on weblate.

https://hosted.weblate.org/user/nautilusx/

**Comment by myfunnyandy** [comment]
Hi @nautilusx, we've just granted you permissions to allow you to contribute with german tranlslations. You also might want to take a look at https://help.penpot.app/contributing-guide/translations/

Thanks!

**Comment by winie** [comment]
Hello,
I'd also like to help improve the German translation, but I can't submit any suggestions in Weblate. Can you please also give me access to the Weblate.

**Comment by Alotor** [comment]
@winie can you share your weblate user? thanks.

**Comment by winie** [comment]
> @winie can you share your weblate user? thanks.

It's also winie because I log into Weblate via github.

**Comment by myfunnyandy** [comment]
Hi @winie, sorry for the late response. You have been already added to the weblate project. Thansk!
