### ISSUE TITLE
Mouse middle and right buttons trigger selected object resizing

### ISSUE THREAD

**Issue by Calcimicium** [penpot/penpot#1060]
**Describe the bug**
I mainly use the mouse middle button to navigate inside the viewport. The problem is when an object is selected in the viewport and I accidentally middle click a border or a corner of the selection box (it happens often...), it triggers a resizing until I left click somewhere else.

**To Reproduce**
1.  Create a new object (by inserting a resource or drawing a simple shape)
2.  Middle click (or right click) a border (or corner) of the selected object
3.  If you right click the border, press *Escape* to close the contextual menu
4.  Move the mouse and see the object beeing resized until you left click

**Expected behavior**
Middle and right clicks should not trigger the resizing of the selected object.

**Screenshots**
Middle click:
![middle-click](https://user-images.githubusercontent.com/2129545/123403223-d8981680-d5a8-11eb-94eb-33fe410f5dfe.gif)

Right click:
![right-click](https://user-images.githubusercontent.com/2129545/123403239-dd5cca80-d5a8-11eb-82c1-1bb30b69e0e0.gif)

**Desktop**
-   OS: Debian 11 (bullseye)
-   Browser: Chrome
-   Version: 91.0.4472.114

**Environment:**
SAAS (https://design.penpot.app)

**Comment by elhombretecla** [comment]
Hi @Calcimicium 

Thank you for your feedback :)

We will manage this issue from Taiga [https://tree.taiga.io/project/penpot/issue/1866](https://tree.taiga.io/project/penpot/issue/1866)
