### ISSUE TITLE
Unfocus property field by pressing Escape and Enter

### ISSUE THREAD

**Issue by Calcimicium** [penpot/penpot#1061]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I validate a property entry by pressing *Enter* and the field keeps the focus. It is the same when I want to cancel an entry by pressing *Escape*.

**Describe the solution you'd like**
I'd like that:
- pressing *Enter* in a property field validates the entry and transfers the focus on the selected object.
- pressing *Escape* in a property field cancels the entry and transfers the focus on the selected object.

**Describe alternatives you've considered**
I don't think about an alternative.

**Comment by elhombretecla** [comment]
We will do some research about this! You can track the enhancement here [https://tree.taiga.io/project/penpot/issue/1867](https://tree.taiga.io/project/penpot/issue/1867)

**Comment by myfunnyandy** [comment]
Already solved, thanks for reporting it.
