### ISSUE TITLE
Disable dynamic alignment with hidden objects

### ISSUE THREAD

**Issue by Calcimicium** [penpot/penpot#1063]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I hide objects but alignment guides with those objects are still shown and snaped.

**Describe the solution you'd like**
When some objects are hidden, I'd like the one I'm moving does not display nor snap to them.

**Additional context**
A moving rectangle snaping to hidden objects
![image](https://user-images.githubusercontent.com/2129545/123421532-3fbfc600-d5bd-11eb-9f83-7a466659cd8e.png)

**Comment by elhombretecla** [comment]
Hi again @Calcimicium :)

Something is wrong with hidden objects and dynamic alignment.
You can track this issue here [https://tree.taiga.io/project/penpot/issue/1868](https://tree.taiga.io/project/penpot/issue/1868)

**Comment by Calcimicium** [comment]
Ok! Sorry I didn't find any ticket on GitHub about this.

Thanks for reply!
