### ISSUE TITLE
Shared project link doesn't stick after login, works if already logged in

### ISSUE THREAD

**Issue by diacritica** [penpot/penpot#1071]
**Describe the bug**
If you need to log in prior to continue to a shared project link, then the link is lost and you end up on your dashboard, as a regular login.

**To Reproduce**
I received a shared project link created by another Penpot user (project and team are accessible to me). I clicked on it and it asked me to log in first, I did so and went directly to my default Penpot screen, not to the shared link.

**Expected behavior**
Shared project link should be propagated after login and not require an active session.

**Screenshots**
N/A

**Desktop (please complete the following information):**

-   OS: Linux 64bit
-   Browser (e.g. chrome, safari): Firefox 
-   Version (e.g. 22): 89.0.2

**Smartphone (please complete the following information):**

N/A

**Environment (please complete the following information):**

SaaS

**Additional context**

N/A

**Comment by myfunnyandy** [comment]
Managed on Taiga: https://github.com/penpot/penpot/issues/1071
