### ISSUE TITLE
Stroke is cropped when exporting cut images

### ISSUE THREAD

**Issue by soultipsy** [penpot/penpot#1092]
**Describe the bug**
When the stroke type is centered or external, the stroke in the exported image (JPG, PNG, SVG, PDF) will be cropped (the size of the exported image will only be cropped according to the size of the fill, and the size of the stroke is ignored), in addition, when the stroke is changed from centered to external, the part of the stroke will also be cropped in the penpot.

**To Reproduce**
1.  Drawing shapes
2.  Add a stroke to it, (to make it more visible, add a large value to the stroke)
3.  Export (JPG, PNG, SVG, PDF)
4.  View export results

**Expected behavior**
Stroke should occupy the actual space and should not be cropped.
**Screenshots**

https://user-images.githubusercontent.com/40300919/125758442-7e589862-4a3b-41d0-803e-327cf1d0eb2b.mp4

https://user-images.githubusercontent.com/40300919/125758465-3dabd4a3-4c20-4581-b977-f9ffaaf3f107.mp4

**Desktop (please complete the following information):**

-   OS: Windows
-   Browser : Firefox&Microsoft Edge
-   Version :89.02& 92.0.902.45 Beta

**Environment (please complete the following information):**
SAAS (https://design.penpot.app) version 1.7.0-alpha-5594-ga6d156438

**Comment by myfunnyandy** [comment]
Thanks for such detailed report. We've added this to Taiga and will try to fix it soon: https://tree.taiga.io/project/penpot/issue/1897
