### ISSUE TITLE
Need a union or substract option for objects to create icons

### ISSUE THREAD

**Issue by APattjoshi** [penpot/penpot#1097]
**Is your feature request related to a problem? Please describe.**
I want to create an Icon where two objects come together to create a shape

**Describe the solution you'd like**
I want to subtract one shape with another

**Describe alternatives you've considered**
I have put a colour patch to fake it

**Additional context**
No other context

**Comment by jdittrich** [comment]
I also looked for this yesterday. 
Sometimes it is also useful to create irregular shapes, like an popover element as outlined rectangle with a little pointer triangle. However, it is not essential to me at the moment.

**Comment by elhombretecla** [comment]
Hi everyone!

Shape booleans operations are high prioritized in the project roadmap. We are closing some SVG task related and then we will start developing this user story.

You can track the progress here [https://tree.taiga.io/project/penpot/us/748](https://tree.taiga.io/project/penpot/us/748)

**Comment by niwinz** [comment]
Booleans already implemented.
