### ISSUE TITLE
Component options menu is partially hidden by main viewport

### ISSUE THREAD

**Issue by mlgarchery** [penpot/penpot#1101]
**Describe the bug**
The component options menu is partially hidden by the  viewport.

**To Reproduce**
1.  Create a component
2.  Click on the component 3-dots options on the right menu (see the image below)
3.  The menu is partially visible

**Expected behavior**
The menu should be on top of the main viewport and so fully visible.

**Screenshots**
![Screenshot from 2021-07-22 00-38-14](https://user-images.githubusercontent.com/16239564/126569084-2b86f0d6-2849-4cce-a18f-66bf5283da88.png)

**Desktop (please complete the following information):**

-   OS: Ubuntu
-   Browser: Brave
-   Version 1.7

**Environment (please complete the following information):**
SAAS

**Additional context**
My selected language is French.

**Comment by elhombretecla** [comment]
Hi @mlgarchery thank you for your feedback!

We will fix this bug as soon as we can. You can track this issue here [https://tree.taiga.io/project/penpot/issue/1900](https://tree.taiga.io/project/penpot/issue/1900)

**Comment by hirunatan** [comment]
This already closed in https://github.com/penpot/penpot/issues/1223
