### ISSUE TITLE
Animations/transitions between artworks

### ISSUE THREAD

**Issue by Enrico204** [penpot/penpot#1102]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when (...)
During the prototyping of mobile apps, transitions are very important in UI/UX design. Modal views should appear with a transition from bottom to top (and dismissal should be the reverse, top to bottom). Inner views navigation is a left-right transition instead.

**Describe the solution you'd like**
In the "prototype" tab (in workspace) there should be a way to set an optional transition for that action. In the prototype "view mode" the transition should be played accordingly.

**Describe alternatives you've considered**
I'm not aware of any alternative at the moment.

**Additional context**
See Google web fundamentals for examples: https://developers.google.com/web/fundamentals/design-and-ux/animations/animating-between-views

**Comment by elhombretecla** [comment]
Hi @Enrico204 and thanks for your comments :)

We are currently working on advanced prototyping capabilities which include animations, new triggers, etc...
It will be ready as soon as possible. You can follow this US status here [https://tree.taiga.io/project/penpot/us/244](https://tree.taiga.io/project/penpot/us/244)

**Comment by Enrico204** [comment]
Good! Also I found that this issue is a duplicated of #724 , so I'm closing this issue and I'll follow that one :-)
Thanks :-)
