### ISSUE TITLE
Use both "_" and "-" as Zoom Out shortcut; and both "+" and "=" as Zoom in shortcut

### ISSUE THREAD

**Issue by vladstudio** [penpot/penpot#1104]
**Problem**
Current shortcuts to zoom in/out are "-" and "+". This sounds logical, but I have to hold Shift to zoom in, and not hold it to zoom out. Inconvenient!

**Solution**
Use both "_" (with Shift) and "-" (without Shift) as Zoom Out shortcut; and both "+" (with Shift) and "=" (without Shift) as Zoom in shortcut. Try it in Figma as an example.

**Comment by elhombretecla** [comment]
Hi @vladstudio thanks for your input. You're right. We need to review and enhance this zoom shortcuts behaviour.
We already add this enhancement to our work queue.

[https://tree.taiga.io/project/penpot/issue/1901](https://tree.taiga.io/project/penpot/issue/1901)
