### ISSUE TITLE
When an input is focused, let "Esc" return focus to the viewport

### ISSUE THREAD

**Issue by vladstudio** [penpot/penpot#1105]
**Problem**
To be more productive, I want to be able to switch between inputs and viewport without leaving the keyboard. Right now, once I make an input in focus, I cannot unfocus it and return to viewport by keyboard. E.g. in Figma I can hit Esc to unfocus. Example:

https://cdn.vlad.studio/831cde4cd104769a02332ef8f1416d57.mp4

**Solution**
When an input is focused, let "Esc" return focus to the viewport.

**Comment by elhombretecla** [comment]
Yeah! Good one :)

Adding this input behaviour will improve the experience definitely. Thank you! Track the enhancement here
[https://tree.taiga.io/project/penpot/issue/1902](https://tree.taiga.io/project/penpot/issue/1902)
