### ISSUE TITLE
In "Constraints" panel, the colors of enabled/disabled constraints are too similar

### ISSUE THREAD

**Issue by vladstudio** [penpot/penpot#1106]
My suggestion:

![image](https://user-images.githubusercontent.com/914320/126646254-a1115b3a-7210-41f3-93dd-ace7de3e1522.png)

**Comment by elhombretecla** [comment]
Hi again @vladstudio :)

This bug will be reviewed by the design team in order to fix the usability.
[https://tree.taiga.io/project/penpot/issue/1903](https://tree.taiga.io/project/penpot/issue/1903)

**Comment by myfunnyandy** [comment]
Closing the issue as the UI change has already been done.
