### ISSUE TITLE
Custom Fonts change and don't show on export

### ISSUE THREAD

**Issue by Kernin** [penpot/penpot#1108]
**Describe the bug**

when i load my cutom fonts, its all normal, they show up correctly (in chrome) but when i want to export my board the image either jpeg or png does not show the custom font, it shows another  font

**To Reproduce**
1.  load custom font
2. open proyect 
3. change text to custom font ( in my case a single block of text has 2 different custom font)
4. export board to jpeg or png
5. view image and notice wrong font

**Expected behavior**

when exporting a board with text in custom fonts i would expecto to see the text in the custom font i chose

**Screenshots**
screenshot: 
![screenwhot-penpot-evidence-01](https://user-images.githubusercontent.com/5806416/126661044-cc2c9a40-8110-4629-92e5-49d87fcb79da.jpg)
Exports:
![img-portada-n321-nombre-reg](https://user-images.githubusercontent.com/5806416/126660900-ce051578-d40d-4876-9098-ea4633450af7.jpeg)
![img-portada-n321-nombre-reg](https://user-images.githubusercontent.com/5806416/126660907-377c835e-f8d4-4550-9f76-6b1e700fcfeb.png)

**Desktop (please complete the following information):**

-   OS: macOS Hight Sierra
-   Browser Chrome
-   Version 91.0.4472.114 (Build oficial) (x86_64)

**Smartphone (please complete the following information):**

N/A

**Environment (please complete the following information):**
website https://design.penpot.app

If self-hosted instance, add OS and runtime information to help explain your problem.

-   OS Version: (e.g. Ubuntu 16.04)

Also provide Docker commands or docker-compose file if possible and if proceed.x

N/A

**Frontend Stack Trace (if self-hosted)**

N/A

**Backend Stack Trace (if self-hosted)**

N/A

**Additional context**

custom fonts also change when using firefox in windows, but i guess that would be another bug report

**Comment by niwinz** [comment]
Hello @Kernin

Thank for reporting this issue. I have checked it right now and looks like it works as expected. Can you try again?, if the problem persists, can you send us the font you have used or share with us (privately on info@penpot.app) the link of the file where the problem appears?
