### ISSUE TITLE
When the "alt" key is pressed the shape should change symmetrical from the center

### ISSUE THREAD

**Issue by hedgehoglover2** [penpot/penpot#1111]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to change the size of a circle but I don't have the option to make it bigger from the center / symmetrical on the x or y axis.

**Describe the solution you'd like**
When I change the size of a shape I want the growth to come from the center when I press my "alt" key. When I change the size of a shape in one direction (for example increasing a button's width) I also want it to expand to both left and right when I press my "alt" key while dragging.

**Describe alternatives you've considered**
none

**Additional context**
This is the same shortcut that is used in other layout programs like Adobe InDesign or Figma. I would love to have this feature as it speeds up my workflow a lot :)

**Comment by elhombretecla** [comment]
Thanks for your ideas @abbynorway 

You're right. This is an usual and expected behavior in order to transform elements. We will review it and develop as soon as we can.

Thank you!

[https://tree.taiga.io/project/penpot/issue/1904](https://tree.taiga.io/project/penpot/issue/1904)
