### ISSUE TITLE
Settings top right button not working

### ISSUE THREAD

**Issue by eduayme** [penpot/penpot#1123]
**Describe the bug**
Exit button in top right of the feedback page not working.

**To Reproduce**
1.  Go to any '/settings/X', for example '/settings/feedback'
2.  Click on the top right button 'Exit' or in Spanish 'Salir'
3.  See button is doing nothing

**Expected behavior**
Not sure if the button should logout, go back to the dashboard or directly not displayed.

**Screenshots**
<img width="1440" alt="Screenshot 2021-07-30 at 23 45 15" src="https://user-images.githubusercontent.com/26260104/127714652-65bd5260-0fc7-4376-a383-352033b92dab.png">

**Desktop:**
-   OS: (MacOS Beta 12.0)
-   Browser (Brave)
-   Version (1.27.109 Chromium: 92.0.4515.115)

**Environment:**
SAAS (https://design.penpot.app).

**Comment by claragvinola** [comment]
Hi Eduard! you're right! the button should directly not be displayed! We've created the issue (https://tree.taiga.io/project/penpot/issue/1922)

Thanks for your feedback!

**Comment by eduayme** [comment]
@claragvinola I have open a new PR to solve the bug #1129

**Comment by claragvinola** [comment]
Thank you! we've merge your PR :) You will see the changes in the next release ;)
