### ISSUE TITLE
Custom Fonts Not Showing Up in Editor or View Mode

### ISSUE THREAD

**Issue by nickian** [penpot/penpot#1124]
I'm using:

- Pentpot version 1.8.0-alpha
- Running with Docker Compose on Ubuntu 20
- Doesn't matter which browser, it's happening on all of them that I try.

Custom fonts that I upload are not working. I've tried uploading multiple ones (both TTF and OTF). Here's an example. I pulled this font from Google and tried uploading: https://fonts.google.com/specimen/WindSong

![image](https://user-images.githubusercontent.com/590678/127723353-ed8974c0-e2fe-4198-b75a-c4b4f1fe5ac4.png)

![image](https://user-images.githubusercontent.com/590678/127723373-e1bc911a-0e21-425b-94b9-e4d0eac71ece.png)

I see this error in the developer console:

![image](https://user-images.githubusercontent.com/590678/127729261-cc808b0f-86b5-4fee-a031-d25c46469bcf.png)

Are there any other log files that would be helpful in debugging this?

**Comment by claragvinola** [comment]
Hello Nickian! we're currently working on fixing this problem. we will keep you updated!

**Comment by claragvinola** [comment]
Hello Nickian! we've fix the problem yesterday. Please try to re-load the font and see if it's working.

**Comment by nickian** [comment]
@claragvinola Can you confirm that I am doing this correctly to test? It's not working, but I just did this to stop my docker containers:

`docker-compose -p penpot down`

Then did:

`docker system prune -a`

Then did a `git pull` in the repository.

Then `git checkout 1.7.2-alpha`

Then `docker-compose -p penpot -f docker-compose.yaml up -d`

But I'm still having the font issue after that.

**Comment by nickian** [comment]
I did also delete the font and re-import it.

**Comment by niwinz** [comment]
We have had some issues on windows, for some reason window browser did not reported correctly the mimetype and the fonts from windows are imported incorrectly. This is fixed on the 1.7.3, I will upload the docker image today (probably directly the 1.7.4 that will include other fixes.
