### ISSUE TITLE
Arabic Translate 

### ISSUE THREAD

**Issue by MidooDj** [penpot/penpot#1126]
Hello, 
I want to help with the **Arabic** translation. 
I would be happy if you could permit me to make translations on Weblate.

My Weblate profile link is: [](https://hosted.weblate.org/user/MidooDj/)

Thanks 🙏

**Comment by claragvinola** [comment]
Hi MidooDj! can you send us your profile link please? 

Thank you!!!!

**Comment by MidooDj** [comment]
> Hi MidooDj! can you send us your profile link please?
> 
> Thank you!!!!

Hello @claragvinola 
sorry I forget it 
here is my profile URL https://hosted.weblate.org/user/MidooDj/

**Comment by hirunatan** [comment]
Hi! I have added you to the project. Now you should see it in your projects
list, and be able to send translations of the language you want.

Thanks very much for your help!
