### ISSUE TITLE
Want to change the height to .5 or .25 from 1, currently can't do it

### ISSUE THREAD

**Issue by APattjoshi** [penpot/penpot#1127]
**Is your feature request related to a problem? Please describe.**
I want to change the height of a Rectangle to .25px from 1px. Ex. I'm currently unable to reduce it to .25 , I don't want to take line because I want the line to transform into a box.

**Describe the solution you'd like**
If I am able to reduce the size to .25px then it will help me keep the object the same.

**Describe alternatives you've considered**
A line can be added but not the solution I want

**Additional context**
![image](https://user-images.githubusercontent.com/47391164/127860842-29f6f17e-97e7-4838-8a58-9947be99f8bb.png)

**Comment by claragvinola** [comment]
Hi! Penpot does not currently allow setting sizes less than 1 px. We add your suggestion to our roadmap!
Thank you!

**Comment by myfunnyandy** [comment]
Closing the issue as subpixel units are already available.
