### ISSUE TITLE
Can't access drafts page and also can't create new projects after deleting the stuff in projects page

### ISSUE THREAD

**Issue by zhaolinlau** [penpot/penpot#1130]
Can't access drafts page and also can't create new projects after deleting the stuff in projects page.
Browser I use: Firefox
OS: Windows 10

Details please refer to the video:
https://youtu.be/GCLPbhWENno

**Comment by niwinz** [comment]
Nice catch, thanks this will be fixed on the next release (the fixes on the backend side are already landed on `main` branch)

**Comment by hirunatan** [comment]
@zhaolinlau we have just released a new version that fixes this. If you delete your drafts project, the deletion has no effect.

In the next release we'll ship a more polished front behavior, but for now it's enough to avoid failures.

**Comment by zhaolinlau** [comment]
> 
> 
> @zhaolinlau we have just released a new version that fixes this. If you delete your drafts project, the deletion has no effect.
> 
> In the next release we'll ship a more polished front behavior, but for now it's enough to avoid failures.

problem still there

**Comment by hirunatan** [comment]
Hum... does this occur in an account where you deleted drafts project before the release? or is in a new account?

In the second case, the problem persists when you reload the page? If it solves, it's an expected behavior. For now, the backend simply ignores the delete request, so if you reload front, everything is restored.

In the next release we will enhance this to completely avoid deleting drafts.

**Comment by zhaolinlau** [comment]
> 
> 
> Hum... does this occur in an account where you deleted drafts project before the release? or is in a new account?
> 
> In the second case, the problem persists when you reload the page? If it solves, it's an expected behavior. For now, the backend simply ignores the delete request, so if you reload front, everything is restored.
> 
> In the next release we will enhance this to completely avoid deleting drafts.

yaya better than before already, just need to relogin to refresh.
