### ISSUE TITLE
Interaction Animation of Prototype

### ISSUE THREAD

**Issue by zhaolinlau** [penpot/penpot#1131]
As we know, Penpot's prototype is monotonous because it doesn't have any animation. What I expect is adding some interaction animations of prototype, and the interaction in Figma is the example. It's like when I click the button of next page or back to previous page, it will show the animation of swiping left/right before reaching the page I want to reach.

**Comment by claragvinola** [comment]
Hello! we're currently working con Advanced interactions for prototypes. You can see the progress in here: https://tree.taiga.io/project/penpot/us/244?milestone=262806

Thank you so mucho for your feedback

**Comment by niwinz** [comment]
The referenced issue is already done.
Thanks for reporting.
