### ISSUE TITLE
Can't login after recreating an old account

### ISSUE THREAD

**Issue by zhaolinlau** [penpot/penpot#1132]
I have deleted my account to recreate new
account due to the issue I already submitted to github which is here
https://github.com/penpot/penpot/issues/1130 . After that, I suddenly
cannot login to Penpot and I'm pretty sure that my
username(email) and password are all correct but the
Penpot still keep saying that my username or password is incorrect and
of course I did try to reset password but Penpot didn't send anything
for me to reset my password.

**Comment by niwinz** [comment]
@zhaolinlau thanks for repoting it, this will be fixed in the next release, the fix is already on `main` branch

**Comment by hirunatan** [comment]
@zhaolinlau please try again, you should now be able to log in with your account.

**Comment by zhaolinlau** [comment]
> 
> 
> @zhaolinlau please try again, you should now be able to log in with your account.

Yep, i can login as usual. thx
