### ISSUE TITLE
Preview not corresponding to the SVG

### ISSUE THREAD

**Issue by Aviortheking** [penpot/penpot#1134]
**Describe the bug**

**To Reproduce**
1.  get an SVG from lucides icons ex: https://lucide.dev/?search=layers
2.  import it in penpot
3.  create a component
4.  preview won't correspond to the SVG

**Expected behavior**

the preview should be the same from the SVG

**Screenshots**
![Capture](https://user-images.githubusercontent.com/15822031/128411971-caf3d270-fced-4134-adf9-9782e6d1f90c.PNG)

**Desktop (please complete the following information):**

-   OS: (e.g. iOS) Windows
-   Browser (e.g. chrome, safari) Firefox
-   Version (e.g. 22) 90.0.1

**Smartphone (please complete the following information):**

-   Device: (e.g. iPhone6)
-   OS: (e.g. iOS8.1)
-   Browser (e.g. stock browser, safari)
-   Version (e.g. 22)

**Environment (please complete the following information):**
Specify if using SAAS (https://design.penpot.app) or self-hosted instance.

If self-hosted instance, add OS and runtime information to help explain your problem.

-   OS Version: (e.g. Ubuntu 16.04) Debian 4.19.194-2

Also provide Docker commands or docker-compose file if possible and if proceed.x

-   Docker / Docker-compose Version: (e.g. Docker version 18.03.0-ce, build 0520e24) Docker version 20.10.7, build f0df350
-   Image (e.g. alpine) 1.7.2-alpha I suppose

**Frontend Stack Trace (if self-hosted)**

<details>

```
no stack trace
```

</details>

**Backend Stack Trace (if self-hosted)**

<details>

```
no stacktrace
```

</details>

**Additional context**
It may be because I have imported around 400 of theses icons in this.

**Comment by myfunnyandy** [comment]
Thanks for the report. We've opened an issue that you can track here: https://tree.taiga.io/project/penpot/issue/1940
