### ISSUE TITLE
Double clicking the design assets make the program crash

### ISSUE THREAD

**Issue by APattjoshi** [penpot/penpot#1135]
**Describe the bug**
I copied an element from the design system of penpot and pasted it in the file I am working on then I double-click in the element to edit the SVG but the program crashes, I can't change the color to it.

**To Reproduce**
1.  Open the design system file of penpot
2.  Copied an element
3.  Pasted in another document of mine
4.  Double click to edit it
5. The penpot crashing
6. pressing the retry button coming back to file

**Expected behavior**
I want to double click and change the shape of element and add a line to it as well as want to change colour of it

**Screenshots**
![arrow](https://user-images.githubusercontent.com/47391164/128460977-241e3022-550a-4b3c-a76c-1d2f96868775.PNG)
![arrowselected](https://user-images.githubusercontent.com/47391164/128460996-855e182f-bd0d-4770-bfd6-1ee5900a891c.PNG)
![error](https://user-images.githubusercontent.com/47391164/128461022-75084492-9b0d-45f3-8982-73e8f376dbca.PNG)

Desktop (please complete the following information):

OS: (Windows 10)
Browser (chrome)
Version (88.0.4324.182 (Official Build) (64-bit)
Environment (please complete the following information):
Specify if using SAAS (https://design.penpot.app).

**Comment by myfunnyandy** [comment]
We are aware of this problem and we are working on a solution to prevent this type of error. It is happening with old svgs like some of the ones of the DS (Design System). You can recognice them by their icon:
![svgs](https://user-images.githubusercontent.com/708713/128717831-f9ce0690-a5a2-4ec0-8aad-ad8d3d6a2dd1.png)

We will also release soon a new DS version with general improvements and proper, new svgs that you will be able to import to your projects.

**Comment by mlgarchery** [comment]
In Spectating Mode then Code Mode, double clicking on any element in the navigation pane on the left results in an internal error like above. I think this is linked.

**Comment by vintprox** [comment]
It may be related to dragging issue, when you suddenly drag&drop random thing in the UI and it gives redirection to "Internal Error".
