### ISSUE TITLE
Line to be round

### ISSUE THREAD

**Issue by APattjoshi** [penpot/penpot#1136]
**Is your feature request related to a problem? Please describe.**
I want the line to be round

**Describe the solution you'd like**
I want to control the edge of the line to make it round or square or add an arrow

**Describe alternatives you've considered**
There is no alternative except take a square and make the corners round but its time taking

**Additional context**

![line](https://user-images.githubusercontent.com/47391164/128461638-2c1536fe-44d4-4381-8a60-b8e90af236ad.PNG)

**Comment by myfunnyandy** [comment]
We have an user story that will enable to change the paths end points: https://tree.taiga.io/project/penpot/us/1107?backlog-q=round&no-milestone=1

However, it is yet not prioritized so can't give estimations. I will add your request to the issue, thanks!

**Comment by nikolahoff** [comment]
Do you know when this feature will be implemented?

**Comment by hirunatan** [comment]
This is already done! https://help.penpot.app/user-guide/styling/#stroke-caps

**Comment by hirunatan** [comment]
Sorry, it seems that we forgot to close this issue when we implemented this.

**Comment by nikolahoff** [comment]
> This is already done! https://help.penpot.app/user-guide/styling/#stroke-caps

Oh cool, thanks:)
