### ISSUE TITLE
Text doesn't scale with group

### ISSUE THREAD

**Issue by burnoutberni** [penpot/penpot#1142]
**Describe the bug**
When scaling a group, all children should scale with it. This generally works with the exception of text items.

**To Reproduce**
1.  Create a group containing a text item and something else (e.g. an image)
2.  Select the group
3.  Drag group boundary to scale it
4.  See the image scaling, but the text item not

**Expected behavior**
All grouped items should scale including text items.

**Desktop (please complete the following information):**

-   OS: ArchLinux
-   Browser: Firefox
-   Version: 90

**Environment (please complete the following information):**
SAAS (https://design.penpot.app)

**Comment by soultipsy** [comment]
Good question. Although penpot can now use "K" to control the scaling of text individually, it can't be applied to groups.
In fact, when we talk about the overall scaling of groups, we have to consider extending the concept of "equal scaling" to more properties, such as the value of rounded corners and the width of paths, and we need a way to make them scale at the same time as the group to ensure the same visual effect, which is very useful when drawing icons or card elements.
So is it possible to apply the "K" function to these properties：
1. Rounded corners
2. path/stroke
3. shadow
4. blur

thanks!

**Comment by myfunnyandy** [comment]
Both are interesting suggestions aligned with our motivations with the recently added scaling text capability ("K"). I've added this proposals to taiga (https://tree.taiga.io/project/penpot/us/1951?backlog-q=scaling&no-milestone=1) so we can better consider if implement all or part of it.

**Comment by VityaSchel** [comment]
> Both are interesting suggestions aligned with our motivations with the recently added scaling text capability ("K"). I've added this proposals to taiga (https://tree.taiga.io/project/penpot/us/1951?backlog-q=scaling&no-milestone=1) so we can better consider if implement all or part of it.

It's been year, any news on this topic?

**Comment by niwinz** [comment]
Looks like the referenced US is solved.
Thanks for reporting

**Comment by burnoutberni** [comment]
@niwinz I can't see any implementation actually, I think the current state of the US is "ready to develop". Should we keep this issue open, until text scaling within groups works? Current behavior is still that non-text group elements scale together, but text does not (at least on SAAS). Or is this fix somewhere in here? https://github.com/penpot/penpot/pull/2088

**Comment by niwinz** [comment]
ups, you are right, I clearly missreaded it.

**Comment by myfunnyandy** [comment]
Hi, the issue was fixed at the last release so I'm closing it.

![k-group](https://user-images.githubusercontent.com/708713/220339780-7f003710-ddae-4dd4-bc7c-0f3a5a41c63d.gif)

However, we are currently working in scaling also more properties (strokes, radius...) that will be tracked [separatelly](https://tree.taiga.io/project/penpot/us/1951?backlog-q=scaling&no-milestone=1).
