### ISSUE TITLE
Path is cut off after adding shadow

### ISSUE THREAD

**Issue by freder** [penpot/penpot#1153]
**Describe the bug**
after adding a shadow a path displays as cut off.

**To Reproduce**
- draw a path
- give it a thick outline
- add shadow

**Expected behavior**
entire path should remain visible

**Screenshots**
![penpot](https://user-images.githubusercontent.com/724844/130225914-0ef57112-ba41-425b-85cc-35b82f6dde7b.gif)

**Desktop (please complete the following information):**
-   OS: linux
-   Browser: chromium 92
-   Version: 1.7.4-alpha-5663-g24da25f0f

**Environment (please complete the following information):**
docker / self-hosted

**Comment by elhombretecla** [comment]
Hi @freder thank you for your feedback :)

We have created an issue at Taiga to accomplish and track this bug
[https://tree.taiga.io/project/penpot/issue/1957](https://tree.taiga.io/project/penpot/issue/1957)
