### ISSUE TITLE
Importing SVG exported from RAWGraphs doesn't work

### ISSUE THREAD

**Issue by giorgiouboldi** [penpot/penpot#1155]
**Describe the bug**
I try to import an svg created with [RAWGraphs](https://rawgraphs.io/) but i get "SVG is invalid or malformed" error message. 

**To Reproduce**
1. export a visualization from RAWGraphs as svg (i attach an example)
2. I drag it to PenPot or import it as image

**Expected behavior**
I think it's just a probem of how the svg is formatted. If I open it with Inkscape and then i save it, the svg is correctly imported in PenPot. 

**Desktop (please complete the following information):**

-   macOS BigSur 11.2.2.
-   Chrome 
-   92.0.4515.159

**Environment (please complete the following information):**
https://design.penpot.app

**Additional context**
I'm part of the RAWGraphs team and we would like to suggest the use of PenPot to edit the visualisations we would like to know how we should format the svg outputs to be compatible. Thanks!

**Comment by elhombretecla** [comment]
Hi @giorgiouboldi :)

It would be great to have these examples
