### ISSUE TITLE
Make the "max-file-size" defined in media.cljc bigger and configurable. 

### ISSUE THREAD

**Issue by berggy** [penpot/penpot#1156]
The default value(5mb) is realy too small for team work, especially for PNG files.

 I've tried to change it in back_end_docker:/opt/penpot/backend/deps/app.jar\app\common\media.cljc, but it keeps refusing bigger files, even after restart the backend & frontend docker containers. 

It's better to make the default value bigger, and make it configurable. 
And don't forget the "client_max_body_size" in front-end's /etc/nginx/nginx.conf 

btw, penpot is so cute:)

**Comment by niwinz** [comment]
Looks interesting, I will do it for the next release (add the ability to customize the default upload size).

**Comment by berggy** [comment]
So, how can i change the value in my dockers? :)

**Comment by niwinz** [comment]
Right now you can't

**Comment by berggy** [comment]
Well, it seems i should load a JPG file or split the PNG file into 2 or 4 blocks:)

**Comment by niwinz** [comment]
Sorry for inconvenience

**Comment by Oskaria** [comment]
Please add this variable (max file size) to config)) This been VERY useful

**Comment by niwinz** [comment]
Implemented here https://github.com/penpot/penpot/pull/2154  and will target the 1.15 release
In any case the nginx configuration is up to yo configure it, the default one in nginx is 100MB that is pretty big.
