### ISSUE TITLE
Components not labeled in Asset panel

### ISSUE THREAD

**Issue by jsmorabito** [penpot/penpot#1157]
Not sure if this is a bug or the functionality has not yet been created, but I expect to see the name of the component in the asset window. In my case, both components are labeled Component-1. The name I've given the first is "Annotation" and the second "Traffic Lights."

**Browser:** Safari 15 Beta 4

![image](https://user-images.githubusercontent.com/46250921/130820299-40d0dd6e-3fd1-48d3-8941-34f6a9815f56.png)

![image](https://user-images.githubusercontent.com/46250921/130819820-f58d9ba1-4f07-4405-b0b0-713e863e9089.png)

![image](https://user-images.githubusercontent.com/46250921/130820382-109df409-a884-453a-ac72-81bc68e473c7.png)

**Comment by niwinz** [comment]
They are different things, on the layers is the instance name, and the asset is the main component. When you drag/insert an component into your workspace from assets you are creating a linked copy of the component, and in this case the copy can have its own name. Also, you can rename the component in the assets panel.

**Comment by jsmorabito** [comment]
> They are different things, on the layers is the instance name, and the asset is the main component. When you drag/insert an component into your workspace from assets you are creating a linked copy of the component, and in this case the copy can have its own name. Also, you can rename the component in the assets panel.

thank you so much that does make sense, and I understand better after reading the guide on the side (should have checked before asking the question haha)
