### ISSUE TITLE
Penpot crashes when eyedropper tool is used on Safari 15 beta 4

### ISSUE THREAD

**Issue by jsmorabito** [penpot/penpot#1158]
**Describe the bug**
Penpot crashes when eyedropper tool is used on Safari 15 beta 4

**To Reproduce**
1. Use hotkey `cmd-i` or choose eye dropper tool from color picker menu
2. Observe crash

**Expected behavior**
Expect eyedropper to work without crashing

**Desktop (please complete the following information):**

-   OS: macOS Big Sur
-   Browser Safari 15
-   Version Beta 4

**Environment (please complete the following information):**
SAAS

**Comment by elhombretecla** [comment]
Hi @jsmorabito thanks for your feedback :)

We will investigate this bug as soon as we can.

[https://tree.taiga.io/project/penpot/issue/1958](https://tree.taiga.io/project/penpot/issue/1958)

**Comment by Alotor** [comment]
Hi @jsmorabito I'm unable to reproduce the error using the current beta version 15.0 (16612.1.28.1, 16612) and Big Sur.

Can you let me know if the error happens on a newly created page? or is an specific page where the error is happening?

Thanks

**Comment by jsmorabito** [comment]
> Hi @jsmorabito I'm unable to reproduce the error using the current beta version 15.0 (16612.1.28.1, 16612) and Big Sur.
> 
> Can you let me know if the error happens on a newly created page? or is an specific page where the error is happening?
> 
> Thanks

just tried in a new page in a different project and the error occurred even quicker somehow haha. If there's anyway to provide more detailed information let me know

![image](https://user-images.githubusercontent.com/46250921/131531831-f0eb4a42-7ee9-4307-aa99-b4627f9b3afa.png)

**Comment by Alotor** [comment]
If you don't mind, can you repeat with the javascript console open (Cmd+Option+C) and paste here the error that should be displayed there.

Also, can you paste here the exact version you're using? (Safari > About Safari)

Thanks!

**Comment by jsmorabito** [comment]
@Alotor  I'm getting this on loading Penpot `Failed to load resource: the server responded with a status of 404 ()` and there's no error reported when I try to use the eyedropper and it crashes

Safari Version 15.0 (16612.1.28.1, 16612)

**Comment by superalex** [comment]
Hello @jsmorabito 

Finally we could reproduce this and it should be solved, thanks!
