### ISSUE TITLE
Trackpad zoom sensitivity

### ISSUE THREAD

**Issue by jsmorabito** [penpot/penpot#1161]
**Is your feature request related to a problem? Please describe.**
Zooming with the trackpad on my MacBook Pro early 2015 model is too sensitive to be useful. The two finger gesture on the trackpad zooms in and out too quickly.

**Describe the solution you'd like**
A menu setting or generally more usable sensitivity by default

**Describe alternatives you've considered**
None considered

**Comment by myfunnyandy** [comment]
Thanks for reporting this. There are a lot of corner cases for different devices and we frequently add related adjustments. We'll take this case into consideration eventually.

**Comment by EnidKapelsen** [comment]
We experienced this problem in our team as well. We use three different MacBooks (one MacBookPro from 2016 to an M1 from last Year and one M1 from this year). So it Sounds rather like a macOS issue. 

Also to add: With the Apple Mouse the problem stays. Let me know if a screencast helps. 🖖🏼

**Comment by mandymozart** [comment]
I also have this issue. it's making the use extremely difficult. if you have a work around, I would love to know. 

drives me insane . =)

**Comment by Alotor** [comment]
We hope to solve this issue for the next release. Our main problem was that we didn't have the hardware to test it. But we have arranged it already. Sorry for your inconvenience :pray:

**Comment by jsmorabito** [comment]
> We hope to solve this issue for the next release. Our main problem was that we didn't have the hardware to test it. But we have arranged it already. Sorry for your inconvenience 🙏

So excited! Now that you all have the hardware maybe you can look into https://github.com/penpot/penpot/issues/1209 as well 😁 I think copy/paste may be a safari exclusive issue. Keep up the awesome work!
