### ISSUE TITLE
Tooltips in color picker

### ISSUE THREAD

**Issue by jsmorabito** [penpot/penpot#1171]
**Is your feature request related to a problem? Please describe.**
Some colors in my design system will be very closely related and hard to distinguish just by looking at the color alone.

**Describe the solution you'd like**
On hover over the color in the recent colors section I would like to see a tooltip that says the hex code. In the file library section (of the color picker), I would like to see the hex code and the name of the color if it has been named in my file library.
![image](https://user-images.githubusercontent.com/46250921/131543199-c152b3ab-380e-483c-884a-49e5da7d796c.png)

**Describe alternatives you've considered**
I have used the colors from the file library section on the left side of the screen to change the color of components, but I do not have that window active all the time, so I will use the color picker recent colors and file library menus to pick colors for components
![image](https://user-images.githubusercontent.com/46250921/131543521-cdd71c55-1ddc-4771-a467-953018fe21fa.png)

**Comment by soultipsy** [comment]
Hi, I think they are already working on this issue, I found the relevant requirements in taiga: https://tree.taiga.io/project/penpot/issue/1966

**Comment by myfunnyandy** [comment]
Right @soultipsy, this issue should solve the problem. Anyway, thanks @jsmorabito, we will crosslink this issue with the one at taiga so we take note of the interest.

**Comment by jsmorabito** [comment]
> Right @soultipsy, this issue should solve the problem. Anyway, thanks @jsmorabito, we will crosslink this issue with the one at taiga so we take note of the interest.

Ty @soultipsy for the heads up. I will be sure to check the Taiga before submitting more bugs and requests!! Should I leave this issue open or close it?

**Comment by jsmorabito** [comment]
added! 🎊
