### ISSUE TITLE
Nesting Artboards

### ISSUE THREAD

**Issue by jsmorabito** [penpot/penpot#1173]
**Is your feature request related to a problem? Please describe.**
The problem is that I can't move artboards that are located within other artboards. It also makes the layers panel more cluttered because I can't fold the sections where I'm trying to contain multiple artboards. I'm using artboards for organizing my workspace

**Describe the solution you'd like**
Ability to nest artboards in other artboards so that moving the parent moves the child

**Additional context**
Nesting Frames in Figma
![image](https://user-images.githubusercontent.com/46250921/131707709-6be88b9b-838a-47c0-a44a-af068f20c5aa.png)

**Comment by myfunnyandy** [comment]
This is already an internal discussion at the Penpot team. There are obvious advantages but on the other hand it is somehow against the svg model behind Penpot.

In fact, if the need is to better organize (collapsing and expanding sections) there are other possible solutions than nesting artboard that we are also considering.

**Comment by jsmorabito** [comment]
> This is already an internal discussion at the Penpot team. There are obvious advantages but on the other hand it is somehow against the svg model behind Penpot.
> 
> In fact, if the need is to better organize (collapsing and expanding sections) there are other possible solutions than nesting artboard that we are also considering.

Great to hear that the problem is being discussed! Should I close this comment?

**Comment by niwinz** [comment]
This is already implemented and will target the 1.15.x release
