### ISSUE TITLE
Font seach only works with lowercase letters

### ISSUE THREAD

**Issue by Igorgro** [penpot/penpot#1180]
**Describe the bug**
When searching for fonts when editing text, it works if the query contains only lowercase letters. If there are capitals letters, no results are shown.

**To Reproduce**
1. Create project
2. Create new file
3. Open file and add new text item
4. Try to change font family and search by name which contains capital letters
5. See empty search results (

**Expected behavior**
Can search for fonts despite the form of letters

**Screenshots**
Capital letters:
<details>

![изображение](https://user-images.githubusercontent.com/22894169/132011339-d9f7693c-c808-4cb1-b5cf-cfd81e9caadd.png)
</details>

Lowercase letters:
<details>

![изображение](https://user-images.githubusercontent.com/22894169/132011427-2d6a3ae8-70cb-4d06-adcf-52aa7d68d66d.png)
</details>

**Desktop (please complete the following information):**

-   OS: Debian 11 (doesn't matter)
-   Browser: Firefox 78/Chrome 93 (doesn't matter)

**Environment (please complete the following information):**
Self-hosted

If self-hosted instance, add OS and runtime information to help explain your problem.

-   OS Version: Debian 11

Also provide Docker commands or docker-compose file if possible and if proceed.x

-   Docker / Docker-compose Version: Docker 20.10.8 / Compose 1.29.2

Used official docker-compose.yml

**Frontend Stack Trace (if self-hosted)**
Nothing significant, or specific to that bug

**Backend Stack Trace (if self-hosted)**
Nothing significant, or specific to that bug

**Comment by claragvinola** [comment]
Hi Igorgro! we've created an issue related to that. You can follow the progress in here: https://tree.taiga.io/project/penpot/issue/2021
