### ISSUE TITLE
Can't select three digit hex code in color picker

### ISSUE THREAD

**Issue by jsmorabito** [penpot/penpot#1184]
**Describe the bug**
When I type the hex code 333 the color does not appear in the color picker.

**Screenshots**
![image](https://user-images.githubusercontent.com/46250921/132366551-9b622402-7024-46e8-8ee1-716310a17b70.png)

**Desktop (please complete the following information):**

-   Big Sur 11.5.2
-   Safari Version 15.0 (16612.1.28.1, 16612)

**Comment by claragvinola** [comment]
Hi jsmprabito! thank you for the feedback! we are going to work on a solution to solve this.
https://tree.taiga.io/project/penpot/issue/2023
