### ISSUE TITLE
Create component option missing from context menu for objects nested in component

### ISSUE THREAD

**Issue by jsmorabito** [penpot/penpot#1186]
**Describe the bug**
The 'create component' option is missing from the right click contextual menu for objects nested under a component. I am able to create a component out of the object using the shortcut 'cmd-k'

**To Reproduce**
1.  Right click an object that is part of a component in the layers menu
2.  Observe 'create component' option missing

**Expected behavior**
expect to see the option available

**Screenshots**
![image](https://user-images.githubusercontent.com/46250921/132375226-6c8936ad-9864-449d-b594-f4f37806ead3.png)

**Desktop (please complete the following information):**

-   big sur 11.5.2
-   Safari Version 15.0 (16612.1.28.1, 16612)

**Comment by claragvinola** [comment]
Hi! thank you for reporting this bug! we're going to give it a high priority. 
You can follow the progress here https://tree.taiga.io/project/penpot/issue/2026
