### ISSUE TITLE
Add better signifier for closing typography sub menus in assets panel

### ISSUE THREAD

**Issue by jsmorabito** [penpot/penpot#1187]
**Is your feature request related to a problem? Please describe.**
It was not immediately obvious how to close this menu which was a point of frustration. I also tried to click 'enter' after changing the name of a typography expecting that to close the menu.

**Describe the solution you'd like**
There's probably a better solution than a check mark in the bottom right corner as I show in the screenshot below, but there should be a more clear indication of how to close the menu. The 3 dots icon is a little confusing in this situation and closing the menu is not the behavior I expected.

**Additional context**
![image](https://user-images.githubusercontent.com/46250921/132397316-c0bab143-93a1-4fa4-a77c-68dc962b742e.png)

**Comment by Igorgro** [comment]
Having related problem: it is not obvious that "+" button in the text settings creates new typography:
![изображение](https://user-images.githubusercontent.com/22894169/132401439-d6bffdc7-3adc-417d-84d8-536e0640c96a.png)

**Comment by claragvinola** [comment]
Thank you so much for your feedback and for your suggestions. We're going to evaluate a better solution.
https://tree.taiga.io/project/penpot/issue/2027
