### ISSUE TITLE
No shortcuts for tools

### ISSUE THREAD

**Issue by maelomanontroppo** [penpot/penpot#1192]
**Describe the bug**
Shorcuts won't select tool

**To Reproduce**
1.  Go to 'project'
2.  try to select any tool  with keyboard input (text is 'T', ellipse is 'E', Artboard is 'A', etc.)
3.  Nothing happen

**Expected behavior**
The selected tool should become active
**Desktop):**

-   OS: windows 10
-   Browser Chrome
-   Version 86.0.4240.198

**Environment :**
SAAS (https://design.penpot.app) 

**Additional context**
Console display: "POST https://design.penpot.app/events http.cljs:89  404"

**Comment by claragvinola** [comment]
Hi! we've just fixed a problem with shortcuts. In the next release, you must be this bug solve, if it's not, let us know!
Thank you so much for the feedback!
