### ISSUE TITLE
Copy & Paste does not work in docker image

### ISSUE THREAD

**Issue by mr-floppy** [penpot/penpot#1193]
Hi!

I am running the latest docker image 1.7.0 in a VirtualBox.
Whenever I try to copy a shape, the following error message pops up in the browsr console:

```
Clipboard blocked: TypeError: navigator.clipboard is undefined
    TJa webapi.cljs:64
    XE core.cljs:361
    RxJS 24
    hKa core.cljs:188
workspace.cljs:1373:12
    qob workspace.cljs:1373
    wK core.cljs:552
    RxJS 26
    hKa core.cljs:188
```

On the [official website](https://design.penpot.app) Copy&Pasting is working as expected. The error occurs only in my locally hosted docker image.

Is this a bug, or am I doing something wrong?

**To Reproduce**
1. Clone`config.env` and `docker-compose.yaml` as described [here](https://help.penpot.app/technical-guide/getting-started/#start-penpot)
2. Set `PENPOT_PUBLIC_URI` in `config.env` to correct hostname, but do not touch `PENPOT_PUBLIC_URI` in `docker-compose.yaml` as the comment says
3. Navigate to locally hosted website and create new draft
4. Draw shape
5. Try to copy it (ctrl+c or right click context menu) -> error `navigator.clipboard is undefined` gets thrown to console
6. Paste (ctrl+v or right click context menu)
7. Recognize, that pasting works, but the system clipboard still contains whatever was in it before copying the penpot shape   

**Expected behavior**
Copying the shape should move it to the clipboard and pasting it should draw a copy of it on the canvas. Exactly as it does on the the [official website](https://design.penpot.app). 

Kind regards,
Mr. Floppy

**Comment by niwinz** [comment]
Are you serving it under https?, copy paste api is only awailable under https.

**Comment by mr-floppy** [comment]
Thank you, @niwinz!

I now have reverse proxyfied the docker container with nginx and a self signed SSL certificate.
Now copy&paste is working as expected. :)

Maybe you should add this to your readme, because none of it is mentioning HTTPS as far as I can remember. 

Kind regards,
Mr. Floppy

**Comment by niwinz** [comment]
Thanks, we consider adding this to the documentation. This is the limitation of the browser api for clipboard. We are limited to this restriction.
