### ISSUE TITLE
Drag to move comments

### ISSUE THREAD

**Issue by jsmorabito** [penpot/penpot#1196]
**Is your feature request related to a problem? Please describe.**
When I make comments and artboards/designs are moved around, I can't move the comments to stay in the relevant area

**Describe the solution you'd like**
I would like to be able to drag comments around to move them. Additionally, comments should stay attached to objects so that when the objects are moved the comments move with them. This behavior can be seen in Figma.

**Comment by claragvinola** [comment]
Hi! I will add your request to taiga. https://tree.taiga.io/project/penpot/issue/2028
Thank you so mucho for the feedback!

**Comment by mlgarchery** [comment]
I've encountered the need for this feature multiple times already, it would definitely make the comments more maintainable.

**Comment by jsmorabito** [comment]
@claragvinola this post is missing the "managed on taiga" tag! was just checking in to see if there's been any progress towards this functionality :)

**Comment by mlgarchery** [comment]
This feature would still be greatly appreciated. Posting here so we don't forget it :)

**Comment by mlgarchery** [comment]
Whitout this, the comment feature feels incomplete. But otherwise, comments are perfectly usable.

**Comment by EvaMarco** [comment]
Hello all¡¡ 
We have complete this enhancement, https://github.com/penpot/penpot/pull/2084. 
I will close this issue if you have more enhancements let us know¡¡
