### ISSUE TITLE
Add Catalan/Valencian option

### ISSUE THREAD

**Issue by rbnval** [penpot/penpot#1198]
Please add the _Catalan/Valencian_ option to the language selector in the [Settings](https://design.penpot.app/#/settings/options). Thank you!

**Comment by claragvinola** [comment]
Hi rbndev! you can see here (https://help.penpot.app/contributing-guide/translations/) the progress to become a penpot translator. After that, we add de option to settings :)

**Comment by rbnval** [comment]
Hi @claragvinola, I am already translator and it's translated. Please, add it to settings.

**Comment by claragvinola** [comment]
Hi again! yes! I've already seen that the translation it's complete. In the next release, you will see it in Options. Thank you so much for the contribution!!!

**Comment by rbnval** [comment]
Okay, thank you!
