### ISSUE TITLE
Imported SVG don't move smoothly

### ISSUE THREAD

**Issue by maelomanontroppo** [penpot/penpot#1199]
**Describe the bug**
SVG files act differently when they are imported : when I move them, only the mouse cursor will move, then, as I release the mouse button, the new position will be settled.
I tried with a SVG exported by Penpot itself, it is the same.

**To Reproduce**
1.  Drag SVG file in artboard
2.  Click and drag to move

**Screenshots**
Here is a short screencast : 

https://user-images.githubusercontent.com/90381769/132835552-294ffd68-fbc7-45ad-ad37-f3023b6e9d89.mp4

**Expected behavior**
Should be smooth like native Penpot shape

**Desktop (please complete the following information):**

-   OS: Windows
-   Browser :  Chrome
-   Version :  93.0.4577.63

**Environment (please complete the following information):**
Penpot SAAS (https://design.penpot.app)

**Additional context**
Console log : 
![image](https://user-images.githubusercontent.com/90381769/132837726-5d1c0ee9-238a-4b6a-94ee-65ae67af20c7.png)

**Comment by elhombretecla** [comment]
Hi @maelomanontroppo thanks for your detailed feedback, is very useful to us :)

This is a quite interesting bug. We are going to fix is as soon as we can. You can track it here

[https://tree.taiga.io/project/penpot/issue/2029](https://tree.taiga.io/project/penpot/issue/2029)

**Comment by maelomanontroppo** [comment]
That was a quick one !
