### ISSUE TITLE
Add an option to show/hide UI 

### ISSUE THREAD

**Issue by Veethika** [penpot/penpot#1202]
## 🧩 Problem
The controls/menu options occlude a major part of the screen in the Penpot app. This makes it very challenging to do any design work on a small screen size(<15"). It also gets difficult to seek feedback on work in progress for the same reason.

## ✨ Proposal
Power users would like an option to show/hide the UI for higher efficiency.

**Comment by elhombretecla** [comment]
Hi @Veethika this is an interesting option. It would be great to have both workspace and view UI hide/show options.

You can track this enhancement here [https://tree.taiga.io/project/penpot/issue/2030](https://tree.taiga.io/project/penpot/issue/2030)

Thank you very much!

**Comment by Veethika** [comment]
This is great, thanks @elhombretecla 👍

**Comment by mairin** [comment]
This would be a wonderful enhancement. I want to add that other open source tools like Gimp and Inkscape allow for this via the Tab key shortcut.

**Comment by myfunnyandy** [comment]
Closing this as it has already been implemented.

**Comment by mairin** [comment]
Thank you - this is such a useful feature!

**Comment by Veethika** [comment]
Looking at this late but thanks so much ❤️
