### ISSUE TITLE
Group project level menu items semantically

### ISSUE THREAD

**Issue by Veethika** [penpot/penpot#1203]
## 🧩 Problem
There's no logical or semantic segregation of the menu items under the top left kebab menu dropdown
<img width="361" alt="Screen Shot 2021-09-11 at 11 05 27 PM" src="https://user-images.githubusercontent.com/35127763/132956431-ae71b9f1-448e-46df-b17b-f514f9acb1dd.png">

## ✨ Proposal
Group the items logically so that the items are easily discoverable.

**Comment by Veethika** [comment]
Happy to take up designing the proposal for this issue if others think there's value in this.

**Comment by elhombretecla** [comment]
Hi again @Veethika :)

This will be amazing!!! Your design proposal will be more than welcome ❤️

**Comment by Veethika** [comment]
Assigning myself, would add a proposal over the weekend 🙂 
Edit: Looks like I couldn't edit assignees 🤔
