### ISSUE TITLE
Spacebar + Drag not working for navigation

### ISSUE THREAD

**Issue by jsmorabito** [penpot/penpot#1208]
**Describe the bug**
I'm unable to navigate my canvas with spacebar and dragging my mouse. I noticed that spacebar + click + drag allows the same functionality but it feels more cumbersome than simply spacebar and drag. I'm noticing that spacebar + click + drag is the functionality in figma too but I still don't like it haha. What is the rationality behind the decision when there is less interaction cost for the former behavior?

**Desktop (please complete the following information):**

- big sur 11.5.2
- Safari Version 15.0 (16612.1.28.1, 16612)

**Comment by elhombretecla** [comment]
Hi @jsmorabito thanks for your feedback :)

There is a [github discussion open](https://github.com/penpot/penpot/discussions/517) about this behaviour. This was the decision we made when Penpot was released but we decide to change it in order to maintain a standard usage.

**Comment by jsmorabito** [comment]
Thank you for the explanation! It would be nice to be able to choose this behavior in a settings menu since spacebar and drag is more frictionless!
