### ISSUE TITLE
Copy and Paste not working

### ISSUE THREAD

**Issue by jsmorabito** [penpot/penpot#1209]
**Describe the bug**
Copy and paste will work once on occasion then get stuck on an item in the clipboard. In the video you can see I am trying to copy and paste the diamond and it will paste something id previously copied, not the diamond. this occurs with the hotkey. using the context menu copy and paste does not work entirely

**To Reproduce**
Try to use copy and paste both as hotkey and from context menu in latest safari beta

**Video**

https://user-images.githubusercontent.com/46250921/133141904-f38ebd2b-024f-4710-9a09-6b1f64919458.mov

**Desktop (please complete the following information):**

- big sur 11.5.2
- Safari Version 15.0 (16612.1.28.1, 16612)

**Additional context**
This problem is not occurring when I use Brave Browser

**Comment by niwinz** [comment]
Looks like Safari bug.

**Comment by niwinz** [comment]
Thanks for reporting, but it probably happens because previously you have been rejected the clipboard permission, and right now it does not works because penpot does not have permissions to use clipboard. Please review the page permissions and allow clipboard usage to penpot.

**Comment by jsmorabito** [comment]
> Thanks for reporting, but it probably happens because previously you have been rejected the clipboard permission, and right now it does not works because penpot does not have permissions to use clipboard. Please review the page permissions and allow clipboard usage to penpot.

Interesting, thanks for the comment. I'm having trouble figuring out how to allow clipboard usage for Penpot in the new Safari so I'm going to leave this issue open in the hopes that someone might come along with more advice. Will keep looking for a solution on my own in the meantime.

**Comment by Alotor** [comment]
I've been testing this and the problem is with the copying. Pasting seems to be good. (At least in Safari 15.4 with Monterey 12.3)

I know what's the problem with copying and will be solved for next release.
