### ISSUE TITLE
Builtin icon collections disappeared  in fresh installation

### ISSUE THREAD

**Issue by iblislin** [penpot/penpot#126]
I ran the `manage.sh run-release` docker builds on master branch.
But the builtin icon collection is empty. Any ideas?
![Screenshot from 2019-12-05 17-22-08](https://user-images.githubusercontent.com/761623/70221718-d16da580-1783-11ea-8f85-4c9b3bc2a426.png)

**Comment by niwinz** [comment]
Hi @iblis17,

To be honest i didn't remember that we have at master branch. It should be pretty outdated. We are working hard on it but the current code is not ready to be used (develop and other branches).

In any case the collections are not bundled in the installation, you need to load manually it, so from a fresh installation it's expected having this empty.

**Comment by iblislin** [comment]
Oh, I will try the `develop` branch.

**Comment by madmath03** [comment]
Hi @iblis17 ,

To complete what @niwinz said, you will find in the develop branch `README.md` a small documentation on how to import your icons / images collections: [Collections import](https://github.com/uxbox/uxbox/tree/develop#collections-import)

**Comment by iblislin** [comment]
ah, I got it. There is a dir named `sample_media` in the develop branch, but not in master.

**Comment by madmath03** [comment]
Yes, those are the sample icons that you can find at [demo.uxbox.io](https://demo.uxbox.io/) but were not provided in master branch.

For the images though, you will have to make your own collection using the documentation.

**Comment by iblislin** [comment]
Thanks for your patient explanation!
I successfully imported them.

**Comment by iblislin** [comment]
Is auto-importing the `sample_media` acceptable for all fresh installation? I can make a patch for it.

**Comment by iblislin** [comment]
And... I found another problem, seems the `icons` button in the workspace page of [demo.uxbox.io](https://demo.uxbox.io) is unfunctional at this moment.

**Comment by niwinz** [comment]
about auto-importing, i think no, because it is incomplete, there are also images collections but images are out of repository because of big files. Is much better a good documentation that automatic incomplete procediments.

And about icons on workspace, yes, they are temporary deactivated and probably broken. We are waiting for a some look and feel redesign so i focus my attention in other questions right now. I hope in a very near future we will have a fully functional workspace.

**Comment by iblislin** [comment]
ah, okay.

If the file size is the only issue, how about enabling [git-lfs](https://git-lfs.github.com/)?
So that we can load all sample meida (both icons and images) in to repo, and auto-import

**Comment by niwinz** [comment]
I have used git-lfs many times and it looks like a hack. It gives more problems that solutions. Importing is something that is done a single time on the installation so i think not having the "auto"-import is not a big problem. In any case, we can rethink it later when we have fixed all other more important things; for now i prefer don't mess with auto-import...
