### ISSUE TITLE
Mastodon account

### ISSUE THREAD

**Issue by 12people** [penpot/penpot#139]
As a person without a Twitter account, I'd like to be able to follow UXBOX news through RSS. As Mastodon offers an RSS option and also offers mirroring Twitter messages, it'd be great if UXBOX had a Mastodon account in addition to a [Twitter account](https://twitter.com/uxboxtool ).

**Comment by elhombretecla** [comment]
Hi Mirek!!! We have an uxbox mastodon account running!!! https://fosstodon.org/@uxboxtool/

See you there ;)
