### ISSUE TITLE
dockerfile imagemagick version

### ISSUE THREAD

**Issue by weaktyper** [penpot/penpot#37]
- update imagemagick version 

`7.0.4-6`  is out of date and not retrievable at url.

**Comment by studiospring** [comment]
Just replace all the version numbers in docker/Dockerfile:
7.0.4-6 => 7.0.4-7

**Comment by weaktyper** [comment]
Did so, just wanted to let you know, thanks.

**Comment by jdittrich** [comment]
now you need .4-8

**Comment by niwinz** [comment]
I'm going to upload somewhere a tar in order to have consistent docker builds. The imagemagick team does not maintains older tars :(
