### ISSUE TITLE
Question about the name change

### ISSUE THREAD

**Issue by Correct-Syntax** [penpot/penpot#377]
Hey there,

I was wondering if there was any specific reason you changed the name from Ubox to penpot? Penpot sounds a bit weird -especially vs. ubox.

Thanks.

**Comment by elhombretecla** [comment]
Hi Noah!

We need a new brand that fits better. In the beginning, UXBOX sounded really good to us, not only as a code name. It represents all the concept ideas we had in mind these days but starts to be deprecated as quickly as we define and develop the platform. The project needs a trademarkable (XBOX, you know...) and less-confusing brand to open it to the world in early 2021.

:)

**Comment by Correct-Syntax** [comment]
Yeah. I can understand that. "Penpot" just doesn't seem like a good replacement to me -not that I have any other ideas that would be better. ;)
