### ISSUE TITLE
NVM Git Clone Issues

### ISSUE THREAD

**Issue by parthmewada** [penpot/penpot#40]
Hi, i am facing the issues over NVM git clone. able to clone form the server but this docker file is uable to pull it. Can u please have look on the bellow error i faced.
![1](https://cloud.githubusercontent.com/assets/23476049/22966051/812074b4-f386-11e6-9ecd-4fb7c7be3bca.JPG)

**Comment by niwinz** [comment]
This is a just plain git clone, try it in your machine. I can't offer a reasonable help with this, because is completly unrelated to uxbox. It may be caused by network timeout, github small downtime or any other external issue of which I have control of.

Sorry for not being very helpful with that.

**Comment by parthmewada** [comment]
OK so can i skip this step and get the cloning done manually. Please help me with the directory. where i can clone manually and get this things done

**Comment by parthmewada** [comment]
Can i clone it manually and put this into working dir. Can you help me with the same.
