### ISSUE TITLE
Connection to Running UXBOX Docker Image 

### ISSUE THREAD

**Issue by parthmewada** [penpot/penpot#42]
Hi, 

when i try to reconnect the docker image, it restarts the process of running the app and thus it done finds uxbox under **/home/uxbox/** .  How to reconnect the running application Docker image/Container terminal. 

**NOTE: STILL THE APPLICATION IS ACCESSIBLE FROM WEB URL.**

**Comment by niwinz** [comment]
I'm not clearly understand...


The docker is for development and it designed to work so. Yo should not use
it as daemon service.

Yo sshould start docker perform some development and stop it. And so again
the next time. It is not designed for run forever and serve uxbox as
service...

**Comment by parthmewada** [comment]
OK Gotcha ;-)
