### ISSUE TITLE
View Mode Redirection 

### ISSUE THREAD

**Issue by parthmewada** [penpot/penpot#43]
When click on View Mode (Ctrl + P). The url dosent hold the IP on which the application is hosted. it goes to local host IP.

**Comment by niwinz** [comment]
The view and main are two different applications and they haw their own
config that should be changed acording to the environment of deploy.

The default config references localhost because the docker is a Developmen
environment.

**Comment by parthmewada** [comment]
Ok, Thanks @niwinz Great application by the way.
