### ISSUE TITLE
Support for User-Plugins?

### ISSUE THREAD

**Issue by Correct-Syntax** [penpot/penpot#437]
This is (probably) both a feature request and question:

*Will PenPot have support for user-created plugins, preferably in Python or JS?*

**Comment by niwinz** [comment]
It is on our roadmap. But for now we don't have any estimation when we start working on it. In any case, thanks for the suggestion. 

PD: I think, question like issues would be awesome open in "discussions".

**Comment by Correct-Syntax** [comment]
@niwinz,  O.k. 

> I think, question like issues would be awesome open in "discussions".

I think so too, now that Github has it. :)

**Comment by jdittrich** [comment]
Close and link to [Discussion](https://github.com/penpot/penpot/discussions/462)?
