### ISSUE TITLE
Rectangles and text boxes cannot be drawn right to left or bottom to top

### ISSUE THREAD

**Issue by studiospring** [penpot/penpot#44]
Drawing a rectangle from top left down works, but starting from any other corner does not. Text boxes have the same bug. Other drawing tools (circle, line etc) are fine. I guess that negative lengths cannot be drawn. 
![test](https://cloud.githubusercontent.com/assets/4901306/23107868/f8289e08-f758-11e6-8bb7-a247fb948b48.gif)

**Comment by niwinz** [comment]
Thanks!

**Comment by niwinz** [comment]
Fixed in master.
