### ISSUE TITLE
Autoconf missing

### ISSUE THREAD

**Issue by studiospring** [penpot/penpot#45]
FYI: I got the following error message when running the manage.sh script:

```
CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /imagemagick/config/missing autoconf
/imagemagick/config/missing: line 81: autoconf: command not found
WARNING: 'autoconf' is missing on your system.
         You should only need it if you modified 'configure.ac',
         or m4 files included by it.
```
Fixed it by adding autoconf to the Dockerfile :)

**Comment by niwinz** [comment]
It is very strange because I have rebuild the docker image yesterday and this didn't happened...

**Comment by studiospring** [comment]
This was at commit #185e9159. I cannot reproduce the bug because I deleted the repo and recloned because I got a node/npm error later on. I hope this is not a recurring problem because running the script from scratch takes a long time.
