### ISSUE TITLE
Close button does not close "new project" dialogue box

### ISSUE THREAD

**Issue by studiospring** [penpot/penpot#46]
Also, the close button does not change colour until I click it. It should change (I think) when I hover over it. I can only close the dialogue box if I click outside the box, but not on the close button.

Interestingly, I can close the "new color" dialogue box by clicking on the button (but again the colour only changes when I click it).
![close new project dialogue box](https://cloud.githubusercontent.com/assets/4901306/23245985/9d2504cc-f9e4-11e6-979c-d2f93393b604.gif)

**Comment by niwinz** [comment]
The close button on project form is fixed. The color and hover works correctly in chrome/chromium. Which browser you are using? Take care that at this moment only chrome/chromium is officially supported by uxbox app.
