### ISSUE TITLE
Clicking the Ruler icon does not do anything.

### ISSUE THREAD

**Issue by studiospring** [penpot/penpot#48]
Ruler is showing, whether the ruler icon is clicked or not.

Tested on Chromium and Firefox at commit #ba40b99c.

**Comment by niwinz** [comment]
The ruler was refactored some days ago, can you make sure that is not cache related issue. I strongly recommend open  the dev console of chromium and in the network tab activate **disable cache** (and maintain dev tool open for make effective that flag always). This will avoid a lot of false positives.

Thanks!

**Comment by studiospring** [comment]
I disabled cache, restarted app and reloaded page, but ruler icon still does not change anything.
![ruler](https://cloud.githubusercontent.com/assets/4901306/23301217/08ba98de-fadd-11e6-8ffa-5ad83b53e591.jpg)
![ruler_on](https://cloud.githubusercontent.com/assets/4901306/23301220/0f559d60-fadd-11e6-9f89-a38983acc5aa.jpg)

**Comment by niwinz** [comment]
The ruler as is, not changes anything visually, is starts the ability to measure things:
![uxbox](https://cloud.githubusercontent.com/assets/843689/23301454/4acc6fca-fa8a-11e6-9f06-62391886ed11.png)

**Comment by studiospring** [comment]
Thank you for explaining!!! I thought the ruler icon shows/hides the ruler. Perhaps the ruler icon needs to be separated from the grid icon (which shows/hides a page attribute), instead of placing them together! I will create a new UX issue.
