### ISSUE TITLE
Test automation 

### ISSUE THREAD

**Issue by myfunnyandy** [penpot/penpot#4803]
### Is your feature request related to a problem? Please describe.

Test automation 

### Describe the solution you'd like.

Test automation

**Comment by madalenapmelo-kp** [comment]
Hi @myfunnyandy,

Thank you for the suggestion! We have added it to our backlog on Taiga to be considered in the future, you can find the details at https://tree.taiga.io/project/penpot/issue/8192

**Comment by madalenapmelo-kp** [comment]
This has now been implemented and it will be released soon!
