### ISSUE TITLE
Testing automation

### ISSUE THREAD

**Issue by myfunnyandy** [penpot/penpot#4804]
### Is your feature request related to a problem? Please describe.

Testing automation

### Describe the solution you'd like.

Testing automation

**Comment by madalenapmelo-kp** [comment]
Hi @myfunnyandy,

Thank you for the suggestion! We have added it to our backlog on Taiga to be considered in the future, you can find the details at https://tree.taiga.io/project/penpot/issue/8198

**Comment by madalenapmelo-kp** [comment]
Hi myfunnyandy,

The team has reviewed this request and this is not something that we plan to address in the foreseeable future. You can find more about the motivations for this decision at the Taiga issue: https://tree.taiga.io/project/penpot/issue/8198

**Comment by madalenapmelo-kp** [comment]
This has now been implemented and it will be released soon!
