### ISSUE TITLE
Keyboard collision for many keyboard shortcuts

### ISSUE THREAD

**Issue by studiospring** [penpot/penpot#49]
Many of the uxbox keyboard shortcuts are standard browser keyboard shortcuts (on Chrome, Firefox, Edge for Windows/Linux). For example:
Ctl-R -> reload page
Ctl-Shift-H -> open history window
Ctl-Shift-O -> open bookmarks window
See [Chrome](https://support.google.com/chrome/answer/157179?hl=en), [Firefox](https://support.mozilla.org/t5/Basic-Browsing/Keyboard-shortcuts-Perform-common-Firefox-tasks-quickly/ta-p/3866), [Edge](http://www.windowscentral.com/microsoft-edge-keyboard-shortcuts) and [Safari](https://support.apple.com/kb/PH21483?locale=en_AU) keyboard shortcuts for details.

Whoever designed uxbox's shortcuts was obviously using a Mac ;-)

I can suggest some hopefully better shortcuts (later) if you want.

**Comment by niwinz** [comment]
I have used many of them and I'm not mac user... but thanks! We have already task for revisit that part: https://tree.taiga.io/project/uxbox/issue/223
