### ISSUE TITLE
Export as HTML does not work

### ISSUE THREAD

**Issue by studiospring** [penpot/penpot#51]
Clicking the "Export HTML" button does nothing in Chromium or Firefox.

**Comment by niwinz** [comment]
This is because that functionality is not implemented. Maybe we should hide it for the first release @elhombretecla ?

**Comment by elhombretecla** [comment]
Ok.

Now is temporarily hidden until the implementation will be finished

**Comment by amira133** [comment]
dose `Export HTML` implemented?
