### ISSUE TITLE
Duplication of images

### ISSUE THREAD

**Issue by girafic** [penpot/penpot#515]
**Describe the bug**
BG images are duplicated when new objects are created.

**To Reproduce**
1.  Add an image
2.  Create rectange/text/circle

**Screenshots**

https://user-images.githubusercontent.com/1187276/106590202-24d8b080-654d-11eb-9d52-b34d6983c5f0.mp4

**Comment by hirunatan** [comment]
Ok, i'll look at it. Thank you for reporting.

**Comment by hirunatan** [comment]
@girafic This should be solved by now. Coud you please try again? Thanks.

**Comment by girafic** [comment]
Thx, works fine now 👍.
