### ISSUE TITLE
bug: When using Chinese input method to edit text, it will crash.

### ISSUE THREAD

**Issue by Elric-li** [penpot/penpot#5174]
### Steps To Reproduce

1. Create text components.
2. Double-click the text component and edit the content using the Chinese input method.
3. Press Enter to confirm the input,the page crashes.

### Expected behavior

I hope I can type Chinese normally.

### Actual behavior

[report.txt](https://github.com/user-attachments/files/17390156/report.txt)

**Comment by madalenapmelo-kp** [comment]
Hi @Elric-li,

Thanks for reporting - this is a known issue that we are already working on fixing, though we don't yet have an exact ETA.

I'm closing this issue here as this is already being tracked on https://github.com/penpot/penpot/issues/4163.
