### ISSUE TITLE
Export icon is unclear.

### ISSUE THREAD

**Issue by studiospring** [penpot/penpot#53]
The export icon is very similar to the common "share" icon.
![export](https://cloud.githubusercontent.com/assets/4901306/23345680/3f0fb47c-fce6-11e6-9a0c-04b5c13543d8.jpg)      ![icon-share-128](https://cloud.githubusercontent.com/assets/4901306/23345651/d9a6c134-fce5-11e6-9a5b-1a9d84e0d2cf.png).
In View mode, the same icon has a "share" tooltip.
![share](https://cloud.githubusercontent.com/assets/4901306/23345676/237e5a92-fce6-11e6-9439-05eeed4fb1af.jpg)
In the export dialogue box, all the explanations use the word "download".
Perhaps, the export icon should be called "download" and the icon changed to reflect this.

**Comment by elhombretecla** [comment]
Hi!!!

Thanks a lot for your feedback. It's very useful :)

I'm agree with this issue and we recently applied the new icon and text.

Thanks!

![icons](https://cloud.githubusercontent.com/assets/1045247/23353353/55221404-fccc-11e6-989d-d6fc1b04599d.png)

**Comment by studiospring** [comment]
> we recently applied the new icon and text.

Very recently! Thanks.
