### ISSUE TITLE
Live preview when editing paths

### ISSUE THREAD

**Issue by eldelacajita** [penpot/penpot#536]
**Is your feature request related to a problem? Please describe.**
When I'm creating or editing a path or a curve, I'd love to see the actual trace of the path being updated as I move or edit the nodes.

**Describe the solution you'd like**
Constantly update the path at all times, even during creation and transformation, so I can get a better visual feedback on what I'm doing. This is already the case with rectangles and other shapes.

**Describe alternatives you've considered**
None. This is quite straightforward.

**Additional context**
I'm 99% sure you already have this on the roadmap (can you confirm?) but I just wanted to file an issue :yum: Other people may come here looking for the same.

**Comment by Alotor** [comment]
This is actually a bug. Should behave as you're describing we'll look into it asap. 

Thanks!

**Comment by Alotor** [comment]
It's now fixed in our development branch. Will be fixed on the next deploy we do. Cheers.

**Comment by eldelacajita** [comment]
Awesome! That was fast!
