### ISSUE TITLE
Rendering issue with shadows after zooming in and out with Blink based browsers

### ISSUE THREAD

**Issue by Manueljlin** [penpot/penpot#539]
# Describe the bug

**To Reproduce**
1.  Create an object on the canvas
2.  Apply a drop shadow (easier to see with 1px non-blurred shadows)
3.  Create another object above, without touching the object or shadow itself
4.  Zoom in, then set zoom back to 100%
5. Reload the tab, and it's fixed

---
## Expected behavior
![image](https://user-images.githubusercontent.com/11275573/106742201-fe824600-661c-11eb-879f-cd39992f45c8.png)
![image](https://user-images.githubusercontent.com/11275573/106742570-7c465180-661d-11eb-9ea0-706b1f0c35ec.png)
![image](https://user-images.githubusercontent.com/11275573/106742201-fe824600-661c-11eb-879f-cd39992f45c8.png)

---
## Screenshots
In this example, the sidebar is above 
![image](https://user-images.githubusercontent.com/11275573/106742201-fe824600-661c-11eb-879f-cd39992f45c8.png)
![image](https://user-images.githubusercontent.com/11275573/106741887-992e5500-661c-11eb-954a-a6bdca2c4b3f.png)
![image](https://user-images.githubusercontent.com/11275573/106742001-bd8a3180-661c-11eb-9b2e-5e82b92643ed.png)

**Desktop (please complete the following information):**

-   OS: Windows 10
-   Browser: Vivaldi 3.5.2115.81 (based on Chromium 87.0.4280.107 according to the UA), Edge Chromium 88.0.705.56

Using the [design.penpot.app](design.penpot.app) instance

**Additional context**
Works completely fine on Firefox+Linux (with KDE Neon & openSUSE Tumbleweed)

**Comment by niwinz** [comment]
Hi @Manueljlin 
Thanks for the report, we will look at it as soon as possible; [taiga issue](https://tree.taiga.io/project/penpot/issue/1197)
