### ISSUE TITLE
"Export project" button in "Export options" dialogue box does not state what format is zipped.

### ISSUE THREAD

**Issue by studiospring** [penpot/penpot#54]
I do not know if the zipped files are svg or html or other. Perhaps explain as "Download all pages as svg in a zip file."

**Comment by elhombretecla** [comment]
Done.

Thanks!

![download](https://cloud.githubusercontent.com/assets/1045247/23353464/e553eb06-fccc-11e6-9eb9-b803660d13d1.png)
