### ISSUE TITLE
Add direction option (RTL support)

### ISSUE THREAD

**Issue by ahangarha** [penpot/penpot#542]
**Is your feature request related to a problem? Please describe.**
It would be great to add option to assign direction to elements. Text elements need direction setting for sure but also they can inherit direction from their parent element (let's say page!)

**Describe the solution you'd like**
Add option of selecting direction!

**Describe alternatives you've considered**
Actually there is no alternative.

**Additional context**
If you have no idea about RTL text, maybe you can use the following text:

یک two سه four

which should look like below text if the direction is set to RTL:

‫یک two سه four

Just make sure (right/left) alignment also works fine.

**Comment by myfunnyandy** [comment]
That is a great suggestion. 

I've seen very few alternatives to do it on other tools, always via plugins that never work properly. We are definitely adding this to our roadmap.

Thanks!

**Comment by jdittrich** [comment]
@ahangarha are there tools that solve this well that could serve as a positive example?

**Comment by tomer** [comment]
As a quick workaround, adding `unicode-direction:plaintext` CSS rule to text fields should solve this for paragraphs that starts with RTL character. Changing alignment is strongly not recommended, as it makes the content block to look similar to RTL content, but with different wording order. Changing direction attributes should make the content right-aligned automatically.

**Comment by myfunnyandy** [comment]
Leaving the user story at Taiga here: [https://tree.taiga.io/project/penpot/us/1106](https://tree.taiga.io/project/penpot/us/1106). 

We are cross-linking github and taiga issues so we will have into account the suggestions made here once we approach the definition of the user story.

**Comment by ahangarha** [comment]
Please don't go for bidi support since that is not the norm yet. There
should be RTL/LTR Option right beside left/center/right alignment.

And make sure you don't use alight:start/end for alignment functionality.

در تاریخ جمعه ۵ فوریهٔ ۲۰۲۱،‏ ۱۹:۱۲ andrés gonzález <
notifications@github.com> نوشت:

**Comment by niwinz** [comment]
This issue/enhacement is already addressed on the latest release. thank you

**Comment by ahangarha** [comment]
Amazing...

Thank you for your consideration.
