### ISSUE TITLE
Strange behavior with shape strokes

### ISSUE THREAD

**Issue by Manueljlin** [penpot/penpot#544]
**Describe the bug**
When inner or outer strokes are added to shapes, it just clips the other part instead of changing it, so that means that an outer or inner stroke would need to be 2px wide to effectively behave like 1px

**To Reproduce**
1.  Create an object
2.  Add stroke
3.  Change from centered to any of the other two options

**Expected behavior**
![image](https://user-images.githubusercontent.com/11275573/106748253-4311df80-6625-11eb-98d0-ad881b0d2fb1.png)
![image](https://user-images.githubusercontent.com/11275573/106748284-502ece80-6625-11eb-9721-8d212adbb784.png)
![image](https://user-images.githubusercontent.com/11275573/106748314-5cb32700-6625-11eb-8a72-9ba09f56c0a3.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/11275573/106748667-da773280-6625-11eb-8781-8025ecdb2f64.png)
Centered: 1 pixel

![image](https://user-images.githubusercontent.com/11275573/106748810-05fa1d00-6626-11eb-8472-084781c59fcf.png)
Inside: 0.5px

![image](https://user-images.githubusercontent.com/11275573/106748935-3772e880-6626-11eb-83d2-4525c3774351.png)
Outside: same as centered when translucent, 0.5px when opaque

Using the demo instance.

**Comment by Alotor** [comment]
Wow, amazing bug report :smile: 

I'll try to fix it asap. Thanks

**Comment by hirunatan** [comment]
Thanks for the report. This behavior was already done the way you say, but there was a bug that prevented its application.

You will see the fix in the next server update.
