### ISSUE TITLE
Allow to move files between projects (and teams)

### ISSUE THREAD

**Issue by violoncelloCH** [penpot/penpot#547]
**Is your feature request related to a problem? Please describe.**
It's really simple to create files and start prototyping, but now I've got those files all in the "Drafts" section. Only then I'm realizing that I can create projects to organize those files. However it doesn't seem to be possible to move files between Projects

**Describe the solution you'd like**
Allow for files to be moved between projects (and possibly even teams). Ideally this should be possible both, over the context/three-dot menu and via drag'n'drop.

**Describe alternatives you've considered**
I don't really see any alternative here.

**Additional context**
Nothing for now. But Penpot looks and feels great!

**Comment by myfunnyandy** [comment]
Hi, we are already working on improvements for file management at the dashboard and moving files between projects is among them. Thanks for raising the interest, and thanks for the end remark :smiley:

**Comment by myfunnyandy** [comment]
Still needs definition, and it will probably split in several user stories, but leaving here the [Taiga User Story](https://tree.taiga.io/project/penpot/us/267?milestone=262806).

**Comment by hirunatan** [comment]
Done! This will be in the next release.

**Comment by jancborchardt** [comment]
Super cool, thank you so much! :) We’re now starting to use Penpot more and more for Nextcloud. :)
