### ISSUE TITLE
History version numbers sometimes skip numbers.

### ISSUE THREAD

**Issue by studiospring** [penpot/penpot#55]
![history](https://cloud.githubusercontent.com/assets/4901306/23358501/4fbd02e8-fd36-11e6-8c0b-6bb0f6f31129.jpg)

**Comment by niwinz** [comment]
Yes, this is expected. It happens when no real change is performed (when the previous and the curent version are identical).

**Comment by niwinz** [comment]
Or a change implies something not versioned such as page name change.

**Comment by studiospring** [comment]
You mean versions are squashed like git commits, which changes the number? I think it would be easier for the user to understand if numbers were sequential. Here it looks like versions are missing.

**Comment by niwinz** [comment]
I mean that when you perform some change on the page and the result of comparing the previous page data with the current page data is the same, no new history entry is created.

With **page data** I'm refering to the blob of data which contains the shapes. Page entity also contains metadata and some additional attributes such as name. That attributes are not versioned.

The version number is atomic and is incremented on each request of change independently if the history entry will be created or not. Maybe there are other ways to do it but that approach works for now. I'm open to revisit this part (and maybe include more attrs to the versioning, but we need more thought on it)
