### ISSUE TITLE
moving object with arrow keys makes it hide / disappear while moving

### ISSUE THREAD

**Issue by violoncelloCH** [penpot/penpot#551]
**Describe the bug**
When moving an object with the arrow keys on my keyboard, while moving the object, it begins to disappear behind the canvas (in the direction you're about to move it). The object reappears once I release the arrow key.

**To Reproduce**
1.  On an empty canvas create (with or without an Artboard) create a (grey) square object
2.  move that square with the arrow keys (press and hold one of the arrows) on the keyboard
3.  see the object slowly disappearing behind the canvas in the direction you're about to move it

**Expected behavior**
The object should be fully visible while moving it.

**Screenshots**
here I'm moving the square downwards:
![image](https://user-images.githubusercontent.com/22591354/106754883-c9caba80-662d-11eb-8271-58fd92a83d69.png)

**Desktop (please complete the following information):**

-   OS: Linux (Manjaro Gnome)
-   Browsers: Firefox 85, Brave 1.19.88 (based on Chromium 88.0.4324.96)

**Environment (please complete the following information):**
self-hosted

-   OS Version: Ubuntu 16.04
-   Docker / Docker-compose Version:  Docker version 20.10.2
-   Image official docker-compose

unmodified, official docker-compose

**Comment by violoncelloCH** [comment]
cool, thanks for the quick fix!

**Comment by Alotor** [comment]
Thank you for the report! We'll be pushing new changes to the server today so you'll see it soon.
