### ISSUE TITLE
Possible sign-up bug: Google sign-up only appearing after account validation

### ISSUE THREAD

**Issue by jdittrich** [penpot/penpot#553]
**Describe the bug**
When I wanted to sign up I looked for a sign-up-with-* button. 
As none was there, I signed up with my mail. 
After I validated my mail, I got a sign-up-with-google button. 

**To Reproduce**
1. Create a new account with mail and password
2. Validate Mail
3. See login page

**Expected behavior**
Usually, I would expect a "sign up with [service]" to be there right from the start to ease signing up to the product.

**Screenshots**
Before 
<image src="https://user-images.githubusercontent.com/3416487/106763000-aeb07880-6636-11eb-91a3-1a7b2a691b74.png" width="300" alt="sign up from lacking 'a sign in with google'-button" />

After validation
<image src="https://user-images.githubusercontent.com/3416487/106763044-b96b0d80-6636-11eb-98cf-a19f18736331.png" width="300" alt="log in from showing a 'sign in with google'-button" />

**Desktop (please complete the following information):**

-   OS: Ubuntu 20.4
-   Browser: firefox 85

**Comment by ianrumac** [comment]
+1 on this issue.
Had the same occur - also wasn't obvious at first I got an email, so then I created an account with Google and noticed the email after that. The snackbar at the top disappears too fast, but that is an issue for itself.

**Comment by hirunatan** [comment]
Thanks for the warning. We have fixed it, you can see it now in penpot.app.
