### ISSUE TITLE
Email verification snackbar disappears too fast

### ISSUE THREAD

**Issue by ianrumac** [penpot/penpot#556]
**Describe the bug**
E-mail verification snackbar dissapears too fast.

**To Reproduce**
1.  Open https://design.penpot.app/#/auth/register
2.  Create an account
3.  Try to read the snackbar at the top before it dissapears

**Expected behavior**
The snackbar remains until dismissed by the user or has a longer duration. 

**Screenshots**
<img width="1104" alt="Screenshot 2021-02-03 at 17 15 52" src="https://user-images.githubusercontent.com/6658593/106775516-7bc0b180-6643-11eb-8f25-7448fc4b434d.png">

**Desktop (please complete the following information):**

-   OS: macOS
-   Browser: Brave
-   Version 1.18.78 Chromium: 87.0.4280.141 (Official Build) (x86_64)

**Additional context**

So I went to register, created an account, tried to login with the mail and password and noticed it didnt work. Then I used my google account to login which worked. After a while, I noticed the verification email. Only after re-registering to test it did I notice that a snackbar appeared, but still it was gone too fast to read the message. I'd suggest leaving it there for a longer time or indefinitely.

**Comment by myfunnyandy** [comment]
You're absolutely right, the need of email verification is not explicit enough. Other users raised their concerns about this issue too through different channels.

We are currently working on an slight change on the register flow that should fix it. Once registered you won't be redirected to login but to an screen that asks you to check your email.

**Comment by niwinz** [comment]
We have fixed the login/register frow to be more explicit and increase the duration of flash messages.
Thanks for the report.
