### ISSUE TITLE
Allow creation of a "public" shared library/libraries

### ISSUE THREAD

**Issue by brianredbeard** [penpot/penpot#562]
**Is your feature request related to a problem? Please describe.**
As a new user, I'd like to minimize my time on-boarding with ~UXBOX~ Penpot. One way of achieving this is to stand on the shoulders of existing design kits/frameworks.  Presently, as a user, even if I am attempting to use a design kit whose assets are available under a free/libre license my first step is to collect the assets and upload all of them to Penpot.

**Describe the solution you'd like**
Related to #88, it would be ideal if a mechanism for _public_ shared libraries.  These would be shared libraries free for all users to consume.  It would be ideal if design kits (available under a free/libre license) could be contributed to the upstream to be available to all Penpot users.

I'll use [PatternFly](https://github.com/patternfly/patternfly) as an example.  

Presently PatternFly [instruct their users](https://www.patternfly.org/v4/get-started/design/) to download assets download assets and begin using "Sketch" or "Figma" as a part of their "Getting started with PatternFly" instructions.  As a user just getting started with _PatternFly_ with no previous experience with either "Sketch" or "Figma", I would prefer to invest my effort in the use of free/libre ecosystems.

I would imagine the "public" shared library would be a "team" (run/owned by the organization hosting Penpot) whereby libraries can be administered through that "team" (and even made public/private from there).  This would also provide additional benefits like:
  - organizations installing Penpot can pre-load company proprietary design kits ensuring all users have access with zero effort
  - for the administrators of https://design.penpot.app content can be quickly "hidden" in the event of accidental presentation of assets _not_ licensed appropriately (imagine someone trying to submit a purloined font, set of glyphs, etc).

**Describe alternatives you've considered**
A variation on this theme exists via the [Figma Community](https://figma.com/community/). In this model, a user can browse a "gallery" of content and select items to import into their account.

**Additional context**
The gallery model does have one benefit insomuch as users do not need to worry about their content being "broken" if the community version changes (the import is a snapshot in time).  This could easily overcome though by a user being able to "clone" a file. Effectively the "clone" would perform a copy operation on the `file` asset into the users account/library creating the element with a new id in the file database table.  Furthermore, like a shared library on a host, this means that a single update can be quickly consumed by many users allowing for quicker iteration and easier adoption of "alpha" design kits.

From a hosting perspective, the shared library mechanism also has the ability to reduce storage of commonly used/re-used assets.

_Edit_: Fixed formatting/punctuation mistakes.

**Comment by elhombretecla** [comment]
Hi Brian!!! Thanks for your feedback.

We are working on creating a marketplace/gallery where all users can share resources with the community. Whether you are a designer or not, it would be helpful to have quality resources to improve your designs or starting from scratch. The examples you propose are very good. We will study and review them to see what we can learn from them. We will take this into account when we face the development of all this new functionality.
