### ISSUE TITLE
radius option

### ISSUE THREAD

**Issue by ssmns** [penpot/penpot#563]
In the app, the radius option is fixed for all corners. the option that enables us to modify the radius for each corner  is necessary

**Comment by elhombretecla** [comment]
Thank you very much for your feedback!!!

Border radius advanced settings are included and high prioritized in our project roadmap. We will develop it soon :)

**Comment by myfunnyandy** [comment]
Leaving here [the US in Taiga](https://tree.taiga.io/project/penpot/us/411?no-milestone=1)
