### ISSUE TITLE
Inconsistent naming: "Shapes" and "Draw tools"

### ISSUE THREAD

**Issue by studiospring** [penpot/penpot#57]
![shapes](https://cloud.githubusercontent.com/assets/4901306/23359697/9bbe4436-fd3b-11e6-8c84-0563899a112b.jpg)  ![draw](https://cloud.githubusercontent.com/assets/4901306/23359703/9fa9cf98-fd3b-11e6-986a-3eda277cadd7.jpg)
"Canvas tools" may be a better name. The ruler tool would fit semantically with these tools then.

**Comment by elhombretecla** [comment]
Done
