### ISSUE TITLE
Import proprietary fonts

### ISSUE THREAD

**Issue by BernhardHH** [penpot/penpot#582]
I have been waiting long to testdrive penpot, and I am not disappointed - it's much more intuitive than Pencil or Adobe UX, even (at least for me).

I have figured out how to "group" items by creating components but one thing still misses for me: **how can I import proprietary fonts** (WOFF preferably)? Did I miss the general user manual? https://github.com/penpot/penpot/tree/develop/docs did not help me for that :)

Currently, I use the hosted version (https://design.penpot.app/) but if needed, getting a docker version to run on our side should be no problem.

Cheers, 

Bernhard

**Comment by myfunnyandy** [comment]
Hi @BernhardHH, thanks for such kind words :)

You did not missed anything. For the moment you can not import local fonts, but we have planned a lot of improvements regarding font management, and importing local fonts is among them.

I will crosslink this issue with the Taiga user story so we can take into account what is said here too: [https://tree.taiga.io/project/penpot/us/292](https://tree.taiga.io/project/penpot/us/292)

**Comment by NicolasLeboeuf** [comment]
This issue can be closed, as the font import is available.
