### ISSUE TITLE
Import SVG

### ISSUE THREAD

**Issue by der-On** [penpot/penpot#589]
To be able to port existing projects/files to penpot, I'd like to be able to import SVG files into penpot.

For this, I'd like to have an import file button on the dashboard that, when clicked opens a local file browser and allows me to select a local SVG file. Once selected the file will be imported into penpot as a new file. See the attached screenshot, on where to find the import button in figma:
![figma_import_file](https://user-images.githubusercontent.com/359399/107143878-bb371880-6937-11eb-88f8-3f6d23879a6b.png)

An alternative approach would be to decompose SVG images, that have been placed inside a file using the "Image" tool or by drag-n-drop onto the canvas. However I thinks this approach could be more complex then the one described above.

**Comment by myfunnyandy** [comment]
Hi, importing and editing SVGs is actually among our main priorities. We hope to release it soon :)

**Comment by niwinz** [comment]
On the next release you will be able to upload more complex svg files into the workspace (penpot file); 

I know that it is not the same as proposed in this issue, but can be a workaround until we implement the native import (and export).

**Comment by canonex** [comment]
Is there any news on this?
I am new to using Penpot and the ability to edit vectors with an external software would increase productivity tremendously!
This could also allow complex path manipulation.

I think this could be related with: #838 #1097 #546 

Thank you!
Riccardo

**Comment by niwinz** [comment]
You already have the ability to import plain svgs to workspace, also you have the ability to export distinct assets/shapes to png/jpg/svg, and you also has the ability to export and import penpot files (for backup or for importing it in a selfhosted instance)

In fact this issue should be considered closed.
The related ones they have they own nuances.

**Comment by canonex** [comment]
Thank you.
I apologize to get back on topic, I couldn't find in the guide (or even making some attempts) any way to import svg into the workspace... can you direct me?

**Comment by niwinz** [comment]
https://help.penpot.app/user-guide/objects/#images

**Comment by der-On** [comment]
I can confirm that drag & drop of svg files now works and imports these SVGs inline.
I've however found some issues during that test and will create/search for issues regarding those.
