### ISSUE TITLE
Lock icon for size and radius is unclear.

### ISSUE THREAD

**Issue by studiospring** [penpot/penpot#59]
Only the colour changes, not the shape. This makes it difficult to remember which is which and tell the difference, especially for colour blind people. Hovering over the icon also changes the icon to the same colour as locked, but does not change the state, unless you click, which makes things even more confusing. A slightly bigger icon would be even clearer!
Screenshot is from firefox, but Chromium is similar.
![lock](https://cloud.githubusercontent.com/assets/4901306/23389778/4cf981e8-fdbe-11e6-94f5-c170919d08fd.jpg)

**Comment by studiospring** [comment]
Locking "layers" uses the same icon (but different colour!). Separate locked/unlocked icons consistent with other lock icons would be good here too.

**Comment by niwinz** [comment]
Fixed
