### ISSUE TITLE
Contributor License Agreement?

### ISSUE THREAD

**Issue by kreba** [penpot/penpot#590]
Found out about this project via FOSDEM :)

You mention in [CONTRIBUTING.md](https://github.com/penpot/penpot/blob/develop/CONTRIBUTING.md#pull-requests) that pull requests are subject to a CLA. But I can't find such a section or document. Where is the CLA, please?

--
(There is also a minor typo in the word Ag(g)reement.)

**Comment by niwinz** [comment]
There are no CLA, is just a DCO (Developer's Certificate of Origin); we are fully commited with opensource and don't require CLA.

**Comment by kreba** [comment]
Glad to hear that you are committing to open source. I suggest to leave this issue open until the CONTRIBUTOR.md is changed accordingly. I quickly thought about creating a PR for this – but I think it's best when someone from the core team does the writing.

**Comment by niwinz** [comment]
Hmm, as far as I know, the `CONTRIBUTING.md` is already changed on the `develop` (default branch).

**Comment by niwinz** [comment]
Oh, I see, what you saing. You are right!

**Comment by niwinz** [comment]
now this should be considered fixed :D
