### ISSUE TITLE
Text in preview (project overview) is centered while actually being left aligned

### ISSUE THREAD

**Issue by violoncelloCH** [penpot/penpot#594]
**Describe the bug**

**To Reproduce**
1.  create a file
2.  add some left-aligned text
3.  go back to the team / project overview
4.  see text being centered in the small preview (see screenshot)

**Expected behavior**
text in preview should be aligned as in the real file

**Screenshots**
file:
![image](https://user-images.githubusercontent.com/22591354/107160236-51e5f280-6995-11eb-9929-3a355959c081.png)
preview:
![image](https://user-images.githubusercontent.com/22591354/107160243-632eff00-6995-11eb-97e4-62182ade1efb.png)

**Desktop (please complete the following information):**

-   OS: GNU/Linux (Manjaro, Gnome)
-   Browser: Firefox
-   Version: 85

**Comment by elhombretecla** [comment]
Thank you very much for your report!

**Comment by violoncelloCH** [comment]
Wohoo, thanks for the fix @Alotor !
