### ISSUE TITLE
Frontend should have the demo warning and users settings of config.js in the ENV

### ISSUE THREAD

**Issue by sardaukar** [penpot/penpot#597]
To make it easier to configure with docker-compose.

**Comment by madmath03** [comment]
@niwinz I think we've got a solution for that: on our [alternative frontend docker image](https://github.com/Monogramm/docker-penpot-frontend) we created a template [`config.js`](https://github.com/Monogramm/docker-penpot-frontend/blob/master/template/config.js) and a custom [`entrypoint.sh`](https://github.com/Monogramm/docker-penpot-frontend/blob/master/template/entrypoint.sh) that will enable and update the commented properties of the configuration.

What do you think of this approach ?
Would you like a PR with that ?

**Comment by niwinz** [comment]
Yes, more than welcome!

**Comment by niwinz** [comment]
@madmath03 the frontend config variable prefix is changed from `app` to `penpot` FYI

**Comment by niwinz** [comment]
Will be available on the next release
