### ISSUE TITLE
Disallowing registration should remove the sign up option from the login form

### ISSUE THREAD

**Issue by sardaukar** [penpot/penpot#598]
Right now, it still lets you do it (but errors out with a red banner at the top). 

In addition, setting the email domain whitelist doesn't give a meaningful error message when you use an email address from a non-whitelisted domain, it just shows the same generic red error banner at the top of the page.

**Comment by niwinz** [comment]
Hi @sardaukar 

This looks like a bug :P
We annotate it and fix as soon as posible. [taiga issue](https://tree.taiga.io/project/penpot/issue/1196)

Thanks.

**Comment by hirunatan** [comment]
This has been solved. https://github.com/penpot/penpot/pull/684

You will see it in the next release.
