### ISSUE TITLE
Explain uxbox's vision in Readme and landing page.

### ISSUE THREAD

**Issue by studiospring** [penpot/penpot#60]
A vision of what uxbox aspires to be will encourage early adoption and contribution. Contributors will be able to decide if uxbox is a project that they want to contribute to. This also helps keep uxbox on track. It also improves transparency. See [Jared Spool's 3Qs](https://articles.uie.com/the3qs/).

The vision should describe uxbox's raison d'etre. This boils down to:
- values of the organisation
- what differentiates uxbox from other prototyping tools
- why you are building uxbox. What pain points are you trying to solve.
- a description of what uxbox intends to be at version 1 (?)

**Comment by elhombretecla** [comment]
We are working on a new website with all this info included. Hope to finish it soon :)

Meanwhile I update the README with some new info :)

**Comment by studiospring** [comment]
Thanks @elhombretecla. Is the new website going to be on GitHub as well?

**Comment by elhombretecla** [comment]
Yes! We will create a new repository for it :)
