### ISSUE TITLE
USABILITY ISSUE: After going into View Mode (G V), you need to click the main icon on the left to get out of the view mode again.

### ISSUE THREAD

**Issue by ghost** [penpot/penpot#607]
**Describe the bug**
After going into View Mode (G V), you need to click the main icon on the left to get out of the view mode again. This isn't intuitive and really confusing as the penpot icon actually should always lead to the project board.

**To Reproduce**
1. Click on the play icon (view mode G V) on the right
2. At the place on the top right, where an "X" should lead the way out of the view mode (back to the artboard with layers), there's only the full screen button.
3. After taking some time to find out how to get out of it, you "just" click the penpot icon again.

**Expected behavior**
As written, an "X" or any other solution would make more sense in this particular place, but not the penpot icon on the left, which should always lead to the project dashboard.

**Desktop (please complete the following information):**

-   OS: macOS 11.1
-   Browser Firefox 85.0

**Comment by myfunnyandy** [comment]
Hi, at the View mode header you there is an "Edit page" button to got to the edit mode. An "X" button wouldn't be appropiate as is a View is a different page as Edit, not an overlay that you can close.

In any case we agree that the standar behaviour at click on the Penpot icon should be to go to the Projects section at the dashboard. We created an issue to solve that: https://tree.taiga.io/project/penpot/issue/1149

**Comment by ghost** [comment]
Ah, well! That "Edit page" button didn't work for me for some reason and I understood something else under "Edit page", but thank you for clarification! And by the way: you guys made an awesome job on this, even though it's only the alpha version, it works very well and looks really promising! Can't wait to get started and I already told my collegues about it!

**Comment by myfunnyandy** [comment]
Thank you for such kind and encouraging words and for spreading the word, it means a lot for us!
