### ISSUE TITLE
Default sizing method can lead to accidentally distorted images

### ISSUE THREAD

**Issue by jancborchardt** [penpot/penpot#609]
**Describe the bug**
When inserting an image and wanting to resize it, the default sizing method doesn’t keep the format of the image, distorting it.

**To Reproduce**
1. Insert an image
2. Resize it 
3. Accidentally don’t hold down shift
4. End up with weirdly resized image

**Expected behavior**
Some software uses proportional sizing by default, and you have to use Shift to _not_ use it.
Figma for example uses a container around images and thus in the worst case only crops them, but never distorts the dimensions of an image.

**Screenshots**
Stuff like this is very easy to accidentally do | In Figma, cropping is the worst that can happen
-|-
![image](https://user-images.githubusercontent.com/925062/107347309-f9fad900-6ac5-11eb-9186-3d35316087e1.png)|![image](https://user-images.githubusercontent.com/925062/107347728-6970c880-6ac6-11eb-95d6-d20932123dea.png)

**Desktop (please complete the following information):**

-   OS: Ubuntu 20.04
-   Browser: Firefox
-   Version: 85

**Environment (please complete the following information):**
Using demo.

**Comment by hirunatan** [comment]
Hi. Thanks for the report! Other people also pointed us to this, and it's already solved. You will see it next time we update the public site.

**Comment by jancborchardt** [comment]
Thanks so much about this btw, it’s soooo much better. :)
