### ISSUE TITLE
Penpot fails to import heavy svg files

### ISSUE THREAD

**Issue by Skylsmoi** [penpot/penpot#613]
**Describe the bug**
When importing (using drag & drop or the "Image" tool) a svg file, it show an error page when the svg is a bit heavy.

I have tested:
- svg 1.5mo => fail
- svg 730ko => fail
- svg 360ko => ok
- svg 50ko => ok

**To Reproduce**
I can't add a failing svg file in a github issue (unsupported file). But what I did:
1. open inkscape
2. click everywhere using any tools at your disposal and regularly save your file (as svg) until your file reach around 750ko
3. import the file in penpot
4. it takes a bit of time to load and then display the error page

**Expected behavior**
The file is imported and visible in the artboard

**Screenshots**
x

**Desktop:**

-   OS: Ubuntu
-   Browser Firefox 
-   Version 85.0.1

**Smartphone (please complete the following information):**
- not tested

**Environment (please complete the following information):**
demo instance (https://design.penpot.app)

**Additional context**
x

**Comment by niwinz** [comment]
After digging on it, right now this is not designed to load very heavy svg images; it just for load icons and small illustrations. Right now, uploading big svgs will not work.

What is real use case you need for upload very big svgs?

**Comment by Skylsmoi** [comment]
Our use case is to migrate our current projects from Figma to Penpot.
I have seen on hackernews that you plan on making it possible but the feature is NYI.
So we tried to do so by exporting our project in svg from Figma and importing it in Penpot but I understand it might not be designed for.

Great work on Penpot by the way !

**Comment by niwinz** [comment]
@Skylsmoi Thanks!

Indeed, the import from figma, sketch, import/export from penpot is in our roadmap :D https://tree.taiga.io/project/penpot/us/551
And yes, the current method is not designed to import big projects.

**Comment by mathben** [comment]
I don't find the issue in taiga, is it normal?

**Comment by heyakyra** [comment]
> Our use case is to migrate our current projects from Figma to Penpot.

Same here

> Indeed, the import from figma, sketch, import/export from penpot is in our roadmap :D https://tree.taiga.io/project/penpot/us/551

Link is dead. Is this what that pointed to before? https://tree.taiga.io/project/penpot/us/1469 (if so, why did it break?)

**Comment by elhombretecla** [comment]
Yep @heyakyra this is the correct link :)

[https://tree.taiga.io/project/penpot/us/1469](https://tree.taiga.io/project/penpot/us/1469)

Thanks!

**Comment by heyakyra** [comment]
Thanks, any idea why the ID changed? Did everything get reset by some update?
