### ISSUE TITLE
Error when accessing a shared file if we are connected to PenPot

### ISSUE THREAD

**Issue by Natouille** [penpot/penpot#615]
**IF** I am connected to PenPot and **IF** someone shares a PenPot link with me, I cannot access the file, I have an error.
Many of us (on french Penpot channel on Matrix) encountered the problem. 
Tests done with Firefox and Chrome. Error occured on both browsers.

![image](https://user-images.githubusercontent.com/2006947/107386720-6ab8ea00-6af4-11eb-821b-ef76e5c59739.png)

**Comment by niwinz** [comment]
Thanks @Natouille for report

I have just fixed it today. It will be available in the next release.
