### ISSUE TITLE
Paste in place 

### ISSUE THREAD

**Issue by MyNameIsTroll** [penpot/penpot#617]
**Is your feature request related to a problem? Please describe.**
It is sometimes very convenient to be able to copy an item on one page and be able to copy it in the same place on another page.
At the moment we have to use the "position" menu to put the item back in the same place. It would be great to be able to do this directly with a "paste in place" (x,y) function.

**Describe the solution you'd like**
For example add to the menu (right click) the function "paste in place". 

**Additional context**
![SharedScreenshot2](https://user-images.githubusercontent.com/31790025/107480451-eb232d80-6b7c-11eb-8da6-8f719df35641.jpg)

**Comment by Dehelssey** [comment]
i absolutely always use paste at the same position when designing so i definitely have to +1 this request !

**Comment by elhombretecla** [comment]
Hi!!! Thank you for your feedback :)

"Paste in place" is activated by default when you are copy/paste items between artboards. It replicates same element coordinates (x, y) Just copy an element from an artboard, select another artboard and paste it :)

**Comment by elhombretecla** [comment]
Copy (ctrl + C) and paste (ctrl + V)

![paste-items](https://user-images.githubusercontent.com/1045247/107484976-71427280-6b83-11eb-9297-9a32d0bab587.gif)

**Comment by MyNameIsTroll** [comment]
@elhombretecla 
ohh great :)
Sorry I didn't try this way (by first selecting the workspace before pasting).
Wonderful, thanks for the information.

**Comment by Dehelssey** [comment]
**Quick tip :** when _double clicking_ on an artboard you select it and then can copy/paste at the same position
i think it's easyer than targeting the name of the artboard 😉

i still think a Ctrl+Shift+V would be a nice addition tho 😀

**Comment by elhombretecla** [comment]
Great!!

We will consider your enhancement proposal ([Taiga enhancement](https://tree.taiga.io/project/penpot/issue/1169))

Thank you very much!!!

**Comment by MyNameIsTroll** [comment]
Thank you, I close the issue.
