### ISSUE TITLE
No form validation messages on sign up

### ISSUE THREAD

**Issue by studiospring** [penpot/penpot#62]
I do not see any error messages when:

- username is missing
- Email is invalid/missing

Nothing happens when I click the register button.

**Comment by niwinz** [comment]
As far as I can observe right now, the form is validated properly. The register button remains disabled if the form is not valid, and only becomes enabled when the data is properly introduced.

We can revisit the UX of that, but the validation is working as expected.

**Comment by studiospring** [comment]
The button is disabled, but I do not know which input is invalid. Do I need more than one name in full name, is username taken, is my email invalid, is my password too short?
![register](https://cloud.githubusercontent.com/assets/4901306/23530380/83b57dac-fff5-11e6-9865-fedfa73af80b.gif)

**Comment by studiospring** [comment]
An easy way to add some validation is to use native browser validation (not the prettiest though!).

`<input type="email" id="email" name="email" required>`
