### ISSUE TITLE
Internal Error when locking path (shape) size

### ISSUE THREAD

**Issue by Quin452** [penpot/penpot#621]
**Describe the bug**
(Painstakingly) made a shape (it's a chat bubble) and resizing is fine.  But when I go to lock constraints for this shape, the page loads with "Internal Error", every time.

**To Reproduce**
1.  Create a shape with the Pen tool
2.  "Save" it.
3.  Click on the lock for the width & height
4.  See error

**Expected behavior**
For it to act like the other shapes

**Screenshots**

**Desktop (please complete the following information):**

-   OS: Win10
-   Browser: Firefox 85.0.2

**Environment (please complete the following information):**
Current alpha site

**Additional context**
I also couldn't find a way to edit a Path shape after creation.

**Comment by Alotor** [comment]
Thanks for the report. We'll fix it for the next release.
