### ISSUE TITLE
Cannot unmask (error server side)

### ISSUE THREAD

**Issue by Quin452** [penpot/penpot#623]
**Describe the bug**
Trying to unmask, and it returns an error when auto-saving (on back end).

**To Reproduce**
1.  Mask somethings
2.  Right click layer -> unmask
3.  Doesn't save
4.  Need to reload

**Expected behavior**
It unmasks

**Desktop (please complete the following information):**

-   OS: Win10
-   Browser: Firefox 85.02

**Additional context**

**Comment by Alotor** [comment]
Hi @Quin452 sorry to hear you're having problems.

Could you please copy the mask (in Penpot select the mask in the workspace, and do Ctrl+C) then create a text file and paste what you've copied.

It should have a representation of the problematic shape. If you could upload it here would be a great help for us.

Cheers,

**Comment by Quin452** [comment]
Sorry, the mask has been deleted.  It was causing so many issues, and on one of the auto-save/recovery it just vanished (issues with "assertions", I think it said).

I'm not sure if it was because of a mask within a mask, or just the singular mask, but I'll try to replicate the issue later.

Update: I just tried recreating the issue, and single masks, and child masks don't cause an issue.

Originally I had a path shape, a duplicate of that mirrored, and a rectangle in a group, which was then masked.
I lost all that.
Perhaps things just got confused with the multiple shapes, groups and masks.

**Comment by Alotor** [comment]
OK, no worries. I'll try to reproduce the problem with the information you've provided. Thanks!
