### ISSUE TITLE
Modifier + middle mouse button for zooming

### ISSUE THREAD

**Issue by pulakctl** [penpot/penpot#625]
**Is your feature request related to a problem? Please describe.**
My current setup uses a keyboard with a graphics tablet (the screen-less kind). Zooming in the viewport is difficult as I do not use a mouse.

**Describe the solution you'd like**
Similar to Blender and Krita, I want to use `Ctrl` + `MMB` for zooming (or any other modifier key).

**Describe alternatives you've considered**
The numpad `+`/`-` keys are less ideal (requires moving my hand to the other end of the keyboard).
The `+`/`-` keys next to the number row could work, but the zoom in key appears to be specifically `+` instead of allowing `=` as a substitute (like most browsers).

**Additional context**
Browser: Microsoft Edge, Version 90.0.789.1 (Official build) dev (64-bit)

**Comment by jdittrich** [comment]
> I want to use Ctrl + MMB for zooming

To clarify: Ctrl+Middle mouse button for zooming means that, when Ctrl+MMB are pressed, an upward movement is interpreted as zooming in, a downward movement is moving out. A movement on the horizontal axis does nothing. 

**Usefulness:** I imagine this to be really helpful for graphic tablet users; for others it probably is of limited usefulness, as most mice have a wheel and and most laptops do not have a dedicated middle mouse button but will support a zoom gesture.

**Comment by pulakctl** [comment]
> an upward movement is interpreted as zooming in, a downward movement is moving out.

Yes, that is the expected behavior. I am not sure if it is linearly proportional or logarithmic in Blender/Krita.

> I imagine this to be really helpful for graphic tablet users; for others it probably is of limited usefulness, as most mice have a wheel...

Correct, it is really helpful for input setups without a dedicated scroll wheel/touch gesture. From what I know, this also includes some basic trackballs having neither a scroll wheel nor a 3rd button (the 3rd button is emulated by pressing both buttons together).

**Comment by hirunatan** [comment]
Thanks for your suggestion. It seems useful indeed. We have created a user story in Taiga for this:

https://tree.taiga.io/project/penpot/us/1428

**Comment by hirunatan** [comment]
This has been done. You'll see it in the next release.
