### ISSUE TITLE
Remove full name from sign up.

### ISSUE THREAD

**Issue by studiospring** [penpot/penpot#63]
The need for full name at sign up is unclear. If there is no reason for it, can we remove it, to make sign up simpler? This will require removal from profile page as well.

**Comment by niwinz** [comment]
Hmm, I'm not pretty convinced unpersonalizing the application. The full name is shown in the top-right corner and is pretty intuitive. On the future we have plans to implement a feedback mechanism on the view mode and not having the name of the person will make that much les intuitive...

**Comment by studiospring** [comment]
The username serves as a unique identifier, so I do not see what extra benefit a full name gives. There is no guarantee that a person will supply their real name and it only makes a point of confusion with the username. If there is a good reason for supplying a full name, then the reason should be made clear on the registration page, especially since this is not standard practice for registering on most web apps.

**Comment by niwinz** [comment]
I'm not agree with you, the fullname is disponible in almost all services that I'm using, I don't remember a unque service that only has username / email.

Later, I know people that has just the contrary opinion that you.

In summary, we need to think more about this, I have a lot of doubts for depersonalizing the application.

**Comment by studiospring** [comment]
Ok. Look forward to the discussion...
![github](https://cloud.githubusercontent.com/assets/4901306/23531052/63efba04-ff9c-11e6-9349-88c2f3ab2436.jpg)
![lucidchart](https://cloud.githubusercontent.com/assets/4901306/23531068/7884e85e-ff9c-11e6-960d-341ddc2a1a2b.jpg)

**Comment by niwinz** [comment]
It is quite surprising but your second example requires a **Name**, that is not username is just a name or analogous to the uxbox **Full Name**.

We don't have any problem to change Full name, to something more soft like the last example "Your Name" I think.

**Comment by niwinz** [comment]
And github does not requires it on register but it encourages to fill it on the profile page. Eliminating the "full name" or "name" from uxbox register page can be an option, but definitively it is not going to be a simple decision.

**Comment by studiospring** [comment]
Right! There are many ways to do it. Some sites require full name, but do not require username. Full name could be optional later in profile. "Your name" encourages a full name, but may accept single names. I want to reduce friction from registration to get as many users as possible. See [Conversion funnel](http://www.vision6.com.au/blog/a-simple-approach-to-web-forms-that-wont-scare-customers-away/).

I do not think removing full name depersonalises the app in any way. A prototyping app does not have to have a real name like facebook.

**Comment by niwinz** [comment]
@elhombretecla I need your feedback here.

**Comment by elhombretecla** [comment]
We are going to remove the "Full name" input from the sign in form. The user could fill it at the profile options. It will be necessary for future features :)

**Comment by niwinz** [comment]
I'll maintain this issue open until is fixed ;)
