### ISSUE TITLE
Create a "material design" dashboard as default

### ISSUE THREAD

**Issue by overflorian** [penpot/penpot#630]
Hi,
While creating a first project, the current "Penpot onboarding" screens allow to copy-past custom elements of the whole interface. That's extra useful!

As a lot of projects are following the [materal design](https://material.io) guidelines, a nice feature would be to display a sample project with these elements too. That would definitely speed up the process of creating a first screen.

Thanks in advance and congrats for this great tool that I just discovered and will use for my open source projects.

**Comment by niwinz** [comment]
Hi @overflorian 
First of all, welcome, and thanks for the suggestion. 

Is in our plans for a  future is improve the reusability of shared libraries that I think will solve this use case.

**Comment by hirunatan** [comment]
Close this, as it's related to #620
