### ISSUE TITLE
Development: Include an architecture.md

### ISSUE THREAD

**Issue by jdittrich** [penpot/penpot#634]
**Story:** 
* As an volunteer interested in fixing a bug I want to understand how the penpot code is structured, so I can understand where to look for the cause of the bug.
* As a newly onboarded team member I want to understand how the penpot code is structured, so I can be productive quickly

**Describe the solution you'd like**
* Consider using an `architecture.md`-file as [described here](https://matklad.github.io//2021/02/06/ARCHITECTURE.md.html): "this file should describe the high-level architecture of the project." A positive example pointed out by the article is [rust-analyzers architecture file](https://github.com/rust-analyzer/rust-analyzer/blob/d7c99931d05e3723d878bea5dc26766791fa4e69/docs/dev/architecture.md)

**Describe alternatives you've considered**
* Community contributions can be hard to manage (People want to see it merged, code quality might be sub-par, question of maintenance…) so you might not focus on this right now and rather, e.g. on the long term creation of a extension API for people who want to hack on penpot. 
* One can also take the more elaborate route and produce some diagrams

**Comment by niwinz** [comment]
Hi @jdittrich 
Thanks for you suggestions.

Right now we already have an ongoing task for the documentation. And architecture overview is a part of it (I'm not sure if we going to go with `ARCHITECTURE.md` file because we want to have our all doc in a publicy available site).

**Comment by hirunatan** [comment]
Hi!

We've just launched the first version of the documentation site! We'll add much more sections later, but there is already an Architecture section:

https://help.penpot.app/developer-guide/architecture/

Hope it's useful for starting to understand how Penpot is made. Stay tuned for more info.
