### ISSUE TITLE
Can't change fill colour when multiple objects are selected

### ISSUE THREAD

**Issue by OleksiySitka** [penpot/penpot#638]
It is impossible to change fill colour when several objects with different current fill colour are selected using click+drag

Steps to reproduce the behaviour:
1.  Create 2 rectangles
2.  Have them filled with 2 different colours
3.  Select both of them by clicking the mouse outside the shapes and dragging the mouse over them (can't figure out the pattern here, but if objects are selected using shift+click this bug is not always reproducing)
4.  Look at "selection fill" panel on the right and see "?" instead of colour and "Mixed" instead of hex value
5.  Open colour palette by clicking "?" and select a new colour from the canvas using colour picker
6.  See that objects didn't change the colour

Expected behaviour:
Both rectangles should change the colour to selected one

Setup:
-   OS: macOS Mojave 10.14.6
-   Browser: Firefox 85.0.2 (64-bit)
-   Penpot version: I guess it's Alpha 1.0? The one that is currently live on design.penpot.app

**Comment by Alotor** [comment]
Hi! Thanks for the report.

There is a known bug when changing properties for shapes inside groups. Maybe that is your problem? If so, we're uploading a new version today that will fix that.

With the steps you've indicated I couldn't reproduce the bug.

**Comment by OleksiySitka** [comment]
Yep, seems like it was that known bug. Can't reproduce it now.
Thanks!
