### ISSUE TITLE
Cannot create shapes in all directions when using proportion lock.

### ISSUE THREAD

**Issue by studiospring** [penpot/penpot#64]
When I hold down Ctl, the shape is not created in the same direction as the mouse movement. See gif. This happens with circles and text boxes as well.
![ctl-drag](https://cloud.githubusercontent.com/assets/4901306/23486853/900d17a0-ff36-11e6-93f2-af95d22e2c7b.gif)

**Comment by niwinz** [comment]
Yeah, is a known bug/limitation. For now it is low priority.
