### ISSUE TITLE
Corner radius bug with drop shadow + spread

### ISSUE THREAD

**Issue by Manueljlin** [penpot/penpot#644]
**Describe the bug**
Adding a drop shadow with spread enabled:
- Doesn't add more px radius by px spreaded on squares.
- Doesn't behave correctly on circles.

**To Reproduce**
Steps to reproduce the behavior with **squares**:
1.  Add a square (for example: 100x100) and add a ~35px radius
2.  Add a shadow with the following configuration, to see the bug more clearly
            0 X    0 Y    0 Blur    20 Spread    100% Opacity
3.  Current result:
![image](https://user-images.githubusercontent.com/11275573/107936820-64f35680-6f83-11eb-9cea-c01c15466820.png)
Expected result: (radius of the original object (35) + amount of pixels spreaded out (20))
![image](https://user-images.githubusercontent.com/11275573/107937020-a97ef200-6f83-11eb-9f0c-6ca0a075965a.png)

Steps to reproduce the behavior with **circles**:
1.  Add a circle with the same valus as before
2.  Add a shadow with the values from before
3.  Current result:
![image](https://user-images.githubusercontent.com/11275573/107939404-f31d0c00-6f86-11eb-96ce-7752ff6fcc9e.png)
Expected result:
![image](https://user-images.githubusercontent.com/11275573/107939448-0334eb80-6f87-11eb-93b6-03cc180d3ad3.png)

edit: removed the circle "radius info" from copypasting. oops

**Environment (please complete the following information):**
Demo instance

**Comment by Alotor** [comment]
Thanks for the report, this is a tricky one.
I've been testing and the problem is the SVG filter we're using. Looks like it's causing this effect.

The following code has the same problem:

```svg
<svg width="200" height="200" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
  <g filter="url(#filter)">
    <circle cx="10" cy="10" r="5" fill="red"/>
  </g>
  <defs>
    <filter id="filter" filterUnits="userSpaceOnUse" color-interpolation-filters="sRGB">
      <feMorphology radius="1" operator="dilate" in="SourceAlpha" result="shadow"/>
      <feBlend mode="normal" in="SourceGraphic" in2="shadow" result="shape"/>
    </filter>
  </defs>
</svg>
```
![image](https://user-images.githubusercontent.com/3418223/107947649-f5856300-6f92-11eb-81b7-1264ed9f9917.png)

Looks like SVG dilation is causing the problem.

**Comment by niwinz** [comment]
For now we don't have a good solution for this. Maybe we revisit this in a future.
In any case, thanks for reporting this.
