### ISSUE TITLE
Snapping to grid stops working on duplicated pages

### ISSUE THREAD

**Issue by SaucySauce** [penpot/penpot#646]
BUG: Basically, when using a duplicated page, the grid snapping or recognition of other asset boundaries does not work.

Temporary FIX: Reloading the web page or going to the library and back to the file will get the features working again but it's only temporary as duplicating a page again will have the same bugs and will persist until this workaround is done once more.

Setup:
1920x1080 23' monitor
R3 1200, RX 580 4GB, 8GB RAM

Arch Linux, up to date except Firefox 85 (crash bug)
GNOME Shell 3.38.3 with Wayland session enabled
Firefox 84.0.2 with Wayland mode enabled

**Comment by Alotor** [comment]
Thanks for the report. We'll fix it for the next release.
