### ISSUE TITLE
Unable to accept invitation to join team

### ISSUE THREAD

**Issue by veeableful** [penpot/penpot#647]
**Describe the bug**
I'm unable to join team via invitation link. When I click Accept Invite button in the email, I get redirected to login page even though I have logged in previously. After logging in again, I don't see the team I was invited to listed in the team list.

**To Reproduce**
1.  Click on Accept Invite button in the invitation email
2.  Click on Login with Google
3.  Click on the team list on top-left but it doesn't show the team I was invited to

**Expected behavior**
The team I was invited to shows in the team list on the top-left corner of the dashboard. I also expected not to be redirected to the login page upon accepting the invitation if I'm already logged in.

**Desktop (please complete the following information):**

-   OS: macOS Big Sur
-   Browser: Brave
-   Version: 1.0.0 Alpha

**Additional context**
We used Login with Google for our accounts.

**Comment by niwinz** [comment]
Hello @veeableful 
Thanks to report it, something similar happenned to our internal team today.

**Comment by niwinz** [comment]
The real problem is that login/register with google right now does not handles well the invitation token. A workaround is: once registered/logged-in with google, go to accept link again and accept the invitation (the invitatin link has 24 hours of expiration); if you don't have it, just request an other invitation and it should work as expected.

Meanwhile we fix it ASAP.

**Comment by veeableful** [comment]
Thanks @niwinz. I tried the workaround you suggested and the accept invitation link still seems to redirect me to the login page even though I have already signed in and can see the dashboard. The link itself has only been a few hours old.

**Comment by niwinz** [comment]
The invitation code is completeley refactored and now should work as expected.
