### ISSUE TITLE
Resend activation e-mail not possible?

### ISSUE THREAD

**Issue by jeffrey-ose** [penpot/penpot#648]
**Describe the bug**
When a user registers himself and the SMTP settings are not yet configured, there is no way to resend the activation mail and therefore the user account is blocked.

**To Reproduce**
1.  Set up Penpot without SMTP settings
2.  Register a user
3.  Enable SMTP settings and restart Docker
4.  Try to log in with the new user, message appears: Profile is not verified, please verify profile before continue.

**Expected behavior**
An option to resend the activation mail would be great. It could be a button in the toaster that says "Click here to resend verification mail."

**Desktop (please complete the following information):**

-   OS: Windows
-   Browser Firefox 
-   Version: 85.0.2 (64-bit)

If self-hosted instance, add OS and runtime information to help explain your problem.

-   OS Version: Ubuntu 20.04LTS

**Additional context:**
The Docker-compose file states that if SMTP is disabled, emails are printed to the console. I'm not aware how I can access those if I run in daemon mode:  `docker-compose -f docker-compose.penpot up -d`.

_Edit:_
To add to this:
I see this as a bug, because when you don't have the verification mail, the e-mail address you used is blocked because you cannot use the same e-mail address twice (which is obvious).

**Comment by jeffrey-ose** [comment]
I found a workaround for anyone that's interested. You can edit the database and manually activate the created account:

Log in to the postgres docker container :
`docker exec -ti taiga-docker_penpot-postgres_1 /bin/bash`

Login to the database (default username and password are `penpot` ):
`psql -U penpot penpot`

Use the penpot database:
`\c`

Query to activate the specified user:
`UPDATE profile SET is_active='t' WHERE email = 'EMAIL';`

Exit out from the database and the container with `ctrl + d`

Now you are able to login to Penpot!

**Comment by niwinz** [comment]
Hi @jeffrey-ose 

Welcome!

> The Docker-compose file states that if SMTP is disabled, emails are printed to the console. I'm not aware how I can access those if I run in daemon mode: docker-compose -f docker-compose.penpot up -d.

You can access to docker logs using `docker-compose -f docker-compose.penpot.yml logs` if I'm not wrong.

> An option to resend the activation mail would be great. It could be a button in the toaster that says "Click here to resend verification mail."

This is a bit tricky; I try to explain it: when you using a good reputation email sentinding service, exposing a "send me again" link will open a hole to malicious use (send and send again probably bounced or spam reported email) that will repercute in the email sending reputation and (on the extreme case) cause suspend of email sending completelly. Obviously it is more important to SAAS instance and not so important on on-premise personal usage but it still important.

We need to thing a good aproach in balance with the usability and the "security" (avoid malicious usage)

**Comment by jeffrey-ose** [comment]
I understand. Maybe it is an option to create a superuser (like with Taiga6). That superuser can be created the same way as with Taiga and therefore, is activated by default. If that user gains access to an admin page where all registered users are listed, he/she can then manually call a service to resend the activation email.

**Comment by jeffrey-ose** [comment]
> 
> You can access to docker logs using `docker-compose -f docker-compose.penpot.yml logs` if I'm not wrong.
> 
This is correct. I can see the logs now. Maybe it's a good idea to include this in the comment of the docker-compose file?

**Comment by niwinz** [comment]
>> You can access to docker logs using docker-compose -f docker-compose.penpot.yml logs if I'm not wrong.

>This is correct. I can see the logs now. Maybe it's a good idea to include this in the comment of the docker-compose file?

Hmm maybe is a good idea, the documentation right now makes the assumption that the user already knowns how docker works but I think is a bad assumption. Thanks, we will improve it.

**Comment by niwinz** [comment]
> I understand. Maybe it is an option to create a superuser (like with Taiga6). That superuser can be created the same way as with Taiga and therefore, is activated by default. If that user gains access to an admin page where all registered users are listed, he/she can then manually call a service to resend the activation email.

The problem here is that, we don't have the "admin" concept on penpot; there are no users that can see everything. But probably creating a default user already activated can be a good idea in any case.

**Comment by jeffrey-ose** [comment]
> 
> 
> > > You can access to docker logs using docker-compose -f docker-compose.penpot.yml logs if I'm not wrong.
> 
> > This is correct. I can see the logs now. Maybe it's a good idea to include this in the comment of the docker-compose file?
> 
> Hmm maybe is a good idea, the documentation right now makes the assumption that the user already knowns how docker works but I think is a bad assumption. Thanks, we will improve it.

I understand. My knowledge of Docker is still quite basic (learning as I go). Maybe I'm in the minority, but I think that it wouldn't hurt anyone to include that line as a comment.

Thank you for your quick responses btw. It's appreciated.

**Comment by niwinz** [comment]
[Taiga US](https://tree.taiga.io/project/penpot/us/1293?milestone=284230)

**Comment by niwinz** [comment]
Many facilities are already landed in the last release but the documentation is missing for now (will be updated soon);

Righ now when you start an instance in locally (using docker, if email is not configured, you will be able to change email without confirmation. And addtional manage.sh script is added for create already activated users:

Example of usage:
```sh
docker exec -ti penpot_penpot-backend_1 ./manage.sh create-profile
```

**Comment by pierreelliott** [comment]
I have this exact problem on the SaaS (design.penpot.app).
I forgot to validate my email right away and can't do anything now: token isn't valid anymore, email is already registered and account isn't verified so impossible to change password (just to see if I could find a solution).

Is there anything I can do or do I need to recreate an account ?

**Comment by niwinz** [comment]
> I have this exact problem on the SaaS (design.penpot.app).
> I forgot to validate my email right away and can't do anything now: token isn't valid anymore, email is already registered and account isn't verified so impossible to change password (just to see if I could find a solution).
> 
> Is there anything I can do or do I need to recreate an account ?

Send us an email to `info@penpot.app` from the registered email and we will activate your account.
