### ISSUE TITLE
undo doesn't work correctly when the colour plate is open

### ISSUE THREAD

**Issue by OleksiySitka** [penpot/penpot#649]
When the colour panel is open and a new fill colour of the object is set, pressing cmd+z does not revert the last action (change of colour) but reverts the one that was done before

Steps to reproduce the behaviour:

- Create a (grey) rectangle
- Move it to the different location
- Change the fill colour of it (e.g. to blue)
- Press cmd+z while colour selection panel is open
- see that rectangle moved back to the previous location, but didn't change the colour (still blue)

Expected behaviour:
The rectangle should change back to original colour and not move to original place

Setup:

    OS: macOS Mojave 10.14.6
    Browser: Firefox 85.0.2 (64-bit)
    Penpot version: whatever is currently live on design.penpot.app

**Comment by hirunatan** [comment]
Thanks for the reporting!

I understand this can cause some confusion, but this was a deliberate decision. When choosing a color it's usual for an user to try many options until they find the correct color. We create the undo entry only when the color picker is closed, to avoid generating a lot of entries, one for each color change while the picker was open.

**Comment by OleksiySitka** [comment]
I see... This is quite confusing to me, as it results in inability to revert exactly to the previous state. In my example it'd be a grey rectangle in the place I created it, Instead I got a blue rectangle in the place I created it, but it was never blue in this place before. I understand that it'd be an overkill to add each change of the colour to the undo list while the picker is open, but maybe it'd be possible to create an undo entry right away and then just update it on colour change? 
Anyway, it's just an idea.
Thanks for making a great product!

**Comment by hirunatan** [comment]
Let's see... the possibility of update an existing undo entry has not been contemplated, at least for now, and this may have some complex side effects.

Anyway, in your example you just need to close the color plate, thus generating the undo entry. And then, you press cmd-z and will revert the color change, leaving the object in position.

**Comment by hirunatan** [comment]
I think I can close this. If we think in the future a smart way of enhancing it, will be good. But for now I can't think of a reasonable solution.
