### ISSUE TITLE
Modify primary shapes (delete points with the pen tool)

### ISSUE THREAD

**Issue by MyNameIsTroll** [penpot/penpot#658]
**Is your feature request related to a problem? Please describe.**
At the moment it is not possible to modify primary shapes such as squares or circles. However it is sometimes very useful to use primary shapes as a basis to build more complex shapes. For example, one could remove a point from a square and then use the pen tool to close the points and create a triangle. 
One can also imagine connecting a piece of square to a piece of circle or a free shape. 

**Describe the solution you'd like**
For example, I would like to be able to double-click on a primary shape and have access to the pen tool options to modify a point, move it or delete it. Currently it is not possible to delete points with the pen tool when selecting a point. 

![image](https://user-images.githubusercontent.com/31790025/108600177-f3a61000-7395-11eb-8ad7-dc0e986edce5.png)

**Comment by claragvinola** [comment]
Hi! These features are described in these US that we have in our backlog: https://tree.taiga.io/project/penpot/us/907?no-milestone=1 We add your comments to the US :)
Thank you for your feedback!
