### ISSUE TITLE
Blurry rendering on editor

### ISSUE THREAD

**Issue by Manueljlin** [penpot/penpot#659]
**Describe the bug**
Blurry rendering on the web editor, affects one pixel lines the most.

**To Reproduce**
1.  Create pixel aligned objects, shadows, etc
2.  Zoom back to 100%
3.  See blurry rendering

**Expected behavior**
Non-blurred editor preview
![image](https://user-images.githubusercontent.com/11275573/108199411-45903100-711d-11eb-9014-a545dffb8069.png)
You might need to click on the image to see it properly

**Screenshots**
![image](https://user-images.githubusercontent.com/11275573/108199533-78d2c000-711d-11eb-940a-847a85d0fb1a.png)
You might need to click on this image too to see it properly

**Environment (please complete the following information):**
Using demo instance.

**Additional context**
Using 100% scaling at the OS level, both on openSUSE Tumbleweed and Windows 10 20H2. Happens on Firefox and Vivaldi.
Exports look completely normal.

**Comment by Manueljlin** [comment]
Here's the SVG file for easier testing
[github_doesn't_let_me_upload_svgs.zip](https://github.com/penpot/penpot/files/5995407/github_doesn.t_let_me_upload_svgs.zip)
Thanks a lot for this wonderful app :D

**Comment by myfunnyandy** [comment]
We are currently working on a lot of SVG improvements that might affect SVGs at Penpot in many ways. Until we have them we will postpone browser rendering issues, so I will close this issue.

Thanks, as always ;)
