### ISSUE TITLE
In sign up and login page, the first form input should have tabindex=1.

### ISSUE THREAD

**Issue by studiospring** [penpot/penpot#66]
At present, sections that are unrelated to inputs have initial focus.
Also, the other links "Forgot your password?", "Don't have an account?" should also get tab focus.

**Comment by niwinz** [comment]
I have added tab-index to relevant inputs on register and login pages.

**Comment by studiospring** [comment]
Thanks, @niwinz. But why is the first form input tabindex=2? 
Why does this section need a tabindex of 1?

`<section id="app" tabindex="1">`

**Comment by niwinz** [comment]
It was so from the start of the project. I'm not very aware of how tabindex works so we need to talk with @elhombretecla about that!
