### ISSUE TITLE
Bug with special caracters

### ISSUE THREAD

**Issue by overflorian** [penpot/penpot#669]
Hi, 
when I use the caracters "ê" or "ë" which are common in French, Penpot instantanely crashes and display this screen:
![image](https://user-images.githubusercontent.com/11553211/108484410-1522d100-729c-11eb-9d1a-fc92f3faecdc.png)

help!

**Comment by niwinz** [comment]
Hi @overflorian 
This is already reported here: https://github.com/penpot/penpot/issues/656

**Comment by overflorian** [comment]
Sorry about that and have a good day

**Comment by niwinz** [comment]
No problem! ;) Thanks! You too.
