### ISSUE TITLE
In sign up and login page, tab does not highlight "Continue" or "Register" button.

### ISSUE THREAD

**Issue by studiospring** [penpot/penpot#67]
Even though the button is focused, there is no visual indication. Changing colour and bolding text/border change is required. Links, should also change visually on focus.

**Comment by niwinz** [comment]
I'm not clearly understand this. The button register/sign in button is highlighted only when you enter a valid data, until that, the buttons remains disabled.

**Comment by studiospring** [comment]
I am using tab to navigate, but I do not know when the button has focus. I only know that it is enabled. If I tab again, the links should show focus too. This is partly a browser issue because Firefox shows button focus by default with the dotted lines (but not link focus), but Chromium does not.

The sign in and register buttons actually change colour when I hover with the mouse (not shown in gif), but not with tab.

Chromium
![login2](https://cloud.githubusercontent.com/assets/4901306/23529765/eb4f2f9c-fff2-11e6-99cb-94dd8121543c.gif)
Firefox
![login](https://cloud.githubusercontent.com/assets/4901306/23529964/cab09e5a-fff3-11e6-8bd7-6cc1985524a7.gif)

**Comment by niwinz** [comment]
Thanks for the explanation.
