### ISSUE TITLE
Zoom In doesn't work on Ubuntu

### ISSUE THREAD

**Issue by MarkAurel** [penpot/penpot#670]
**Describe the bug**
Zoom In doesn't work on Ubuntu 18.04.5 LTS

**To Reproduce**
1.  Open an document
2.  Click on keyboard key 'more' (+)
3.  See error

**Expected behavior**
I expected to Zoom In.

**Desktop (please complete the following information):**

-   Ubuntu 18.04.5 LTS
-   Browser Google Chrome
-   Version 88.0.4324.150

**Environment (please complete the following information):**
Specify if using demo instance or self-hosted instance.

In Production

**Additional context**

**Comment by niwinz** [comment]
Hi @MarkAurel , thanks for reporting it.

Unfortunatelly, I can't reproduce, I have tried on Chrome and Firefox and works as expected.

**Comment by keunes** [comment]
Can't replicate either:
- Ubuntu 18.04.5
- Google Chrome 88.0.4324.182

I do need to hold 'shift' in order to press the + sign, but that's to be expected on a US Int'l dead key layout.

**Comment by hirunatan** [comment]
@keunes can we consider this issue closed, if you can't reproduce it either?

**Comment by keunes** [comment]
@hirunatan I would think so, yes. Unless @MarkAurel has any particularities that might impact their issue, which they can share.
