### ISSUE TITLE
When moving elements the screen stuck and element goes out of artboard

### ISSUE THREAD

**Issue by APattjoshi** [penpot/penpot#671]
**Describe the bug**
When moving elements in the artboard, element goes out of the artboard

**To Reproduce**
1.  Create an artboard
2.  Inside the artboard create a masked image
3.  Move the image with the help of the arrow key
4.  The Image layer gets out of the artboard

**Expected behavior**
The Image should remain inside the artboard when you move it with the help of the keyboard

**Screenshots**
No Screenshots

**Desktop (please complete the following information):**

-   OS: (Windows 10)
-   Browser (chrome)
-   Version (88.0.4324.182 (Official Build) (64-bit)

**Comment by niwinz** [comment]
Yeah, look like a bug! Thanks! ([internal issue](https://tree.taiga.io/project/penpot/issue/1258))

**Comment by Alotor** [comment]
@APattjoshi There was a bug with using keys to move shapes. Should be fixed already in the latest release.
Thanks for the report
