### ISSUE TITLE
Pressing the Alt key to see the distance element gets deselected

### ISSUE THREAD

**Issue by APattjoshi** [penpot/penpot#672]
**Describe the bug**
Pressing the Alt key to see the distance element gets deselected

**To Reproduce**
1.  Create an artboard
2.  create two rectangles inside the artboard
3.  Press alt to see the distance
4.  move the element (rectangle)
5. The chrome browser menu opens

**Expected behavior**
All the short key functionalities should remain within the program

**Screenshots**
Unavailable

**Desktop (please complete the following information):**

-   OS: (Windows 10)
-   Browser (\chrome)
-   Version (88.0.4324.182 (Official Build) (64-bit)

**Comment by niwinz** [comment]
Hi @APattjoshi
Thanks for reporting this.

Right now many browsers don't allow override operating system shortcuts and I think that this is the case. We will research further on this but I think there are no good solution for this problem.

**Comment by APattjoshi** [comment]
I am not having any issue with Quant-UX or Figma for that matter, when I am using it through the same browser, thank you for your reply though.

**Comment by niwinz** [comment]
I have reported it internally to further investigation. [Taiga issue](https://tree.taiga.io/project/penpot/issue/1260)

**Comment by keunes** [comment]
> Right now many browsers don't allow override operating system shortcuts and I think that this is the case. We will research further on this but I think there are no good solution for this problem.

I think this is a problem also with alt showing a menu if it is not displayed by default. Hitting alt will thus, in addition to displaying elements' distance, change the available screen height and position of the artboard - which is really annoying.
Maybe an alternative key should be found.

**Comment by Alotor** [comment]
@APattjoshi the issue with "alt" will be fixed in next version, I haven't been able to reproduce your issue exactly but I've changed the code and I hope it's fixed.

@keunes Next release will have the `.` key as an alternative to `alt` for showing distances between elements.

Cheers.
