### ISSUE TITLE
Unexpected error on exporting artboard.

### ISSUE THREAD

**Issue by APattjoshi** [penpot/penpot#673]
Please get a plugin for Figma or export to Figma; Currently, the platform is very unstable, and data may be lost or corrupted. Exporting as SVG and importing back to other tools, all the elements are simply not in place or enable to copy-paste SVG.

**Comment by niwinz** [comment]
Hi @APattjoshi
Can you explain what you mean with "Currently, the platform is very unstable, and data may be lost or corrupted" ? I mean, would be awesome have a more constructive feedback of what makes you feel **very unstable**. 

The current release is marked as **alpha** so there expected have some bugs and missing features, and we aware of many of them (and we expect to fix them as soon as possible); the application is just released to the public some weeks ago, and we are working hard on make it stable and incorporate many of the missing features.

You already can export as png or svg any shape, just select it and go to export section on element options.
![Screenshot from 2021-02-19 17-27-24](https://user-images.githubusercontent.com/843689/108532524-39040800-72d8-11eb-80a0-6646979b9d42.png)

**Comment by APattjoshi** [comment]
Apologies if it did not come across as I intended, I am unable to export SVG sometimes so if it's possible to copy-paste SVG code that will be great. I tried around 10 times and always it said unexpected error and a retry screen, I am unable to reproduce it again now.

**Comment by niwinz** [comment]
If this happens afain, please try to reporoduce it on a separated file, and send us the id of the file that we can investigate the real problem. Thank you very much.

**Comment by APattjoshi** [comment]
Describe the bug
Trying to export SVG

To Reproduce
Steps to reproduce the behavior:

Create an artboard
Select the Artboard
Press export
It says exporting for sometime
The shows a push notification saying unexpected error
It did not export
Selected another artboard
export shape
Exported

Issue
But the SVG was corrupted not opening properly in another program like Inkscape
Tried exporting another Artboard it did not work

Expected behavior
It should Export an SVG to the local machine

Screenshots
![Capture](https://user-images.githubusercontent.com/47391164/109098056-966bdf00-7746-11eb-9c17-7efab25af927.PNG)
![Capture1](https://user-images.githubusercontent.com/47391164/109098064-9a97fc80-7746-11eb-8cba-f0390edb219d.PNG)

Desktop (please complete the following information):

OS: (Windows 10)
Browser (chrome)
Version (88.0.4324.182 (Official Build) (64-bit)

**Comment by APattjoshi** [comment]
> If this happens afain, please try to reporoduce it on a separated file, and send us the id of the file that we can investigate the real problem. Thank you very much.

I reproduced but how to send the file id, where to find it.

**Comment by niwinz** [comment]
Hi @APattjoshi you can send me the workspace URL to info@penpot.app; I have created a task for research on this problem https://tree.taiga.io/project/penpot/task/1318;

**Comment by niwinz** [comment]
As in other opened issue you asked for an approach to copy the svg, on the viewer/handoff mode you have the svg visualized on the right sidebar and has the ability to copy it. The main difference with export, is that the texts are not converted to paths on the handoff output.

**Comment by APattjoshi** [comment]
> As in other opened issue you asked for an approach to copy the svg, on the viewer/handoff mode you have the svg visualized on the right sidebar and has the ability to copy it. The main difference with export, is that the texts are not converted to paths on the handoff output.

I am unable to find the above thing. I have shared the file with you to the mentioned email id. Please do the needful.

**Comment by niwinz** [comment]
We din't received any email. EDIT: now i have received it, thanks

The handoff mode is easy to acces. From workspace, go to view mode (top right corner, play button); once in viewer select the arboard; then go handoff mode (top center, 3rd button), and then you only need to select the artboard with the mouse pointer.

**Comment by APattjoshi** [comment]
Thank you I found it, sorry to say but it's not easy to find, there is a learnability issue with it, might be the buttons are not in focus so, it's easily missed.
