### ISSUE TITLE
share link redirects to the login page

### ISSUE THREAD

**Issue by mjourdan** [penpot/penpot#675]
**Describe the bug**
Share link is supposed to be public, yet it redirects to the login page.

**To Reproduce**
1.  Open project
2.  Enter view mode
3.  Click on share link
4.  Popover states "anyone with the link will have access"
5. Copy link

Open link in a separate browser session. From \<link\>, we are redirected to \<link\>#/auth/login

**Expected behavior**
Content is accessible without authentication.

**Desktop (please complete the following information):**

-   OS: Fedora
-   Firefox 85.0.1
-   GNOME Web 3.38.2

**Environment (please complete the following information):**

Using design.penpot.app

**Comment by niwinz** [comment]
Hello @mjourdan 
Thanks for reporting that.

I have tried to reproduce but it works as expected. This is a share link to a dummy page: https://design.penpot.app/#/view/c5267fa0-3310-11eb-8dbc-556a2f641513/c5267fa1-3310-11eb-8dbc-556a2f641513?token=KI7fRB9cym8fCXkrbsOV5A&index=0, can you confirm that you can access it? Thanks

**Comment by mjourdan** [comment]
Thanks for your reply @niwinz. I can access the link you gave without trouble. Here is [the one](https://design.penpot.app/?token=eO87zcguYOTulx29eYSn2A&index=0) for which I opened this issue. The actual url is missing from the share link it seems:

![image](https://user-images.githubusercontent.com/5346620/108597736-e899b280-738a-11eb-91fa-16e9ed8d54ee.png)

**Comment by niwinz** [comment]
I'm not clearly undestan how this can happen. But for ensure tha it works correctly a pushed a commit with a better impl for this link printing #677 . Will be online on the next release.

**Comment by niwinz** [comment]
We have deployed all the fixes to design.penpot.app. If this persists; reopen please.

**Comment by mjourdan** [comment]
I confirm I can't reproduce the issue anymore. Thank you @niwinz and the Penpot team!
