### ISSUE TITLE
Importing existing projects into a team

### ISSUE THREAD

**Issue by MyNameIsTroll** [penpot/penpot#676]
**Is your feature request related to a problem? Please describe.**
I would like to import a document I started alone in a new team. 

**Describe the solution you'd like**
I was thinking of an option "import an existing document" in the team section for example. Or via a drop menu (three points)

**Describe alternatives you've considered**
Currently we can copy-paste an artboard and paste it into another blank document of a team, it's already a good thing but it's not very intuitive and it requires several tedious manipulations. 

**Additional context**

![image](https://user-images.githubusercontent.com/31790025/108596742-41ffe280-7387-11eb-8bc5-ca7db152f8c5.png)

![image](https://user-images.githubusercontent.com/31790025/108597245-52648d00-7388-11eb-88b6-74279e195b2a.png)

**Comment by claragvinola** [comment]
Hi! Thank you for your feedback! We're currently working on a US related to Project files organization that we think solves your problem.

https://tree.taiga.io/project/penpot/us/267?milestone=262806

**Comment by MyNameIsTroll** [comment]
Thank you @claragvinola 
it looks great, thanks for your work.

**Comment by MyNameIsTroll** [comment]
I close this issue because there is already one :
https://github.com/penpot/penpot/issues/547
