### ISSUE TITLE
Order of pages is different in edit mode and view mode.

### ISSUE THREAD

**Issue by studiospring** [penpot/penpot#68]
In edit mode, new pages are added above the current page. In view mode, pages are added to the end of the list. Personally, I think adding new pages immediately below the current page is the most intuitive.

**Comment by niwinz** [comment]
Fixed.

**Comment by studiospring** [comment]
Nothing has changed for me (I'm at commit 993657a1).
![page](https://cloud.githubusercontent.com/assets/4901306/23534101/b19afa30-0009-11e7-9a1e-11cb11c4c990.gif)

**Comment by niwinz** [comment]
Please, can you verify if this is not a cache issue. You can test this just tesing it on test.uxbox.io (demo instance), and you can login with user20/123123 credentials or just register an other user (take care that this is a demo instance and your data will be wiped periodically)

**Comment by studiospring** [comment]
Sorry, you're right. It was a caching issue.
