### ISSUE TITLE
Partial export of artboard only

### ISSUE THREAD

**Issue by diacritica** [penpot/penpot#685]
**Describe the bug**
Selecting an artboard and exporting the full of it generates incomplete PNG, JPG and SVG (same output)

**To Reproduce**
1.  Go to https://design.penpot.app/#/workspace/e372f140-58c3-11eb-8e53-556a2f641513/e4f57290-58c3-11eb-8e53-556a2f641513?page-id=e4f57291-58c3-11eb-8e53-556a2f641513
2.  Click on Character Sheet and then Sheet
3.  Select Sheet and try to export
4.  See incomplete output

**Expected behavior**
It should export the whole artboard

**Screenshots**
![Sheet](https://user-images.githubusercontent.com/1606348/108780133-47685300-7568-11eb-9198-c4a85b6eaf54.png)

**Desktop (please complete the following information):**

-   OS: Linux (Ubuntu 20.10)
-   Browser Firefox
-   85.01

**Environment (please complete the following information):**
Demo instance

**Comment by diacritica** [comment]
It works now? 
![Sheet](https://user-images.githubusercontent.com/1606348/108882080-497fef80-7604-11eb-803c-79f6f2fe22c9.png)

**Comment by diacritica** [comment]
hmm, not exactly, layer position has changed for some objects, but looking much better now

**Comment by diacritica** [comment]
I changed layer order for the border decorations and now it looks great, export is WYSIWYG again :)
![Sheet](https://user-images.githubusercontent.com/1606348/108884206-9d8bd380-7606-11eb-9958-1c66680f110d.png)
I'd be happy to close this issue but I'd rather understand what happened here :)

**Comment by elhombretecla** [comment]
Hi Pablo!!!

This is nos a bug itself. It seems that there was a problem with the elements positioned outside the artboard. They look like are well positioned but they did't belong to the artboard at the layers panel.

**Comment by diacritica** [comment]
Hi Juan! OK, so could it be that some elements moved away from the artboard? I will be monitoring this is case it happens again. Basically, duplicating an artboard with many elements could (if there's a bug) leave some elements OUTSIDE the artboard without being too obvious (they are visible).
