### ISSUE TITLE
Can not write character with special accent

### ISSUE THREAD

**Issue by KillianKemps** [penpot/penpot#688]
**Describe the bug**
I want to write text in French in my designs. I'm able to write characters like "é" and "è", but not "û" and "ê". To write these characters on other apps, I need to tap on the "^" button of the keyboard and then on the "e" letter as an example. In Penpot the characters simply doesn't show up.
For the moment the workaround I use is to copy the characters inside Penpot.

**To Reproduce**
1.  Create a text box
2.  Write the following text: "un coût"
3.  See that only this has been written: "un cot"

**Expected behavior**
Have "un coût" written

**Desktop (please complete the following information):**

-   OS: Linux (Arch Linux)
-   Browser (e.g. chrome, safari): Firefox Developer edition
-   Version (e.g. 22) 86.0b4

**Environment (please complete the following information):**
https://design.penpot.app

**Comment by niwinz** [comment]
Hi @KillianKemps 
Seems like in chromium it works:
![Peek 2021-02-23 18-30](https://user-images.githubusercontent.com/843689/108883002-36b9ea80-7605-11eb-8753-3f403ea1c23e.gif)

But on firefox it crashes :(. 
We will look on it, thanks for the report.

**Comment by niwinz** [comment]
This bugs will be resolved in the next release (the fixes are already landed on the `develop` branch).

**Comment by niwinz** [comment]
Release is out :tada:
