### ISSUE TITLE
View mode is missing the "Sitemap" title.

### ISSUE THREAD

**Issue by studiospring** [penpot/penpot#69]
Edit mode
![edit_mode](https://cloud.githubusercontent.com/assets/4901306/23487780/73d41cd6-ff3c-11e6-9e3a-dfb08d04106e.jpg)
View mode
![view_mode](https://cloud.githubusercontent.com/assets/4901306/23487792/7f1d2880-ff3c-11e6-83b2-7b0c658250d4.jpg)

**Comment by niwinz** [comment]
The current approach is expected one, the sitemap title is not missing, it is just omited on view. In any case, the view part need some revisit and maybe we'll take this in consideration.

Thanks.
