### ISSUE TITLE
Create/Provide Android design system shared library

### ISSUE THREAD

**Issue by keunes** [penpot/penpot#690]
Related to (or duplicate of) #630?

**Is your feature request related to a problem? Please describe.**
I'm trying to make mock-ups for AntennaPod, but currently need to import icon and stuff to create them.

**Describe the solution you'd like**
A shared library with:
- the https://github.com/Templarian/MaterialDesign icon set
- the Google-specified components https://material.io/components

**Describe alternatives you've considered**

**Additional context**
Love the concept of shared libraries importable to your project/account :)

**Comment by hirunatan** [comment]
Thanks for the feedback. As @niwinz said at #630, in our plans are a rework of libraries, to improve usability and likely to have some standard libraries shipped by default.

For the moment you can create your own library, shared with your team, and load there any icons you need.

**Comment by hirunatan** [comment]
Close this, as this is related also to #620, can manage all of them at once.
