### ISSUE TITLE
Local font listed but not rendered

### ISSUE THREAD

**Issue by keunes** [penpot/penpot#691]
**Describe the bug**
When creating a text element, in the 'font' settings I see three 'Local' fonts listed. However, selecting 'Roboto' or 'Roboto condensed' the font isn't applied (not available?)

**To Reproduce**
1.  Install Roboto font on your computer
2.  Add a text element
3.  Select 'Roboto' from the font selector
4.  See error

**Expected behavior**
Use Roboto font

The font is rendered correctly after having selected their siblings from the Google-provided list. The local font Source Sans Pro does seem to be rendered correctly (at least, it's a sans font that's rendered).

**Screenshots**
![Schermafdruk van 2021-02-24 08-58-15](https://user-images.githubusercontent.com/11229646/108967129-660d3d80-767f-11eb-9671-56609e024d0f.png)

**Desktop (please complete the following information):**

-   OS: Ubuntu 18.04
-   Browser Firefox 85.0.1

**Comment by hirunatan** [comment]
Hi, @keunes.  I cannot reproduce the bug, In a setting with linux and firefox I see the correct fonts:

![image](https://user-images.githubusercontent.com/1483050/108989753-3d447280-7696-11eb-985d-761efc8692a7.png)

What do you mean by "The font is rendered correctly after having selected their siblings from the Google-provided list"?

Currently the fonts used in penpot are independent of what ones do you have installed in your machine. It uses standard Google fonts.

**Comment by keunes** [comment]
Thanks for chipping in
> What do you mean by "The font is rendered correctly after having selected their siblings from the Google-provided list"?

When opening penpot for the first time and creating a text item with the Roboto font from the '**local**' list it's not rendered correctly. Then if I select Roboto from the **Google** list, and finally select Roboto from the **local** list again, the font is rendered successfully (supposedly not using the locally installed font, but the web font that was just cached from Google)

> Currently the fonts used in penpot are independent of what ones do you have installed in your machine. It uses standard Google fonts.

That surprises me, given that in the font drop-down I have a 'local' and a 'Google' header.

**Comment by hirunatan** [comment]
Ah, I understand. The "local" label does not refer to your locally installed fonts, but the fonts that are installed in the server you are connected to. It's true that it may cause confusion, we are going to rename it to "preset", for example.

And there is a bug indeed: the roboto font is no longer used in the default installation, because it's already available as a google font, so we removed it. But we forgot to update the fonts list.

I'll fix this ASAP.

**Comment by hirunatan** [comment]
Anyway, all this will be enhanced soon, this is one of our top priorities: https://tree.taiga.io/project/penpot/us/292?no-milestone=1

**Comment by keunes** [comment]
Ah, awesome!

**Comment by hirunatan** [comment]
Done! You'll see it when the next release is published.
