### ISSUE TITLE
Crop imported image

### ISSUE THREAD

**Issue by keunes** [penpot/penpot#692]
**Is your feature request related to a problem? Please describe.**
I'm aiming to create a mock-up for a new feature in AntennaPod (Android app). To save myself some time replicating standard components (like the android top bar and the app's top bar), I imported a screenshot from the app that I'd like to reuse across different artboards.

**Describe the solution you'd like**
Be able to 'crop' the imported screenshot, so only the top x pixels is displayed (similar to elements outside the artboard being cut off). I imagine an extra field under 'size' titled 'container size' might work? I don't know - you probably have better ideas :)

**Describe alternatives you've considered**

**Additional context**

**Comment by hirunatan** [comment]
You can do this with a mask.

- Create a rectangle that cover the part of the image you want to be visible.
- Create a group with the image and the rectangle.
- Send the rectangle to the back of the group.
- Select the group and click "Mask" in the context menu.

**Comment by keunes** [comment]
Oh wow, great. Thanks @hirunatan!
