### ISSUE TITLE
Path objects and pencil objects should be differentiated.

### ISSUE THREAD

**Issue by studiospring** [penpot/penpot#70]
Path objects and pencil objects use different tools and icons to create them, but they are represented by the same icon and name in the layers panel. It would be more consistent and easier to identify if the pencil objects were given a pencil icon and name.

**Comment by niwinz** [comment]
I understand that you trying to say. But, ... on the end they are the same thing. They are different tools because we offer two different ways to build paths: in a free drawing or assisted lines (or curves in future).

What do you think about this @elhombretecla ?
