### ISSUE TITLE
Internal server error when typing é

### ISSUE THREAD

**Issue by keunes** [penpot/penpot#701]
**Describe the bug**
When trying to type é (e-acute) I get an internal server error

**To Reproduce**
1.  Go to [this file](https://design.penpot.app/#/view/e357a320-7535-11eb-8a88-eb0147e048f5/e357a321-7535-11eb-8a88-eb0147e048f5?token=L4p-9sogmtEVgXkHrtErlg&index=0)
2.  Double-click on the Text-5 element to start editing the text
3.  Type é
4.  See error

**Expected behavior**
Add the é

**Screenshots**
![Schermafdruk van 2021-02-24 20-56-36](https://user-images.githubusercontent.com/11229646/109058804-b918dc00-76e3-11eb-9b28-84abe6e7dec4.png)
![Schermafdruk van 2021-02-24 21-02-48](https://user-images.githubusercontent.com/11229646/109058809-ba4a0900-76e3-11eb-858a-74e66537d270.png)

**Desktop (please complete the following information):**

-   OS: Ubuntu
-   Browser Firefox

using SAAS (https://design.penpot.app)

**Comment by keunes** [comment]
Duplicate of #688

**Comment by niwinz** [comment]
We have many problems with current editor and we are thinking in a solution.
