### ISSUE TITLE
Ability to chose underline color

### ISSUE THREAD

**Issue by Dehelssey** [penpot/penpot#703]
When text is underlined, for example on links, CSS offers the possibility to use a different color for the line. 

I often design websites where links and their underline have different colors but i can't do that on Penpot right now. For the moment, i cheat with a rectangular shape that i place under my text but it's not how underline text actually looks like on a browser

I wish Penpot could implement an option to pick line color on underline text :)

**Comment by elhombretecla** [comment]
Thank you very much for your feedback!

We will review and evaluate your proposal with the core team :)
