### ISSUE TITLE
SVG Export Issue, suggestion to facilitate svg code copy for a more stable way

### ISSUE THREAD

**Issue by APattjoshi** [penpot/penpot#705]
Describe the bug
Trying to export SVG

To Reproduce

Create an artboard
Select the Artboard
Press export
It says exporting for sometime
The shows a push notification saying unexpected error
It did not export
Selected another artboard
export shape
Exported

Issue
But the SVG was corrupted not opening properly in another program like Inkscape
Tried exporting another Artboard it did not work

Expected behavior
It should Export an SVG to the local machine

Screenshots
![Capture](https://user-images.githubusercontent.com/47391164/109255874-d3090a80-781a-11eb-9950-9c1d93e9bead.PNG)
![Capture1](https://user-images.githubusercontent.com/47391164/109255882-d69c9180-781a-11eb-92ff-bc777cd649c8.PNG)

Desktop (please complete the following information):

OS: (Windows 10)
Browser (chrome)
Version (88.0.4324.182 (Official Build) (64-bit)

*I don't know how to provide a file id for you to check
*Suggestion to facilitate SVG code copy for a more stable way

**Comment by elhombretecla** [comment]
Hi!!! This issue is duplicated :)

https://github.com/penpot/penpot/issues/673
