### ISSUE TITLE
Allow to move files from drafts to projects from Dashboard

### ISSUE THREAD

**Issue by keunes** [penpot/penpot#706]
**Is your feature request related to a problem? Please describe.**
The first time I logged in to Penpot I didn't really pay attention to the project/file structure and just started a file. It seems to be in the Drafts folder/project. Now I'm getting a bit more involved, I created a new project, and would like to move the relevant file there. I don't see a way to do that.

**Describe the solution you'd like**
Add option 'Move to project' to contextual menu of files in Drafts section (?)

**Describe alternatives you've considered**
Drag-and-drop files to projects in the sidebar. Probably more complex to implement reliably.

**Additional context**
n/a

**Comment by elhombretecla** [comment]
Hi @keunes !!! Thanks for your feedback :)

We are currently working on this. We expect to implement it very soon!
You will be able to move files between projects and teams. Also you could move and duplicate entire projects :)

https://tree.taiga.io/project/penpot/us/267?milestone=284230
