### ISSUE TITLE
'Typographies' of assets cannot be collapsed

### ISSUE THREAD

**Issue by keunes** [penpot/penpot#707]
**Describe the bug**
The 'Typographies' sections under assets can't be collapsed like the other asset sections (components, graphics).

**To Reproduce**
1.  Go to 'Assets'
2.  Click on the the down arrow left from the 'Typographies' section
4.  See error

**Expected behavior**
Collapse section when clicking on arrow.

**Desktop (please complete the following information):**
-   OS: Ubuntu 18.04
-   Browser: Firefox 85.0.1

**Comment by elhombretecla** [comment]
Thanks for notice that.

You could track the issue here

https://tree.taiga.io/project/penpot/issue/1320
