### ISSUE TITLE
Don't take group out of artboard when moved partly outside

### ISSUE THREAD

**Issue by keunes** [penpot/penpot#708]
**Is your feature request related to a problem? Please describe.**
I'm moving a group with elements partly outside the artboard, in order to imitate a 'swipe' effect on the element. I get frustrated every time I do this (or move it a little bit further), as the group gets detached from the artboard - and the layer order messed up and the whole element becomes visible outside the artboard.

**Describe the solution you'd like**
Do not take an element/group outside of an artboard automatically (except maybe when the group is placed completely outside).

**Describe alternatives you've considered**
Can't think of any.

**Additional context**
How it gets:
![afbeelding](https://user-images.githubusercontent.com/11229646/109360292-3892e080-7887-11eb-90d9-1da478e55bc0.png)

After I put it back in place:
![afbeelding](https://user-images.githubusercontent.com/11229646/109360375-68da7f00-7887-11eb-8a19-0a81490289bb.png)

**Comment by elhombretecla** [comment]
Hi! Thank you so much for your feedback!

This is a bug, not an enhancement. We will check all the elements/artboard behavior and validate this issue.
We will be back with more info soon. You can follow this issue here

https://tree.taiga.io/project/penpot/issue/1322

**Comment by myfunnyandy** [comment]
This should be fixed with the last release so I'm closing the issue.
