### ISSUE TITLE
Bundle common FOSS icon fonts with Penpot

### ISSUE THREAD

**Issue by 12people** [penpot/penpot#713]
**Is your feature request related to a problem? Please describe.**
In both Sketch and Figma, I've gotten used to inserting icons using icon fonts.

(The fonts I use use ligatures to be able to add certain icons, which makes the process of adding an icon as simple as writing the icon's name, changing the font to the icon font, and setting the font size.)

**Describe the solution you'd like**
Include open-source icon fonts like the Apache-licensed [Material Design icons](https://github.com/google/material-design-icons) or the SIL-licensed free version of [Font Awesome](https://fontawesome.com/download) with Penpot.

Unlike with local font support, bundling these outright would have the advantage of open-source projects being able to use these fonts in their wireframes and mock-ups, share those with the community, and not have to worry about icons not displaying for some.

**Comment by 12people** [comment]
Just a note — this is different from [#620](https://github.com/penpot/penpot/issues/620) in that I'm asking for the fonts to be bundled themselves, rather than SVG symbol libraries.

**Comment by keunes** [comment]
What's the benefit of adding them as fonts over adding the SVG set (eg for MD icons) as a shared library?

**Comment by 12people** [comment]
@keunes It's mainly a workflow difference for me.

With assets, to add an icon, you have to open the Assets sidebar, click on the search field, type the name, and drag and drop the icon onto the canvas. To replace an icon, you currently have to delete the previous one and repeat this whole process. With nested assets, there seems to currently be no way to replace an inner asset, though I expect this might change in the future.

With an icon font, to add an icon, you write the icon name as text (if the icon font supports ligatures, which the fonts above do), then change the font. To replace an icon, you simply edit the text. This works with both individual objects as well as nested assets.

When it comes to use in assets, icon fonts make life easier in a number of ways. I can use assets to be able to add icons of a certain size and color quickly (e.g. have a "small dark icon" asset for 18x18 black icons and a "large light icon" for 24x24 white icons).

And icon fonts in assets also allow me to specify the exact icon size and color I want inside of assets. For example, I can have an "active icon tab" containing an icon with my primary color, then an "inactive icon tab" containing an icon with a gray color. And by using an icon font inside these assets, I can easily replace the specific icon while maintaining the size and color that the asset calls for.

It's worth noting that this is not an "either or" situation — there are use cases for icons as shared libraries too.

**Comment by keunes** [comment]
> To replace an icon, you currently have to delete the previous one and repeat this whole process.

Especially this I second - deserves its own feature request I reckon.

**Comment by claragvinola** [comment]
Hi! we have an US regarding Advanced Font Management (https://tree.taiga.io/project/penpot/us/292?no-milestone=1).

We expect that these solve your problems in the future :)

**Comment by 12people** [comment]
@claragvinola Will that allow use in public libraries ( as proposed in #562 )? I have a wireframe kit that uses open-source icon fonts that I'd like to share in the future.

If so, then it would meet my needs. :)

Though I would also welcome shipping the fonts with Penpot outright, as that would be much faster and simpler to implement (it's really just adding a few more open-source fonts to the default selection), as well as easier to discover and use for users.
