### ISSUE TITLE
UI Walkthrough contains wrong text

### ISSUE THREAD

**Issue by FlorianLudwig** [penpot/penpot#716]
**Describe the bug**
"Graphics", "colors" and "typography" contain the same explanation text:

**To Reproduce**
1.  Go to 'UI Walkthrough'
2.  Click on 'Assets'
3.  Scroll down
4.  See error

> Both bitmap and vector images can be stored at the Graphics section.

**Screenshots**

![image](https://user-images.githubusercontent.com/432263/109417943-089e2700-79c6-11eb-8550-68768d8a843c.png)

**Comment by elhombretecla** [comment]
Thank you so much!!!

We will correct this as soon as we can :)

Follow this issue on Taiga
https://tree.taiga.io/project/penpot/issue/1325
