### ISSUE TITLE
Clicking middle mouse moves the canvas (without moving the cursor)

### ISSUE THREAD

**Issue by FlorianLudwig** [penpot/penpot#717]
**Describe the bug**
Clicking the middle mouse button without moving the mouse moves the canvas a varying amount to some direction

**To Reproduce**
1.  Go to any 
2.  Click the middle mouse button (do not move the mouse)
3.  Canvas moves

**Expected behavior**
Canvas should not be moved

**Desktop (please complete the following information):**

-   OS: Linux
-   Browser Firefox
-   Version 85

**Environment (please complete the following information):**
https://design.penpot.app

**Comment by elhombretecla** [comment]
Ok! I've already reproduce this bug.

We will manage it from Taiga issues
https://tree.taiga.io/project/penpot/issue/1326
