### ISSUE TITLE
Interaction area not clickable when layer is below masked image

### ISSUE THREAD

**Issue by keunes** [penpot/penpot#718]
**Describe the bug**
A specific interaction area, while highlighted, is not clickable in the preview. 

**To Reproduce**
1.  Create specific layer for interaction
2.  Put it below a mask group of which the masked layer covers the clickable area
3.  Go to preview
4.  See error

**Expected behavior**

**Screenshots**
Works:
![image](https://user-images.githubusercontent.com/11229646/109420563-7dc42900-79d3-11eb-9914-465f42c4d225.png)

Does not work:
![image](https://user-images.githubusercontent.com/11229646/109420571-916f8f80-79d3-11eb-95ac-6e31b91ea04e.png)

Mask area:
![image](https://user-images.githubusercontent.com/11229646/109420592-a3e9c900-79d3-11eb-94aa-53b9beb02162.png)

Masked image:
![image](https://user-images.githubusercontent.com/11229646/109420599-afd58b00-79d3-11eb-8b03-fd2555c245ca.png)

**Desktop (please complete the following information):**

-   OS: Ubuntu 18.04
-   Browser: Firefox 86.0

**Environment (please complete the following information):**
using SAAS (https://design.penpot.app)

**Comment by claragvinola** [comment]
Hi! sorry but we can't reproduce de bug! can you get us more info? maybe de size of the maks, layer...

**Comment by keunes** [comment]
Hi @claragvinola
Sure! Thanks a lot for looking into it :)
The masked screenshot:
```
/* UI Settings screenshot (mask group) */
.ui-settings-screenshot {
  width: 360px;
  height: 405px;
  left: 0px;
  top: 80px;
}
/* Screenshot_20210228-123811.png-1 */
.screenshot-20210228-123811-png-1 {
  width: 360px;
  height: 720px;
  top: -65px;
}
/* Rect-6 */
.rect-6 {
  width: 360px;
  height: 405px;
  top: 80px;
  background: rgba(177, 178, 181, 1);
}
```
The affected interactive element:
```
/* Swipe click area */
.swipe-click-area {
  width: 360px;
  height: 56px;
  top: 545px;
}
```

It concerns [this design](https://design.penpot.app/#/handoff/e357a320-7535-11eb-8a88-eb0147e048f5/e357a321-7535-11eb-8a88-eb0147e048f5?token=L4p-9sogmtEVgXkHrtErlg&index=8).

**Comment by niwinz** [comment]
I think I understand the problem; thanks @keunes i'll [report it internally](https://tree.taiga.io/project/penpot/issue/1333)
