### ISSUE TITLE
Cannot ungroup objects.

### ISSUE THREAD

**Issue by studiospring** [penpot/penpot#72]
If I select the group layer, the ungroup icon is disabled. I expect to be able to ungroup all objects if the group-1 object is selected.
![group](https://cloud.githubusercontent.com/assets/4901306/23535400/3a2e6dd4-0012-11e7-9c9e-db5776cc5ac0.jpg)
If I select a grouped object, the ungroup icon is enabled, but does not ungroup. It would be nice if selecting one grouped object (eg Circle-1) let me ungroup only that object.
![group_object](https://cloud.githubusercontent.com/assets/4901306/23535468/a12b4f8e-0012-11e7-9887-3f160bb64783.jpg).

However, I can ungroup nested groups. But it still does strange things. Notice in the gif that after I ungroup Group-3, the ungroup icon is still enabled and only after I click it again does it become disabled.
![layer](https://cloud.githubusercontent.com/assets/4901306/23535844/17687d14-0015-11e7-9057-9745df2c0869.gif)

**Comment by niwinz** [comment]
Seems like a bug!

**Comment by niwinz** [comment]
Now should be fixed on master.

**Comment by niwinz** [comment]
If you find more corner cases, please reopen the issue, I have rewrote the implementation of the degroup-shape functionality in order to fix all common use cases and add corresponding tests for that but it also can be a source of new bugs.
