### ISSUE TITLE
LDAP authentication should succeed more than once.

### ISSUE THREAD

**Issue by felixvf** [penpot/penpot#722]
**Describe the bug**
When authenticating using LDAP, the first authentication is successful. However, when performing another authentication (with the same credentials), the authentication fails.

**To Reproduce**
1.  Setup penpot with LDAP authentication and an LDAP server which requires a password for penpot against the LDAP server. Use this https://github.com/penpot/penpot/commits/645954bc7c12be0d1d80bd050f392b62fac7679a version.
2.  Enter a user account e-mail address and password. Login with LDAP.
3.  Observe that the login succeeds.
4.  Logout.
5.  Enter a user account e-mail address and password. Login with LDAP.

**Expected behavior**
It is expected that the login succeeds.

**Backend Stack Trace (if self-hosted)**

<details>

```
com.unboundid.ldap.sdk.LDAPSearchException: no such object
```

</details>

**Additional context**
It seems to me that it is plausible that cache invalidation may be a problem, with the following hypothesis: The LDAP bind operation is successful at the time of the first login. At the time of the second login, the LDAP session may already be bound, therefore preventing any further LDAP bind operation to be successful. The solution would be to not cache, just to setup the LDAP connection every time someone tries to login. This may be less efficient that incorrect cache invalidation, but more correct and reliable.

**Comment by niwinz** [comment]
Hi @felixvf 

Thanks for reporting it; I have tried it many times and i'm always being able to login with same user or different user.

I'm using this LDAP test server: https://github.com/penpot/penpot/blob/develop/docker/devenv/docker-compose.yaml#L102 with the configuration here: https://github.com/penpot/penpot/blob/develop/docker/devenv/docker-compose.yaml#L57

**Comment by felixvf** [comment]
Hi @niwinz,

> Thanks for reporting it; I have tried it many times and i'm always being able to login with same user or different user.

I believe the difference between our setup and the rroemhild/test-openldap setup is in `slapd.conf`:

In our setup, only anonymous users may authenticate and only user "uid=penpot,dc=foo,dc.bar" may read (as suggested by [these examples](https://openldap.org/doc/admin24/access-control.html)) . Hence, our `slapd.conf` contains something like:

```
access to dn.base=""
        by * none

access to *
        by "uid=penpot,dc=foo,dc.bar" read
        by self read
        by anonymous auth
        by * none
```

whereas in rroemhild/test-openldap, the file `/usr/share/slapd/slapd.conf` contains

```
access to dn.base="" by * read

# The admin dn has full write access, everyone else
# can read everything.
access to *
        by dn="@ADMIN@" write
        by * read
```

which means that everyone is permitted read (and thus to authenticate). This means that the settings of rroemhild/test-openldap seem to be too loose to exhibit the bug, because, with the default settings of rroemhild/test-openldap, once a user is authenticated ("bound" in LDAP parlance), this new user can still read the whole database (and thus re-authenticate as a yet a different user), whereas with more tight ACLs, this would not be permitted.

**Comment by niwinz** [comment]
@felixvf  hmm; I understand.
So, I think that instead of using pooled connection, we need to create a separated connection for each request for solve this issue. I'm right?

**Comment by felixvf** [comment]
> @felixvf hmm; I understand.
> So, I think that instead of using pooled connection, we need to create a separated connection for each request for solve this issue. I'm right?

@niwinz,

Yes.
(It seems to me that there is a bug lurking deeper in or below clj-ldap which causes this problem, as the [documentation](https://github.com/pauldorman/clj-ldap#bind-connection-bind-dn-password-connection-pool-bind-dn-password-1) says that "bind?" should actually have no side-effects, which it actually seems to have.)
So I think: One separate LDAP connection per request will solve the problem, because then, no advanced (but apparently broken) features of clj-ldap or its dependencies are being employed.

**Comment by niwinz** [comment]
@felixvf ok, I will look into it, thanks for the hint.

**Comment by niwinz** [comment]
I removed the connection caching in this commit: https://github.com/penpot/penpot/commit/5ae823b25c0ac06f508bab074df9fdb55debe8f6
It will be released on the next release.

**Comment by felixvf** [comment]
> I removed the connection caching in this commit: [5ae823b](https://github.com/penpot/penpot/commit/5ae823b25c0ac06f508bab074df9fdb55debe8f6)
> It will be released on the next release.

Thank you, @niwinz!

I have tried the new version of penpot.

However, now, LDAP authentication with password for the LDAP client does not work at all.

It seems that the connection parameters `bind-dn`, `password` are completely ignored now. The cause of this seems that the new code uses `ldap/create-connection` instead of `ldap/connect`, and no attempt to call `.bind` seems to be made at all, while it should be made, as shown here: https://github.com/pauldorman/clj-ldap/blob/v0.17/src/clj_ldap/client.clj#L234.

**Comment by niwinz** [comment]
@felixvf sorry for not looking into it, I was very busy this days; I'll try to take a look on it the next week.

**Comment by niwinz** [comment]
I commited a fix, and changed the dependency to use the pauldormant/clj-ldap. Should be fixed in next release. If you prefer test a development snapshot, just tellme and I will publish a snapshot images from develop branch (once it is merged).

**Comment by felixvf** [comment]
@niwinz,

I've been testing your branch (https://github.com/penpot/penpot/tree/niwinz/ldap-fixes) and found that it works. Now multiple users can log in! Thank you very much!
