### ISSUE TITLE
Enable replacement of graphic assets in designs

### ISSUE THREAD

**Issue by keunes** [penpot/penpot#723]
**Is your feature request related to a problem? Please describe.**
From #713:
> With assets, to add an icon, you have to open the Assets sidebar, click on the search field, type the name, and drag and drop the icon onto the canvas. To replace an icon, you currently have to delete the previous one and repeat this whole process. With nested assets, there seems to currently be no way to replace an inner asset
> Allow me to specify the exact icon size and color I want inside of assets

My personal use-case: I use Material Design Icons throughout my work, but changed my mind about which icon exactly to use. It was annoying to update all individual icons (which weren't part of a component) as I had to reposition (so they're on the exact same spot), refill (so they had the same colour), and re-resize (from 24 -> 30 px) them.

**Describe the solution you'd like**
Allow to drag and drop an asset on top of an existing asset. If the new asset is more or less the same (original and/or target) size as the asset on the canvas, and is dropped on top of the existing asset (e.g. with 95% overlap), then replace the asset on the canvas. The new asset takes the properties (e.g. shadow, filling, size) of the previous asset.
@12people your thoughts are very welcome here.

**Describe alternatives you've considered**
Right-click on a layer, and select 'Replace asset'. However this would need an extra 'pop-up' interface to find and select the new asset.

**Additional context**
n/a

**Comment by elhombretecla** [comment]
Hi @keunes thanks for your feedback!

We are currently working on assets improvements and have ideas like yours in mind. It will be very useful to switch and manage assets with this kind of interface behaviour. We will manage this and validate it from Taiga.

[https://tree.taiga.io/project/penpot/us/1331](https://tree.taiga.io/project/penpot/us/1331)
