### ISSUE TITLE
Advanced interactions

### ISSUE THREAD

**Issue by mjourdan** [penpot/penpot#724]
**Is your feature request related to a problem? Please describe.**
Making prototypes I end up making several duplicates of a same artboard, to only change a few details each time (setting button states, revealing modal windows, scrolling position, etc.).

**Describe the solution you'd like**
I would like to be able to:
- scroll content in a single artboard
- set some artboards as overlays on top of other artboards
- pick up a transitions (slide, push, fade...) between two artboards
- manage different inputs (click, hover, drag...)

**Describe alternatives you've considered**
Performing actions (like show/hide) in a single artboard instead of defining artboards as overlays. This has downsides when making wireframes.

**Additional context**
[Example in Figma](https://www.youtube.com/watch?v=-d6zNGeF59M)

**Comment by keunes** [comment]
+1 for scrolling within a board especially. Sliding elements would be a nice second for me :)

**Comment by niwinz** [comment]
thanks @mjourdan 

A [similar task](https://tree.taiga.io/project/penpot/us/244) is already in our roadmap; i will add this GH issue as addtional input when we approach the task.

**Comment by mjourdan** [comment]
Oh, thank you for the pointer!

**Comment by jcklpe** [comment]
I don't see "hover state" covered by the linked task on roadmap. I think that's one of the largest things missing that Adobe XD does that prevents me from switching.

**Comment by maciek134** [comment]
I think this issue is no longer tracked in the linked taiga ticket? The taiga one is closed and the only thing from this one that's implemented are overlays. Transitions/animations would be nice too, eg. "when I click this element, move this one 100px left".

**Comment by madalenapmelo-kp** [comment]
These features have been implemented with the exception of scrolling content in a single board, which is being tracked on this [Taiga User Story](https://tree.taiga.io/project/penpot/us/4519).

I'm closing this issue as there is already #4438 where this is being tracked as well.
