### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by keunes** [penpot/penpot#725]
Hello
I love Penpot and am happy to use it in English. I'm wondering if it makes sense to start translating a rather technical tool as penpot.
I see on the main website that in the current alpha French translations were improved. So I reckon the idea is to make it available in multiple languages?

If so, is there anywhere the community can contribute? (If yes, that should probably be added to the Contributions doc. If not yet but desired, I would recommend Weblate, although there are a few other open source services out there as well, which I have no experience with.)

**Comment by niwinz** [comment]
Hi @keunes 

Right now we don't have a specific tool/platform for managing translations, and is a pending issue in our roadmap (we will discuss it on our next planning session).

For now, you have the `frontend/resources/locales.json` file that has all the translation strings used in the application, and it already has translations. We officially maintain the English and Spanish translations; and we have French, Russian & Chinese as community contributed (with different level of completeness).

If you wan't to help us translate, feel free to open small incremental PR's with changes to that file. But beware, the application is constantly changing and some translations can become outdated quickly.

**Comment by keunes** [comment]
I'll wait for when there's a translations tool (at some point in future) :)
