### ISSUE TITLE
Display 'copy code' icon when hovering code in (pre)view

### ISSUE THREAD

**Issue by keunes** [penpot/penpot#727]
**Is your feature request related to a problem? Please describe.**
Not particularly. Only it was a bit difficult in the beginning to understand how to copy the code from an element, for https://github.com/penpot/penpot/issues/718#issuecomment-788899549. Stumbled upon the 'copy' icon by chance as I tried what the CSS dropdown selector does.

**Describe the solution you'd like**
Display the 'copy' icon (and 'expand' icon, I reckon) when hovering the code of an element, in the (pre)view screen.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by niwinz** [comment]
thanks @keunes 

I have [reported it internally](https://tree.taiga.io/project/penpot/issue/1332) for design/ux review
