### ISSUE TITLE
Redo does not work.

### ISSUE THREAD

**Issue by studiospring** [penpot/penpot#73]
I hope I'm not annoying you with all this feedback!!! :D Keep up the great work. I'm looking forward to an amazing release!

![redo](https://cloud.githubusercontent.com/assets/4901306/23536490/26452d8a-ffbd-11e6-8ce1-e3285f40afe7.gif)

**Comment by niwinz** [comment]
@studiospring Not at all! Your feedback is very welcome!

**Comment by niwinz** [comment]
Fixed!
