### ISSUE TITLE
Show colour name on hover (in the picker)

### ISSUE THREAD

**Issue by keunes** [penpot/penpot#730]
**Is your feature request related to a problem? Please describe.**
I have different types of grey in my mock-ups which are very much alike. Currently, to make sure I have the correct one I have to try one, and then read the name that appears in the 'Design' tab on the right-hand side, and circle through a few until I have the correct one.

**Describe the solution you'd like**
Display colour name from the asset library (or colour code if it doesn't have a name) in the colour picker when hovering a colour at the bottom of the picker.

**Describe alternatives you've considered**
-

**Additional context**
![afbeelding](https://user-images.githubusercontent.com/11229646/109811122-b9a4fb80-7c2a-11eb-8f63-9f4f0f5d932a.png)

**Comment by hirunatan** [comment]
Thanks. I'll do this as soon as we can.

See it in Taiga: https://tree.taiga.io/project/penpot/issue/1368

**Comment by myfunnyandy** [comment]
Closing as this is already done.

**Comment by keunes** [comment]
Hi @myfunnyandy, @hirunatan,

I just checked and this doesn't seem to be implemented, or at least not working in Chromium. What I'd be expecting is something like this (quick test by adding a `title` attribute to the div with the `color-bullet` class):
![Screenshot from 2022-12-11 19-03-30](https://user-images.githubusercontent.com/11229646/206920700-27920cd6-28a7-41db-8f84-6f9d4feaff04.png)

EDIT: I see now that there's an `::after` element, which is not showing for me but the area can be made visible via the inspector. So I guess it's a bug. Please let me know if I should open a new issue for this.

**Comment by myfunnyandy** [comment]
hi @keunes, it definitely worked when I closed the issue, we must have broken something recently. I'm reopening all this.

**Comment by keunes** [comment]
Thanks a lot and apologies for the somewhat agressive tagging.

**Comment by myfunnyandy** [comment]
No worries @keunes, thank you very much for poiting it out. Surely it would have taken much more time for us to catch the bug if you hadn't.

btw the fix is already in preproduction environments, hopefully we will publish it soon :)
