### ISSUE TITLE
Code for design is publicly accessible for anyone having the view-share-link

### ISSUE THREAD

**Issue by itgenie98** [penpot/penpot#736]
**Is your feature request related to a problem? Please describe.**
In view mode, when not logged in, the code button and code view is present, and thus enables third party persons (such as clients) to inspect and potentially copy the code and use the code for themself before the work is finished.

**Describe the solution you'd like**
Hideing the code mode button when no user is logged in (or the user has no permission to see the code)

**Describe alternatives you've considered**
An alternative way whould be a setting that; thus anyone can decide if third-party persons that have the view-link can see the code or not.

**Additional context**
![grafik](https://user-images.githubusercontent.com/16072267/110224088-ef6f0c00-7ed8-11eb-8408-92651d5af627.png)

**Comment by hirunatan** [comment]
Thanks for the idea. We'll check it it's feasible.

Follow it in Taiga: https://tree.taiga.io/project/penpot/issue/1369

**Comment by jcklpe** [comment]
second this

**Comment by niwinz** [comment]
The code button is hidden by default now.
In future we consider adding a specific permission for it.

Thanks for reporting.
