### ISSUE TITLE
Wrong rotation deg values

### ISSUE THREAD

**Issue by girafic** [penpot/penpot#741]
**Describe the bug**
Wrong rotation deg values while using arrow up/arrow down key.

**To Reproduce**
1.  Create a rect shape
2.  Click on rotation input field
3.  Tap on arrow down key
4.  deg value changes from 0 to 358

**Expected behavior**
deg value should changes to 359

**Screenshots**

https://user-images.githubusercontent.com/1187276/110383017-04c07380-805c-11eb-960f-9e1c94de0888.mp4

**Comment by Alotor** [comment]
Nice catch! Will be fixed for next release. Thanks.
