### ISSUE TITLE
Work Sans font need to be updated

### ISSUE THREAD

**Issue by girafic** [penpot/penpot#744]
**Describe the bug**
Incorrect rendering of the letter A. (see screenshot)

![A_Letter_Work_Sans](https://user-images.githubusercontent.com/1187276/110602478-58c77700-8186-11eb-8e32-e6788e22cd49.jpg)

**Comment by elhombretecla** [comment]
Thank you so much for the report @girafic 

We will manage this issue from Taiga
[](https://tree.taiga.io/project/penpot/issue/1410)

**Comment by elhombretecla** [comment]
[https://tree.taiga.io/project/penpot/issue/1410](https://tree.taiga.io/project/penpot/issue/1410)
