### ISSUE TITLE
Cannot select text in comments

### ISSUE THREAD

**Issue by der-On** [penpot/penpot#745]
When in view mode with comment mode enabled I cannot select text within a comment.

**To Reproduce**
1.  Go to 'View mode' by clicking the triangle in the upper right of an open file
2.  Click on 'Comments' to enable comment mode
3.  Open a comment
4.  Try to select text in a comment
5. Text is not selectable

**Expected behavior**
I can select text within comments.

**Desktop:**

-   OS: Ubuntu 20.04 64bit
-   Browser Firefox Developer Edition
-   Version 87.0b7

**Environment:**
self-hosted instance using latest docker image.

-   OS Version: Ubuntu 20.04

Also provide Docker commands or docker-compose file if possible and if proceed.x

-   Docker / Docker-compose Version: Docker version 19.03.11, build 42e35e61f3
-   Image penpotapp/frontend:latest penpotapp/backend:latest

**Comment by elhombretecla** [comment]
Thanks for reporting this!

We will manage this from Taiga, you can follow the progress here :)
[https://tree.taiga.io/project/penpot/issue/1413](https://tree.taiga.io/project/penpot/issue/1413)

**Comment by der-On** [comment]
@elhombretecla Thanks. Should I report new issues in taiga or at github?

**Comment by niwinz** [comment]
@der-On here, **on github**, taiga is for our internal development; it is open, and we link it here for transparency; but only us manages taiga; we expect users report bugs here, on github.

**Comment by der-On** [comment]
@niwinz Thanks for clarifying.
