### ISSUE TITLE
Comments not visible in public link

### ISSUE THREAD

**Issue by adambelis** [penpot/penpot#764]
**Describe the bug**

**To Reproduce**
1.  create ne document
2.  go to  view mode
3.  switch to comment mode and add comment
4.    create link
5. send this link to somebody
6. there is no comment visible in public link

**Expected behavior**
there should be comments visilbe in document

**Screenshots**

https://design.penpot.app/?fbclid=IwAR0sFP0VZgVCFDtxKCURn4gRRsxpY97pvP_j4fgNVZ35PurAoD4hVO_rIsA#/view/9d49b1a0-87f2-11eb-9126-57893f4da933/9d49b1a1-87f2-11eb-9126-57893f4da933?index=0&section=comments
**Desktop (please complete the following information):**

-   OS: win 10
-   Browser chrome
-   Version current 1,2

**Smartphone (please complete the following information):**

-   Device: (e.g. iPhone6)
-   OS: (e.g. iOS8.1)
-   Browser (e.g. stock browser, safari)
-   Version (e.g. 22)

**Environment (please complete the following information):**
Specify if using SAAS (https://design.penpot.app) or self-hosted instance.

If self-hosted instance, add OS and runtime information to help explain your problem.

-   OS Version: (e.g. Ubuntu 16.04)

Also provide Docker commands or docker-compose file if possible and if proceed.x

-   Docker / Docker-compose Version: (e.g. Docker version 18.03.0-ce, build 0520e24)
-   Image (e.g. alpine)

**Frontend Stack Trace (if self-hosted)**

<details>

```

```

</details>

**Backend Stack Trace (if self-hosted)**

<details>

```

```

</details>

**Additional context**

**Comment by myfunnyandy** [comment]
For the moment we do not allow to see comments for users that have no permissions to to do it, which are logged users that are members of the team where the file is. Comments are meant to enable conversations between members of a team right over the designs. So if you want someone to see and use the comments at the view mode you currently need to add him/her as a member of the team.

To allow not logged users to participate in this conversations (read and write) we need to considerate a lot of things about privacy and permissions and we are just not considering to tackle this subject at this moment. However, we take note of your suggestion as we might reconsider this in the future.

You can find a bit more info about the comments at the doc https://help.penpot.app/user-guide/comments/#comments-viewmode

**Comment by adambelis** [comment]
i see I was not sure if that was a bug or feature .. your logic make sance on the other hand  you often share designs outside your team (clients, accounts, designers outside your theme for feedback).
So you can take this as a feature request. Maybe if the future it would be nice to have an option (check box next to  share link) to enable  comments for public links.

**Comment by doctormo** [comment]
Perhaps there's a better space for a "public consultation" which could have different permissions. Allowing the public to see the design is critical to open participation, although commenting can be done on other platforms as they link to penpot for example on GitLab.

**Comment by lol768** [comment]
> To allow not logged users to participate in this conversations (read and write) we need to considerate a lot of things about privacy and permissions and we are just not considering to tackle this subject at this moment. However, we take note of your suggestion as we might reconsider this in the future.

I thought I'd ask if this is still the case a year and a bit on? Currently there's quite a bit of friction involved with signing up and getting to the point of being able to leave (and view!) comments, and I've had to work with colleagues to produce guides for non-technical business-y folks to help them get over these hurdles to be able to participate in the design process.

**Comment by prononext** [comment]
It would be really nice to have the setting to allow public commands from non logged in users. Like this the Design can easily be shared with a customer and he can comment directly without having to log in. Right now only Team Members and/or Logged in Users can comment which is leaving out the client. I suppose its not the way to go, giving every client a login to comment on the work. 

Please make it possible!!! @myfunnyandy
