### ISSUE TITLE
Prepopulate some assets and/or option in the dashboard

### ISSUE THREAD

**Issue by zenny** [penpot/penpot#770]
Wouldn't it be nice to prepopulate some assets from the open-source graphic or make an option to do so in dashboard?

Or did I miss anything? 

:+1:  to the team!

**Comment by elhombretecla** [comment]
Hi @zenny :)

It is already in our roudmap to make a marketplace of assets and design libraries in the future. By the moment you could share files with other users (from view mode) and create your own assets libraries from scratch :)

**Comment by myfunnyandy** [comment]
We've released an in-app module to load templates and libraries in the [1.16 beta release](https://community.penpot.app/t/never-gonna-give-you-up-penpot-1-16-beta-release/1865).
