### ISSUE TITLE
Pressing shift does not keep fixed proportions when creating or resizing a shape 

### ISSUE THREAD

**Issue by fomastich** [penpot/penpot#774]
This could be a feature request, but it is such a basic convention that I will add this as a bug. 
Feel free to label is as an enhancement if necessary.

**Describe the bug**
Pressing shift does not keep fixed proportions when creating or resizing a shape 

**To Reproduce**
1.  Click on Ellipse or Rectangle in the tools panel
2.  click on the main section to create the shape & drag to scale
3.  press shift to constrain proportions 
4.  proportions are not kept

**Expected behavior**
A circle or a square should be visible as long as shift is pressed

**Comment by elhombretecla** [comment]
Hi @fomastich :)

You could follow this issue progress here

[https://tree.taiga.io/project/penpot/us/1388?no-milestone=1](https://tree.taiga.io/project/penpot/us/1388?no-milestone=1)
