### ISSUE TITLE
Selecting an artboard and pressing "Enter" causes an internal error

### ISSUE THREAD

**Issue by fomastich** [penpot/penpot#775]
**Describe the bug**
Selecting an artboard and pressing "Enter" causes an internal error 

**To Reproduce**
1.  Create an Artboard
2.  Select it
3.  Press Enter on your keyboard
4.  See internal error screen

Online version, browser: Chrome

**Comment by elhombretecla** [comment]
Thanks for the report!!!

Track the progress here
[https://tree.taiga.io/project/penpot/issue/1440](https://tree.taiga.io/project/penpot/issue/1440)
