### ISSUE TITLE
path ignored from undo history until closed

### ISSUE THREAD

**Issue by fomastich** [penpot/penpot#776]
**Describe the bug**

**To Reproduce**
1.  Create a rectangle
2.  Click on the path tool
3.  start creating a few points
4.  undo (cmd-z)
5.  the rectangle disappears

**Expected behavior**
I expected to be able to undo each point of the path tool

**Comment by elhombretecla** [comment]
Thanks for the feedback!

You can track this issue here
[https://tree.taiga.io/project/penpot/issue/1442](https://tree.taiga.io/project/penpot/issue/1442)

**Comment by Alotor** [comment]
We've added this feature and will be released with the next release. We're targeting this week or the beginning of next week to upload it into the server. Regards
