### ISSUE TITLE
Magnet is checked, but not enabled when grid is off.

### ISSUE THREAD

**Issue by studiospring** [penpot/penpot#79]
Grid is off in the image below, but the magnet is checked. If I move objects when grid is off, it does not snap to grid.

![magnet](https://cloud.githubusercontent.com/assets/4901306/23744072/06aff1cc-0507-11e7-8d5e-6d51224f749d.jpg)
There are three solutions: 

1. snap to grid even when grid is off.
2. dim and disable magnet (and other grid settings) when grid is off.
3. dim and disable grid settings, on click of grid settings, undim, enable and edit settings and show grid.

Option 3 is the best UX and most work :D. This would require some thought as to how to show that the settings are disabled. The text is so dim already, another visual indicator is required.
As an aside, the "Magnet option" would be better named "Snap", with the checkbox labelled "Snap to grid".

**Comment by niwinz** [comment]
@elhombretecla I need your feedback about this. 

I'm not clearly understand you @studiospring. To put here some context:

- The user may want to have grid enabled without alignment to grid.
- The grid visibility is a flag of workspace and is volatile (not persisted) (need to be activated explicitly on each loaded page)
- The alignment flag is persisted on refreshes.

In general terms we are open to make improvements on this part, inclusive change the current behavior, but we want more clear proposal.

**Comment by studiospring** [comment]
If the "Activate magnet" checkbox is checked, it should mean that objects will snap to the grid _even if the grid is invisible_. Therefore, if objects do not snap to grid when the grid is invisible, then the "Activate magnet" checkbox should have a different state, eg unchecked or dimmed.

If you can accept the above logic, then my three proposals above should make sense. This issue is partly related to #80, since I do not think using a grid as a flag to indicate workspace is sensible. Surely the page name is what indicates workspace?!? I do not understand why grid is related to workspace. Maybe (more) usability testing is required?

Here are all possible combinations:
![combinations](https://cloud.githubusercontent.com/assets/4901306/24173307/476f796a-0ed7-11e7-83c0-14ff2cbeb540.png)

**Comment by elhombretecla** [comment]
I agree with @studiospring on this grid behaviour. Snap to grid should work when Activate magnet is checked. Including if the grid is invisible :)

**Comment by niwinz** [comment]
Will be covered on #80
