### ISSUE TITLE
I can not edit svg

### ISSUE THREAD

**Issue by APattjoshi** [penpot/penpot#797]
**Is your feature request related to a problem? Please describe.**
I want to edit the imported SVG. Ex. I'm always frustrated when (I am changing the location of shapes in SVG and also paths are not editable)

**Describe the solution you'd like**
I would like to edit, move, scale, rotate SVG paths

**Describe alternatives you've considered**
In Figma, it's possible to edit SVG illustrations from other programs.

**Additional context**
I want to move the  basketball and chess boat to the right of the screen but can't 
![image](https://user-images.githubusercontent.com/47391164/112744139-eabee480-8fba-11eb-8b68-2c39e6210b68.png)

**Comment by hirunatan** [comment]
Hi, @APattjoshi. I have good news: this is already done. It will be available in the next release, in one or two weeks.
