### ISSUE TITLE
Picking color is time taking

### ISSUE THREAD

**Issue by APattjoshi** [penpot/penpot#798]
**Describe the bug**
I am unable to pick a color sometimes.

**To Reproduce**
1.  Go to color box
2.  Click on 'color option'
3.  Select 'the color picker'
4.  Hove on the color
5.  Color not visible
6. When clicked on the color the off white color get picked instead of the intended one

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

- OS: (Windows 10)
- Browser (chrome)
- Version (88.0.4324.182 (Official Build) (64-bit)

**Environment (please complete the following information):**
Specify if using SAAS (https://design.penpot.app).

**Additional context**
I am trying to pick a color
![image](https://user-images.githubusercontent.com/47391164/112744279-3f169400-8fbc-11eb-9c75-b3332161b53d.png)

**Comment by Alotor** [comment]
Hi @APattjoshi, 

We're aware that there are some performance issues with the color picker and we've implemented some improvements that we'll publish soon. I'll let you know when these are in production so you can check.

**Comment by niwinz** [comment]
Already live ;)

**Comment by miguelgargallo** [comment]
I have the same issue, is this normal? Am I using the latest version? Version 1.19
