### ISSUE TITLE
Hosted instance registration is broken

### ISSUE THREAD

**Issue by aolko** [penpot/penpot#803]
**Describe the bug**
hosted registration is broken

**To Reproduce**
1. attempt to register
2. fill out the form
3. press **register**
4. get your expectations subverted by a surprise error
5. realise that your profile data got discarded and registration is broken
6. have an existential crisis/depression/panic attack

**Expected behavior**
Registration is successful

**Screenshots**
![image](https://user-images.githubusercontent.com/581458/113039993-f5d36980-91a0-11eb-9fe3-527c5c3df2b0.png)

**Desktop (please complete the following information):**

-   OS: windows 10 20h2
-   Browser chrome 89

**The JS stack trace is:**
```
ui.cljs:293 Internal error:
ui.cljs:294 hint: Ya is not a function
ui.cljs:298 TypeError: Ya is not a function
    at OH.f.send (array.js:584)
    at http.cljs:102
    at r._subscribe (core.cljs:129)
    at r._trySubscribe (Observable.js:35)
    at r.subscribe (Observable.js:30)
    at map.js:10
    at e.<anonymous> (lift.js:15)
    at r.subscribe (Observable.js:27)
    at Object.c.mergeInternals (mergeInternals.js:41)
    at mergeMap.js:18
ui.cljs:299 stack: TypeError: Ya is not a function
    at OH.f.send (https://design.penpot.app/js/shared.cc92e4b….js:2626:232)
    at https://design.penpot.app/js/shared.cc92e4b….js:2637:390
    at r._subscribe (https://design.penpot.app/js/shared.cc92e4b….js:2509:228)
    at r._trySubscribe (https://design.penpot.app/js/shared.cc92e4b….js:542:288)
    at r.subscribe (https://design.penpot.app/js/shared.cc92e4b….js:542:206)
    at https://design.penpot.app/js/shared.cc92e4b….js:661:184
    at e.<anonymous> (https://design.penpot.app/js/shared.cc92e4b….js:545:296)
    at r.subscribe (https://design.penpot.app/js/shared.cc92e4b….js:542:122)
    at Object.c.mergeInternals (https://design.penpot.app/js/shared.cc92e4b….js:676:46)
    at https://design.penpot.app/js/shared.cc92e4b….js:677:263
```

related to #77, yet developer insisted on a new issue

**Comment by niwinz** [comment]
What you mean with "hosted"?  Is this penpot instance is running on your own server using docker instance?

Or this happens on the https://design.penpot.app (I have tried it right now and it works there).

In case you are running a docker instance, can you provide the exact image id you are using, for check if the image is broken.

In the devtools console also shows a complete version number. Something like
![image](https://user-images.githubusercontent.com/843689/113049936-8bbcc380-91a4-11eb-8e40-987deff7f563.png)
please, can you provide it also.

Thanks.

**Comment by aolko** [comment]
By hosted instance i mean **officially hosted publicly available instance**. In this case https://design.penpot.app .

`1.3.0-alpha-17-gcc92e4be`

And nope, still happening. Not an adblock issue.

**Comment by hirunatan** [comment]
Hi @aolko! Did you manage to register in penpot? There was some temporary issues some days ago, but they were solved. And today we have just released a new version. Could you try again, please?

**Comment by aolko** [comment]
Not yet, I'll try later today. Pardon for accidental closure.

**Comment by aolko** [comment]
`1.4.0-alpha-4900-g166fdbd4`

Yes, i've tried it and it reports the same error, including but not limited to, just by visiting the url above.
HTTP is 304.

**Comment by niwinz** [comment]
We don't know how to help you, we all working on penpot with different browsers and different operating sistems and we can't reproduce this error (as far as I understand, you can't enter penpot because of this error... I don't know the reason but seems related to something external to penpot).

Please, try with different browsers, environments; without more info we can't do nothing with this because we are not able to reproduce it in any of the different environments we work on penpot every day.

**Comment by aolko** [comment]
> Please, try with different browsers, environments; without more info we can't do nothing with this because we are not able to reproduce it in any of the different environments we work on penpot every day.

So far yandex.browser (latest) works as well as firefox developer 88.0b8, so it must be edge stable 89.0.774.68's fault

**Comment by niwinz** [comment]
Nice, now knowing that is edge fault, we can research more on this (initially you said is chrome 89)
thanks.

**Comment by aolko** [comment]
> Nice, now knowing that is edge fault, we can research more on this (initially you said is chrome 89)

I have both

**Comment by niwinz** [comment]
revisiting this still unable to reproduce, so close for inactivity.
