### ISSUE TITLE
Registration link is displayed although it was disabled by environment variables.

### ISSUE THREAD

**Issue by ozanyolyapar** [penpot/penpot#805]
**Describe the bug**
Altough PENPOT_REGISTRATION_ENABLED is set to false, the "create an account" link shows up and the page is rendered normally. After giving information and clicking "Create an account", the alert "The registration is currently disabled." is shown.

**To Reproduce**
1.  Go to 'Home' (logged out)
2.  Click on 'Create an account'
3.  Fill the fields
4.  Click on 'Create an account' button
5. Error alert is showing

**Expected behavior**
If PENPOT_REGISTRATION_ENABLED is false, the field "No account yet? Create an account" is invisible.

**Screenshots**
![Screenshot from 2021-03-31 11-58-30](https://user-images.githubusercontent.com/12610841/113126941-78e3d680-9218-11eb-825f-d8acb2b3e1e2.png)

**Desktop (please complete the following information):**

- OS: Fedora 33 Workstation
- Browser google-chrome
- Version 89.0.4389.90

**Environment (please complete the following information):**
Self-hosted on
- OS Version: CentOS 7.9.2009
- Docker version 20.10.0, build 7287ab3
- docker-compose version 1.27.4, build 40524192

**Comment by niwinz** [comment]
Looks similar to #806

**Comment by ozanyolyapar** [comment]
Your [comment](https://github.com/penpot/penpot/issues/806#issuecomment-811091778) in #806 is the definitive solution.
