### ISSUE TITLE
"Sitemap" should be renamed "Pages".

### ISSUE THREAD

**Issue by studiospring** [penpot/penpot#81]
Even if you are planning to show pages as a tree structure, the Sitemap panel should be renamed. Sitemaps are very different things. I guess the icon should also be changed at the same time. The position of the project name coud be improved as well.
Something like this?

![sitemap2](https://cloud.githubusercontent.com/assets/4901306/23746179/1a8bdb22-050f-11e7-9a27-7b566f6cc80e.jpg)

**Comment by niwinz** [comment]
It is pretty reasonable change. Let's wait to the @elhombretecla opinion.
