### ISSUE TITLE
Add OpenID Connect support

### ISSUE THREAD

**Issue by burnoutberni** [penpot/penpot#810]
**Is your feature request related to a problem? Please describe.**
We're considering self-hosting Penpot in my organization to enable volunteers to use templates for sketching various types of content. For that, we'd prefer an onboarding process as simple as possible. One factor is registration/login. We have a [Keycloak](https://www.keycloak.org/) setup running and we'd like people to use their single sign-on user data to log into Penpot.

**Describe the solution you'd like**
There's a standard called [OpenID Connect](https://openid.net/connect/) or OIDC, which is a thin layer on top of OAuth 2.0, which you already support. Basically it allows you to add your own identity providers instead of Google/Github/Gitlab already integrated. I'm not an expert, but as far as I understand, this would be rather easy to implement and would allow organizations like ours to use Penpot much more effectively than before.

**Describe alternatives you've considered**
I know there's a [pretty hacky solution](https://devopstales.github.io/sso/mattermost-keycloak-sso/) for Mattermost that abuses their Gitlab OAuth feature and allows you to connect to OIDC providers of your choice, so probably one could work around this here too.

**Additional context**
I think that's it. Happy to follow up in case there's any open questions.

**Comment by niwinz** [comment]
This is something that i'm already thinking. I don't know OIDC but seems approachable. Additionally, I'm right now the current approach for oauth providers is bothering me, because the code is practically identical and I think it can be done in a more generic way.

**Comment by niwinz** [comment]
@burnoutberni I have some questions.

As far as I understand OIDC is just a oauth2 extension. So I can treat it like oauth2 provider?
If i'm not wrong, i just need to expose a correct configuration for all endpoints or (read them from `https://[base-server-url]/.well-known/openid-configuration`)
the rest of flow is the same, I redirect user to authorization endpoint, the user authenticates, then the user is redirected back to the app with a state and code, and with state and code I obtain token and with token I obtain userinfo.

I have tried setup the keycloak but I was unable to get it running correctly in a reasonable time :S

**Comment by burnoutberni** [comment]
@niwinz As far as I understand, you're correct, but my knowledge is only limited to hooking existing software with an OIDC implementation into our SSO. You probably already found it yourself, but I think this resource could be helpful: https://openidconnect.net/

Can't help you with your Keycloak issues either, but you could use a SaaS identity provider like [Auth0](https://auth0.com/) or [Okta](https://www.okta.com/) for testing.

**Comment by niwinz** [comment]
@burnoutberni thanks, i'm already working on it on my spare time, hope soon will make a MR for it ;)

**Comment by niwinz** [comment]
https://github.com/penpot/penpot/pull/840
Probably will be available in the next release ;)

**Comment by burnoutberni** [comment]
This looks pretty good, thank you very much!

One thing though: Many OIDC clients implement a feature that you can define a specific role that a user needs to have, in order to be able to authenticate. For instance: We currently assign `user_x` the role `wordpress-admin` or `wordpress-author` if we want to give that user admin or author access to our Wordpress blog. All users without this role cannot log into our Wordpress.

It would be great to have that working also for Penpot, especially if you plan to have different user roles in the future.

For this to work, I think, you wouldn't have to change much of your code. I'm not used to reading Clojure, so I have a hard time understanding what's going on, but I see that you have hard-coded the scopes. They should be configurable instead, so we could add "roles" as a scope (here: https://github.com/penpot/penpot/pull/840/files#r613989592).

Additionally, there should be a configuration value to pick a role that is required for users to be authenticated. If empty, this should allow all users, but if not it should be restricted to members of that role.

In any case, thank you for your work. If you could make these changes as well, this would be great.

**Comment by niwinz** [comment]
Interesting, but I probably need some additional hints on this. Because I don't know how roles works.
- Roles are exposed as scopes?
- Or: roles can be obtained using some special scope of your auth provider (example `roles`) and then, the response will come with `roles` attribute which we need to match with some other values on the config?

I need a good way for test it, for be able implement it

**Comment by burnoutberni** [comment]
Yes, your second option is correct. `roles` is another scope that could be added. If that's added to the claim, the provider can then return the set of roles attributed to the user (usually a comma-separated list or an array, but since that's configurable on the provider side, you can deal with it however you like).

This is what a payload could look like:

```
{
  …
  "name"      : "niwinz",
  "email"     : "niwinz@example.com",
  "roles"     : "admin,penpot"
}
```

You would then match the roles with another configurable value (I guess you could also hard-code something like `penpot`, but I think it's preferable to be able to change that).

Is this enough information to get you going? I don't have a test SSO environment running and I can't give you access to our production environment, but I'd gladly test it for you, if that's of any help.

**Comment by niwinz** [comment]
Thanks @burnoutberni that is enough information I think. Seems aproachable, I probably will need to check it once is done, so when I finish it and it is merged I will publish a develop snapshot image with this change for you test it :D

**Comment by niwinz** [comment]
I forgotten to notify, but the roles checking is already implemented https://github.com/penpot/penpot/blob/develop/backend/src/app/http/oauth.clj#L122

You can set the required roles using `PENPOT_OIDC_ROLES_ATTR` & `PENPOT_OIDC_ROLES`

**Comment by burnoutberni** [comment]
Awesome, thank you!

**Comment by iWangJiaxiang** [comment]
Hi @burnoutberni 

I am trying to setup penpot 1.72 with keycloak shipping oidc feature for my organization. But when I try to login, I got the error below after keycloak auth.

![image](https://user-images.githubusercontent.com/19409802/130053697-c0536814-7bcb-41db-88cd-4552c22d82f2.png)

And the backend service showed  me this:

```
[2021-08-19 10:09:57.877] [qtp593788300-34] W app.http.oauth - hint="received incomplete profile info object (please set correct scopes)" info="nil"
[2021-08-19 10:09:57.880] [qtp593788300-34] W app.http.oauth - hint="error on oauth process"
clojure.lang.ExceptionInfo: no user info
        at app.common.exceptions$error.invokeStatic(exceptions.cljc:31) ~[?:?]
        at app.common.exceptions$error.doInvoke(exceptions.cljc:26) ~[?:?]
        at clojure.lang.RestFn.invoke(RestFn.java:512) ~[clojure-1.10.3.jar:?]
        at app.http.oauth$retrieve_info.invokeStatic(oauth.clj:108) ~[?:?]
        at app.http.oauth$retrieve_info.invoke(oauth.clj:97) ~[?:?]
        at app.http.oauth$callback_handler.invokeStatic(oauth.clj:226) ~[?:?]
        at app.http.oauth$callback_handler.invoke(oauth.clj:223) ~[?:?]
        at app.http.oauth$wrap_handler$fn__28496.invoke(oauth.clj:256) ~[?:?]
        at ring.middleware.cookies$wrap_cookies$fn__29359.invoke(cookies.clj:214) ~[?:?]
        at app.http.middleware$wrap_errors$fn__29597.invoke(middleware.clj:126) ~[?:?]
        at app.http.middleware$wrap_parse_request_body$fn__29584.invoke(middleware.clj:57) ~[?:?]
        at ring.middleware.keyword_params$wrap_keyword_params$fn__29405.invoke(keyword_params.clj:53) ~[?:?]
        at ring.middleware.multipart_params$wrap_multipart_params$fn__29537.invoke(multipart_params.clj:171) ~[?:?]
        at ring.middleware.params$wrap_params$fn__29561.invoke(params.clj:67) ~[?:?]
        at app.http.middleware$wrap_format_response_body$fn__29593.invoke(middleware.clj:114) ~[?:?]
        at reitit.ring$ring_handler$fn__31278.invoke(ring.cljc:329) ~[?:?]
        at app.http.middleware$wrap_server_timing$fn__29571.invoke(middleware.clj:27) ~[?:?]
        at clojure.lang.AFn.applyToHelper(AFn.java:154) ~[clojure-1.10.3.jar:?]
        at clojure.lang.AFn.applyTo(AFn.java:144) ~[clojure-1.10.3.jar:?]
        at clojure.lang.AFunction$1.doInvoke(AFunction.java:31) ~[clojure-1.10.3.jar:?]
        at clojure.lang.RestFn.invoke(RestFn.java:408) ~[clojure-1.10.3.jar:?]
        at app.http$router_handler$fn__31845.invoke(http.clj:90) ~[?:?]
        at ring.adapter.jetty9$proxy_handler$fn__31746.invoke(jetty9.clj:54) ~[?:?]
        at ring.adapter.jetty9.proxy$org.eclipse.jetty.server.handler.AbstractHandler$ff19274a.handle(Unknown Source) ~[?:?]
        at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:51) ~[jetty-server-10.0.2.jar:10.0.2]
        at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:171) ~[jetty-server-10.0.2.jar:10.0.2]
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:122) ~[jetty-server-10.0.2.jar:10.0.2]
        at org.eclipse.jetty.server.Server.handle(Server.java:562) ~[jetty-server-10.0.2.jar:10.0.2]
        at org.eclipse.jetty.server.HttpChannel.lambda$handle$0(HttpChannel.java:399) ~[jetty-server-10.0.2.jar:10.0.2]
        at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:656) [jetty-server-10.0.2.jar:10.0.2]
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:391) [jetty-server-10.0.2.jar:10.0.2]
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:284) [jetty-server-10.0.2.jar:10.0.2]
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:319) [jetty-io-10.0.2.jar:10.0.2]
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:100) [jetty-io-10.0.2.jar:10.0.2]
        at org.eclipse.jetty.io.SocketChannelEndPoint$1.run(SocketChannelEndPoint.java:101) [jetty-io-10.0.2.jar:10.0.2]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333) [jetty-util-10.0.2.jar:10.0.2]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310) [jetty-util-10.0.2.jar:10.0.2]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168) [jetty-util-10.0.2.jar:10.0.2]
        at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126) [jetty-util-10.0.2.jar:10.0.2]
        at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:378) [jetty-util-10.0.2.jar:10.0.2]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:894) [jetty-util-10.0.2.jar:10.0.2]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1038) [jetty-util-10.0.2.jar:10.0.2]
        at java.lang.Thread.run(Thread.java:831) [?:?]
```

I don't know what's wrong, but maybe incorrect keycloak configuration.

From this issue it seems you have made it work. Could you please show me your keycloak client configuration?

Thanks!

**Comment by DerLinne** [comment]
@iWangJiaxiang Hi - did you solve your last problem? 

I have the same issue - with one difference: I am returned to the Login Page of Penpot. But the error message in the log is the same. 

When I check keycloak and the generated token for the user info path for example - the needed attributes are in. So I do not know how to solve this.

Thanks!

**Comment by iWangJiaxiang** [comment]
@DerLinne Unfortunatelly, I didn't. I am looking forward to help

**Comment by niwinz** [comment]
This error message on the backend. means that keycloack does not returns correct user information. The problem can be in the scopes or in keycloack...

**Comment by iWangJiaxiang** [comment]
@niwinz Yes, it is.

My keycloak conf works on all the other services but not on **penpot**.

Maybe more claims mapping are required on keycloak side?

A working keycloak configuration example would help a lot.

**Comment by niwinz** [comment]
Keycloack should return `name` and `email` mandatory, if one or other does not exists or is empty, it will not work. So you need to use scopes accordingly in order to make keykloack return an object with this props.

**Comment by iWangJiaxiang** [comment]
According to the code base, the `backend` and ` props`  should be returned as well. How could I setup these claim mappers in sso provider side?

Do you have any working example?

[penpot/oauth.clj at develop · penpot/penpot](https://github.com/penpot/penpot/blob/develop/backend/src/app/http/oauth.clj#L122)

![image](https://user-images.githubusercontent.com/19409802/142166646-453e7704-3390-4dcc-a0d3-c575872a8dd0.png)

**Comment by niwinz** [comment]
The `backend` and `props` are automatically filled:

![image](https://user-images.githubusercontent.com/843689/142167319-d66a4058-8038-4f44-b91d-45a12f1a6ff2.png)

**Comment by niwinz** [comment]
I have tested everything using auth0 service. I was unable to setup keycloak in a reasonable time. But knowing that people have issues, I try to do it ASAP.

**Comment by iWangJiaxiang** [comment]
Thank you!

I can provide my token example for you convinience.

---

Access Token

```json
{
  "exp": 1637139450,
  "iat": 1637139150,
  "jti": "df03ed93-dbbd-4d20-99ea-8f46ea67770e",
  "iss": "https://xxxx",
  "sub": "fc0a8dc2-9393-4cb7-b1ab-ace41c0ba951",
  "typ": "Bearer",
  "azp": "penpot-test",
  "session_state": "022ae2ca-ca79-4155-8e9a-54e5e416d436",
  "acr": "1",
  "realm_access": {
    "roles": [
      "offline_access",
      "assistant",
      "uma_authorization",
      "realm-user-manager"
    ]
  },  
  "scope": "openid profile email",
  "sid": "022ae2ca-ca79-4155-8e9a-54e5e416d436",
  "email_verified": true,
  "gender": "1",
  "name": "xxxx",
  "preferred_username": "xxx",
  "fullname": "xxx",
  "given_name": "xxx",
  "locale": "zh-CN",
  "family_name": "xxxx",
  "email": "xxxxx",
  "username": "xxxx"
}
```

---

ID Token

```json
{
  "exp": 1637139450,
  "iat": 1637139150,
  "auth_time": 0,
  "jti": "a76e2a03-a364-43b1-bd11-83b33d8ee95e",
  "iss": "https://xxxxx",
  "aud": "penpot",
  "sub": "fc0a8dc2-9393-4cb7-b1ab-ace41c0ba951",
  "typ": "ID",
  "azp": "penpot-test",
  "session_state": "f4182da6-11ee-4ba3-9bdb-5df812aecd98",
  "acr": "1",
  "sid": "f4182da6-11ee-4ba3-9bdb-5df812aecd98",
  "email_verified": true,
  "gender": "1",
  "name": "xxx",
  "preferred_username": "xxx",
  "fullname": "xxxx",
  "given_name": "xxx",
  "locale": "zh-CN",
  "family_name": "xxx",
  "email": "xxxx",
  "username": "xxx"
}
```

---

UserInfo Token

```json
{
  "sub": "fc0a8dc2-9393-4cb7-b1ab-ace41c0ba951",
  "email_verified": true,
  "gender": "1",
  "name": "xxx",
  "preferred_username": "xxx",
  "fullname": "xxx",
  "given_name": "xxx",
  "locale": "zh-CN",
  "family_name": "xxx",
  "email": "xxx",
  "username": "xxx"
}
```

**Comment by DerLinne** [comment]
The tokens are looking the same in my case. 

Can there be a problem with the `roles` claim? Because it is nested under realm access? 

If it has to be on top level, that could be mapped.

But as far as I understood from the documentation, the roles are only needed if the ENV Vars for

`PENPOT_OIDC_ROLES_ATTR: "roles"`
`PENPOT_OIDC_ROLES: "admin"`

are set - right?

**Comment by niwinz** [comment]
yep,

BTW, I trying to setup keycloak, I have everything up and running, but can you help me with: when I can found my client_id and client_secret on the keycloak interface...?

**Comment by niwinz** [comment]
Finally, I have been able to configure keycloak successfully and everything works as expected.

This is the unique setting that I have used:
```bash
# IMPORTANT: the ending / on the BASE_URI
export PENPOT_OIDC_BASE_URI="http://keycloak:8080/auth/realms/Penpot/"
export PENPOT_OIDC_CLIENT_ID="test"
export PENPOT_OIDC_CLIENT_SECRET="<secret-key-found-on-credentials-tab-of-client>"
```
The client should be configured as "confidential" in order to get the client secret.
![image](https://user-images.githubusercontent.com/843689/142206361-7cdd0d08-6289-476d-9875-ca97f4a613ba.png)

**Comment by iWangJiaxiang** [comment]
@niwinz Could you send me the token from your kc instance?

By entering "penpot kc client" => "client scopes" => "evaluate" => "choose a user" and click evaluate => "Generated XXX tokens"

![image](https://user-images.githubusercontent.com/19409802/142208342-01fb9cc8-ce30-4469-bd29-2fccf5cc68f4.png)

**Comment by niwinz** [comment]
The access tokens that you are showing me are not the ones you have to use to configure oidc in penpot. They are the user access tokens. You need to configure penpot with client_id, and client_secret.

- you should go to the `clients` tab; 
- create a new client, 
- specify the access type `confidential` on the client settings;
- save client
- now, the credentials tab will appear
- copy the secret from this tab,
- and the client_id is the same as you have specified on creating client

With this setup, it worked for me.

**Comment by DerLinne** [comment]
> his is the unique setting that I have used:
> 
> ```shell
> # IMPORTANT: the ending / on the BASE_URI
> export PENPOT_OIDC_BASE_URI="http://keycloak:8080/auth/realms/Penpot/"
> export PENPOT_OIDC_CLIENT_ID="test"
> export PENPOT_OIDC_CLIENT_SECRET="<secret-key-found-on-credentials-tab-of-client>"
> ```

Did you only specify these three variales? No direct Paths to AUTH, USERINFO and so on?

**Comment by niwinz** [comment]
Yes, specifying the BASE_URI, penpot will be able to discover the final configuration

Which is found on: 
http://keycloak:8080/auth/realms/Penpot/.well-known/openid-configuration

**Comment by DerLinne** [comment]
Argh - the trailing Slash in the URL was the problem in my case, too. 

It did not work directly because my last change contained a copy & paste error :-) Took some time to identify this.

So, it works now! Thanks to all!

**Comment by iWangJiaxiang** [comment]
> The access tokens that you are showing me are not the ones you have to use to configure oidc in penpot. They are the user access tokens. You need to configure penpot with client_id, and client_secret.
> 
> * you should go to the `clients` tab;
> * create a new client,
> * specify the access type `confidential` on the client settings;
> * save client
> * now, the credentials tab will appear
> * copy the secret from this tab,
> * and the client_id is the same as you have specified on creating client
> 
> With this setup, it worked for me.

I have followed your instruction and the issue still happened.

The access/id/userinfo tokens are the infomation returned to penpot. Since you have a working config, I could compare the format difference between our tokens and figure out the reason.

So your evaluation version of tokens are needed mostly. 

Thank you~

**Comment by DerLinne** [comment]
I'll jump in, because our configuration now works too.

I think where to get the Client ID and Client Secret is decribed above. Perhaps it helps to check the client settings regarding the supported Auth Flows and features - so here the frist screenshot about this:

![Bildschirmfoto 2021-11-18 um 08 01 25_edit](https://user-images.githubusercontent.com/48880971/142368142-35edf8e1-73eb-4188-bfe0-b72c52667e54.png)

And here are the tokens:

**Access Tokens**

```json
{
  "exp": 1637219409,
  "iat": 1637219108,
  "jti": "7d1e167d-8c4a-44fa-bb4f-ab4ab1f91115",
  "iss": "https://<server>/auth/realms/<realm>",
  "aud": [
    "<client>",
    "account"
  ],
  "sub": "187dd781-beb9-438d-bde4-2b5a146293d8",
  "typ": "Bearer",
  "azp": "<client>",
  "session_state": "f21d4d67-5d0e-4c66-a4ec-1dc51a3426a0",
  "acr": "1",
  "realm_access": {
    "roles": [
      "default-roles-<realm>",
      "offline_access",
      "uma_authorization"
    ]
  },
  "scope": "openid email profile",
  "sid": "f21d4d67-5d0e-4c66-a4ec-1dc51a4426a0",
  "email_verified": true,
  "roles": [
    "admin",
    "manage-account",
    "manage-account-links",
    "view-profile"
  ],
  "name": "<fullname>",
  "preferred_username": "<email>",
  "locale": "de",
  "given_name": "<firstname>",
  "family_name": "<lastname>",
  "email": "<email>"
}
```


ID Token
```json
{
  "exp": 1637219408,
  "iat": 1637219108,
  "auth_time": 0,
  "jti": "004f1aac-1dc7-42d3-a5e8-e85ea289e198",
  "iss": "https://<server>/auth/realms/<realm>",
  "aud": "<client>",
  "sub": "187dd782-beb9-438d-bde4-2b5a146693d8",
  "typ": "ID",
  "azp": "<client>",
  "session_state": "11321e37-590d-4ac3-bc1c-b16b14ef931d",
  "acr": "1",
  "sid": "33321e39-590d-4ac3-bc1c-b16b14ef931d",
  "email_verified": true,
  "roles": [
    "admin",
    "manage-account",
    "manage-account-links",
    "view-profile"
  ],
  "name": "<fullname>",
  "preferred_username": "<email>",
  "locale": "de",
  "given_name": "<firstname>",
  "family_name": "<lastname>",
  "email": "<email>"
}
```

User Info
```json
{
  "sub": "183dd781-beb9-438d-bde4-2b5a146693d8",
  "email_verified": true,
  "roles": [
    "admin",
    "manage-account",
    "manage-account-links",
    "view-profile"
  ],
  "name": "<fullname>",
  "preferred_username": "<email>",
  "locale": "de",
  "given_name": "<firstname>",
  "family_name": "<lastname>",
  "email": "<email>"
}
```

**Comment by GregLebreton** [comment]
Hi,
We're trying to use OIDC (keycloak) to configure SSO with penpot. We already configured keycloak for nextcloud or other instances.

We configured the endpoints in the config.env and the clients settings in keycloak but when we try to log, penpot doesn't send the request to keycloak and we get a 400 error form penpot.

If someone has a clear walkthrough for a workable configuration, it would be awesome.
(We followed all the pieces of information that you distilled in this thread but it doesn't seems to be good enough).
Thanks

**Comment by iWangJiaxiang** [comment]
Solve it!

Using latest 1.13.7-beta and ref #1802

Add config

```
PENPOT_OIDC_NAME_ATTR=username
```

Then everything works as expected!

**Comment by v3ss0n** [comment]
I had add enable OIDC on both side , but client side seems to be ingoring the flags. NO UI for OIDC login appeared.
on server
```yaml
- PENPOT_FLAGS=enable-registration enable-login-with-oidc enable-login-with-password disable-email-verification enable-smtp enable-prepl-server

```
on client
```
- PENPOT_FLAGS=enable-registration enable-login-with-oidc enable-login-with-password
```
