### ISSUE TITLE
Dragging the canvas in Firefox or Epiphany (Webkit) results in unpredictable canvas movement

### ISSUE THREAD

**Issue by puresick** [penpot/penpot#811]
**Describe the bug**
Dragging the canvas with the mouse (activating via space key and holding down the left mouse button while moving the mouse) results in unpredictable canvas movement. It seems that the selection frame is being rendered/triggered with this interaction.

**To Reproduce**
1. Open Penpot in Firefox   
2. Open new file
(2.5. Add something to canvas to make it more obvious)
3. Hold down <kbd>space</kbd> on your keyboard
4. Hold down <kbd>left mouse button</kbd>
5. Move your mouse
6. Look at the ruler values to visualize the movement if it happens to fast

**Expected behavior**
Dragging the whole page/canvas according to the mouse movement, like it works in chromium-based browsers.

**Screenshots**
This is showing the canvas rulers after trying to drag the canvas. (I would have liked to upload a screen recording, but as for now this is not possible on my current system :( ):
![Screenshot from 2021-04-07 22-59-22](https://user-images.githubusercontent.com/2714266/113933751-40826080-97f5-11eb-9f0b-d0b3ffd4a566.png)

**Desktop (please complete the following information):**

-   OS: Arch Linux, Gnome 40 (Wayland)
-   Browser: Firefox
-   Version: 87.0

**Smartphone (please complete the following information):**

-   Device: n/a
-   OS: n/a
-   Browser n/a
-   Version n/a

**Environment (please complete the following information):**
I am using the SAAS version.

**Additional context**
/

**Comment by Alotor** [comment]
Hi @puresick thanks for the report

I've managed to reproduce it on Epiphany but not on Firefox (I'm using Arch + i3). I'll try to fix it soon but in the meantime you can use the mouse middle button to drag.

**Comment by puresick** [comment]
Weird. What Firefox version did you test it with?
I can reproduce this in the current FF Developer Edition 88.0b9 (64-bit) too.

Maybe #817 will solves this for me in FF aswell (awesome how fast you are working on this!). Can I somewhere check if the SAAS version has been updated, aka see the version number somewhere inside the application?

**Comment by niwinz** [comment]
This fix is merged to develop, and will be available on the next version (1.5.x). You can check the current version running on the devtools console (it is printed).
