### ISSUE TITLE
Set artboard as thumbnail

### ISSUE THREAD

**Issue by tbmatuka** [penpot/penpot#818]
**Is your feature request related to a problem? Please describe.**
Not being able to manually create file thumbnails makes the project files more messy. 

**Describe the solution you'd like**
Basic solution would be ability to mark an artboard as thumbnail in the context menu. If having the thumbnail regenerate on change is a problem, adding a "Regenerate thumbnail" option to the context menu would be perfectly usable. The thumbnail artboard would need to be easily identifiable by an icon next to the artboad name.

**Describe alternatives you've considered**
Other options like choosing the thumbnail artboard by name or uploading an image would be a lot worse for UX and not a lot simpler.

**Additional context**
Figma has this somewhat well implemented (thumbnail aspect ratio is not fixed across screen resolutions), but more importantly they have it well documented: https://help.figma.com/hc/en-us/articles/360038511413-Set-custom-file-thumbnails

**Comment by niwinz** [comment]
Hello @tbmatuka 

Thanks for the suggestion. Right now we render all the page and although it solves the problem, it is not optimal, because pages can become bigger. This solution looks like a good approach. We will take it in consideration.

**Comment by tbmatuka** [comment]
@niwinz if you're already messing with that part of the code, it might be a good idea to limit the area of the page that gets rendered by the automatic thumbnail. I'm 100% sure that someone will manage to create a page big enough to break the rendering :grinning:  I'd start with top left and limit to a size that definitely renders fine.

**Comment by myfunnyandy** [comment]
Added to our backlog, thanks! https://tree.taiga.io/project/penpot/us/1526?no-milestone=1

**Comment by tbmatuka** [comment]
Just tried this one out and it works :smiley: Thank you!
