### ISSUE TITLE
Auto layout like Figma

### ISSUE THREAD

**Issue by mathias-bx** [penpot/penpot#822]
**Is your feature request related to a problem? Please describe.**
When you change the copy of a button (for example), the surrounding box doesn't update.

**Describe the solution you'd like**
A solution like Figma has, Auto layout https://help.figma.com/hc/en-us/articles/360040451373-Create-dynamic-designs-with-Auto-Layout - https://www.figma.com/blog/announcing-auto-layout/

**Describe alternatives you've considered**
No real alternative possible at the moment.

**Additional context**
No additional context

**Comment by myfunnyandy** [comment]
Nice suggestion. For its complexity Auto layout is still a still not considered in our planning. However, in the near future we will add constraint settings that might tackle the problem of managing proportions at resizing groups. You can see the progress here: https://tree.taiga.io/project/penpot/us/1125?milestone=262806

**Comment by jcklpe** [comment]
some update on what's going on: https://community.penpot.app/t/what-are-penpot-plans-for-autolayout/112
