### ISSUE TITLE
Shift alignment like Photoshop & Figma

### ISSUE THREAD

**Issue by mathias-bx** [penpot/penpot#823]
**Is your feature request related to a problem? Please describe.**
When moving elements around the canvas, I want to be sure of the placement of them. Using the shortcut shift forces the element to be moved either vertically or horizontally.

**Describe the solution you'd like**
A solution like photoshop or Figma

**Describe alternatives you've considered**
Looking at the placement guides, but it can easily be useless when you have too many elements on the page

**Additional context**
Here's an example on how it works on Figma
https://user-images.githubusercontent.com/51300014/114274503-8ec27a00-9a16-11eb-8b4b-cb8290152531.mp4

**Comment by myfunnyandy** [comment]
This is already in our plans. I will add you suggestion to the user story to raise the interest https://tree.taiga.io/project/penpot/us/1384?no-milestone=1

**Comment by hirunatan** [comment]
Done. You will see it in the next release.
