### ISSUE TITLE
Brazilian Portuguese language support

### ISSUE THREAD

**Issue by guidimas** [penpot/penpot#824]
**Is your feature request related to an issue? Please describe.**
Nowadays the platform supports several languages, but I noticed that Brazilian Portuguese is not yet one of them.

**Describe the solution you would like**
I think it would be good to add support for the Brazilian Portuguese language, turning the platform even more accessible.
I can help with some translations as well. :smile: 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by myfunnyandy** [comment]
Hi, if you want to collaborate with translations (and we would love that to happen) you can directly add translations to the [translations file](https://github.com/penpot/penpot/blob/develop/frontend/resources/locales.json). We know this process is not as user friendly as it should be, that's why we are planning to use a translation service, but for the moment is what we can do.

If you need more help please let us know, thanks!

**Comment by myfunnyandy** [comment]
Sorry @guidimas, I have recent news: we are already working on integrating [weblate](https://weblate.org/) to easily manage translations and meanwhile we will stop accepting contributions for translations. Once we integrate weblate it would be great if you could help us with brazilian portuguese. 

Thanks for your patience.

**Comment by myfunnyandy** [comment]
Hi again @guidimas. Just let you know that we already have integrated Weblate so translating Penpot is much easier from now on. If you are still interested on contributing adding brazilian portuguese translations (we hope so!) you will first need to have a weblate account (its free) and then we will be able to give you the permissions needed. We left more info about the new translating process at the doc: https://help.penpot.app/contributing-guide/translations/

**Comment by guidimas** [comment]
Hello @myfunnyandy, of course! I've just created my account on weblate. Could you help me with the necessary permissions?

Username: guidimas

Thank you.

**Comment by niwinz** [comment]
Done (I have added you to weblate project), if you found any trouble, just write us.

**Comment by eduardobalbo** [comment]
Hello!
I could also help with the translation, if you need a hand @guidimas, just let me know.
We're planning to use PenPot on our dev group and most of our devs would like to see the project in brazilian-portuguese aswell.

**Comment by guidimas** [comment]
Hello @eduardobalbo, of course! The more help, the better! :smile:

If you still don't have access to the weblate, I recommend reading the following doc: https://help.penpot.app/contributing-guide/translations/

I would suggest opening another issue also requesting access, as this one is already closed.

What do you think @niwinz?
