### ISSUE TITLE
Can't upload Material Design Icon svg any-more

### ISSUE THREAD

**Issue by keunes** [penpot/penpot#826]
**Describe the bug**
Trying to upload an SVG as an asset gives an error: "Seems that this is not a valid image."

**To Reproduce**
Steps to reproduce the behaviour:
1.  Go to materialdesignicons.com
2.  Open an icon and download the svg file (e.g. [Material Design Icons - Cast.zip](https://github.com/penpot/penpot/files/6292102/mdi-cast.zip))
3.  Go to the Assets in PenPot
4.  Click the plus sign and select right file
5. See error

**Expected behaviour**
Icon gets added as asset

**Desktop (please complete the following information):**

-   OS: Ubuntu
-   Browser Firefox
-   Version (e.g. 22)

**Environment (please complete the following information):**
using SAAS (https://design.penpot.app)
Uploading MDI icons used to be possible without problem.

**Comment by myfunnyandy** [comment]
It seems that this specific .svg has a DOCTYPE that makes it fail at uploading. We can not allow doctypes for security reasons. Here is the same icon without doctype: [cast-nodoctype.zip](https://github.com/penpot/penpot/files/6296126/cast-nodoctype.zip)

If it happens again with other icons you can remove the doctype manually or use an SVG prettifier like this one: https://jakearchibald.github.io/svgomg/

**Comment by keunes** [comment]
Hi @myfunnyandy,
Thanks for your reply. Was this changed with the latest update?

I just checked, and none of the Material Design Icons files that I had downloaded from their website before and also had already uploaded to Penpot before are now suddenly failing because of this filetype error. Was security enhanced with the recent release, changing the type of files that can be uploaded?

To be honest feels a bit odd if I'd have to meddle in the code or pull through a converter every single icon that I download from a rather well-known [open-source](https://github.com/Templarian/MaterialDesign) icon database. So it'd be great if some solution (that doesn't compromise security) could be found.

**Comment by niwinz** [comment]
@keunes sorry for the inconvenience, but material design icons comes with the DOCTYPE header that in a standard SVG spec and impl allows any user to place some malicious code and read files from the server where this is parsed. Allowing doctype is a high security risk. Many libraries already comes without it because of obvious reason.

This DOCTYPE does nothing to the icon, and probably the correct approach is opening an issue to the material design and ask for removing it.

In any case, we know that is inconvenient and we already working on a specific solution for this case (remove the DOCTYPE ourselves on incomong SVG's)
Again, sorry for inconvenience and I hope this will be fixed soon.

**Comment by niwinz** [comment]
@keunes a workaround is landed on develop, and will be available on next release; it consists on detecting svg that comes with doctype, and remove the doctype before processing. In any case, the correct way is not use doctype at all.

For reference:
- https://owasp.org/www-community/vulnerabilities/XML_External_Entity_(XXE)_Processing
- https://en.wikipedia.org/wiki/Billion_laughs_attack
- https://quanttype.net/posts/2021-03-13-clojure-xml-and-untrusted-input.html

**Comment by keunes** [comment]
As you might have seen I followed your advice and created an issue at MDI. They said they'd be removing the doctor also.

So that makes a double solution. Thanks!

**Comment by imagoiq** [comment]
Good that it will be fixed in next release! Just for reference, this is also happening with Affinity Designer which export SVG with a Doctype as well.
