### ISSUE TITLE
Edit page & Share link options not available

### ISSUE THREAD

**Issue by maballe** [penpot/penpot#830]
**Describe the bug**

When I select the view mode there is neither share link nor edit page option.

**To Reproduce**

1.  Go to design tap.
2.  Click play icon.
3.  See the artboard in view mode.
4. The edit and share link option don't show up in the top left corner like it used to be before.

**Expected behavior**

Be able to see the edit and share link options.

**Screenshots**

![Screenshot from 2021-04-12 12-05-51](https://user-images.githubusercontent.com/77272294/114380723-ab7fbe80-9b8a-11eb-8c03-bf07cb6dd590.png)

**Desktop (please complete the following information):**

-   OS: Ubuntu 20.04
-   Browser: Firefox
-   Version: 87.0

**Environment (please complete the following information):**
Using SAAS (https://design.penpot.app)

**Comment by myfunnyandy** [comment]
Thanks for reporting it, we'll take a look. You can track the issue [here](https://tree.taiga.io/project/penpot/issue/1524).
