### ISSUE TITLE
Put SVGs added from assets back into a box

### ISSUE THREAD

**Issue by keunes** [penpot/penpot#832]
**Is your feature request related to a problem? Please describe.**
With the new update (1.4.0-alpha) icons that I add from my assets don't show up in a box any-more. That makes it much harder (if not annoying) for me to align them if they don't have the exact same size :/

**Describe the solution you'd like**
Put them back 'in the box' declared in the file.

**Describe alternatives you've considered**
Make it a user preference whether they should be kept in a box or not. Not sure user choice makes sense here, though.

**Additional context**
Previously | Now
![afbeelding](https://user-images.githubusercontent.com/11229646/114465082-eadbf880-9be6-11eb-9056-a981e7eef07d.png) ![afbeelding](https://user-images.githubusercontent.com/11229646/114465252-28408600-9be7-11eb-8538-9c0f13985588.png)

Imagine, for example, that the cast and vertical ellipsis are positioned above/below each-other. I can't left-align them any-more, because that will lead the ellipsis to not visually centre with the cast icon. (Instead, I would first have to left-align, then vertically center them.)

Related to [Taiga 1066](https://tree.taiga.io/project/penpot/us/1066) I reckon?

**Comment by myfunnyandy** [comment]
Hi @keunes, the answer is yes, this change is related to that user story. We've made a lot of improvements to allow import and edit SVGs. We decided not to import the viewbox considering different use cases in which we prioritize ease and flexibility at editing.

We acknowledge the pain in this case and we are thinking on potential solutions. As a suggestion, in the meantime you could use hidden layers to provide the icons the desired area. We've opened a [user story](https://tree.taiga.io/project/penpot/us/1538?no-milestone=1) to work on this.

**Comment by keunes** [comment]
Thanks!

**Comment by myfunnyandy** [comment]
This problem has been solved adding a transparent "base-background" layer that matches the svg viewbox.
