### ISSUE TITLE
Right click brings up default browser menu in certain panels

### ISSUE THREAD

**Issue by hilltopmediadesign** [penpot/penpot#833]
**Describe the bug**
Right clicking still brings up default browser context menu in certain areas. Because of the nature of the app, it's probably best to disable this menu everywhere - as with Figma. Seems minor, but it breaks the "feel" of the app.

**To Reproduce**
In chrome, right click brings up default browser menu :
- Dashboard: everywhere
- Workspace: All blank areas.

**Expected behavior**
Right click does not bring up default browser context menu anywhere in app.

**Comment by myfunnyandy** [comment]
Hi, we can not consider this as a bug as nothing is technically broken and it has its purpose (sometimes is useful to get the browser context menu). However, we understand your preference and we note it as we might reconsider this decision in the future.
