### ISSUE TITLE
blending doesn't work for layers with a shadow applied

### ISSUE THREAD

**Issue by aitormendez** [penpot/penpot#837]
**Describe the bug**
blending doesn't work for layers with a shadow applied

**Screenshots**

![Captura de pantalla 2021-04-13 15 37 32](https://user-images.githubusercontent.com/2788577/114562536-dd6a5100-9c6e-11eb-8dd5-cdbdb1150c14.png)

**Desktop (please complete the following information):**

-   OS: macOS 10.15.7
-   Browser: Firefox 88.0b9 (64-bit)

**Environment (please complete the following information):**
Using SAAS

**Comment by Alotor** [comment]
Thanks for the report. I will be fixed in the next release.

**Comment by myfunnyandy** [comment]
[Issue at taiga](https://tree.taiga.io/project/penpot/issue/1551)
