### ISSUE TITLE
Improve backend error message

### ISSUE THREAD

**Issue by studiospring** [penpot/penpot#84]
If I cannot connect to demo.uxbox.io after I log in, I get the "Unable to connect to backend server" error message. However, my pages load and most of the functionality is available. Therefore, the error message could be more descriptive and tell me what functionality remains and what is lost. Obviously, if my work has been saved is the most important!

Note that this is the same message I get if I cannot login, so there may need to be specific messages, not just 1 generic message.

Finally, some kind of help or suggestions would be nice to troubleshoot.

**Comment by niwinz** [comment]
Yeah, it is normal if you get the same message in the login and in the application when the same problem is happens. I think that is how should be... If you can't login, the text message is different when the error is that your username or password is wrong. But if browser can't connect to the server for some reasons, the "unable to connect to the backend server" message will be displayed.
