### ISSUE TITLE
Smart Value Operations

### ISSUE THREAD

**Issue by Chaphasilor** [penpot/penpot#841]
**Is your feature request related to a problem? Please describe.**

Sometimes, it's easier to specify by *how much* you want to change a value, instead of doing the calculation in your head and typing the result in.

**Describe the solution you'd like**

Add support for "smart" operations on values:

- `<value> -10` decreases the value by 10
- `<value> *1.5` increases the value by 50%, as does `<value> + 50%` 
- `<value> /2` halves the value 
- `<value> *1/3` make the value be 1/3 of the initial value 

These operations should work in most, if not all, fields, where a value can be specified (element sizes, border radii, font sizes, etc.)

**Describe alternatives you've considered**

The only real alternative here is doing the calculations manually, which is often inconvenient.

**Additional context**

This is a feature also present in Figma

**Comment by girafic** [comment]
Would be also good to add direction values (c=center, tl=topLeft, l=left, ...) for width and height, like width=200+10c will scale from left and right .

**Comment by elhombretecla** [comment]
Hi!!! Thanks you so much for your feedback.

We currently have an US for this in our roadmap. We will develop it as soon as we can.

Check it here [https://tree.taiga.io/project/penpot/us/1383?milestone=287365](https://tree.taiga.io/project/penpot/us/1383?milestone=287365)

**Comment by hirunatan** [comment]
@Chaphasilor this is done! We have added some basic math calculations in numeric input fields. It will be available in the next release.

@girafic we are planning a different way of doing this, by adding constraints to the shapes measures. See this US https://tree.taiga.io/project/penpot/us/1125. I'm going to start working on it, and would like it to be available in the following release.
