### ISSUE TITLE
Undocumented(?) User

### ISSUE THREAD

**Issue by lka23** [penpot/penpot#843]
**Describe the bug**
There seems to be an active user "system@uxbox.io" with google-login enabled.

**To Reproduce**
1.  Check table "profile" inside postgres-container:
`docker exec -ti penpot_penpot-postgres_1 psql penpot penpot -c "select * from profile;"`

**Expected behavior**
See only users you created, nothing more, nothing less.
If there were any additional users, I'd expect them to be inactive.

**Environment (please complete the following information):**
Using self-hosted instance via docker-compose.

If self-hosted instance, add OS and runtime information to help explain your problem.

-   OS Version: Linux penpot 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64 GNU/Linux

Also provide Docker commands or docker-compose file if possible and if proceed.x

-   Docker / Docker-compose Version: Docker version 20.10.6, build 370c289

**Additional context**
The user is being created as a part of migration [002-add-profile-tables.sql#L28](https://github.com/penpot/penpot/blob/1.4.1-alpha/backend/src/app/migrations/sql/0002-add-profile-tables.sql#L28)
and will be activated afterwards via  [0024-mod-profile-table.sql#L3](https://github.com/penpot/penpot/blob/1.4.1-alpha/backend/src/app/migrations/sql/0024-mod-profile-table.sql#L3).
The "auth_backend" will be set to "google" via [0046-add-profile-complaint-table.sql#L23](https://github.com/penpot/penpot/blob/1.4.1-alpha/backend/src/app/migrations/sql/0046-add-profile-complaint-table.sql#L23)

What is this user for?

**Comment by niwinz** [comment]
It is legacy. This user and team (probably) born on first days of penpot, we have used it for setup "system" libraries"; but the solution was a bad one and we removed part of the code but forgot about that.
It is marked as google auth, as you have seen on migration 0046, because it does not have password.

I'll create a migration for remove this legacy, thanks for opening this issue.

**Comment by niwinz** [comment]
The fix is already landed on develop and will be released in the next release ;)
