### ISSUE TITLE
Selection indicator too bold

### ISSUE THREAD

**Issue by girafic** [penpot/penpot#845]
Selection indicator is too bold if you select shapes with 1px border.

![selected_vector_shape](https://user-images.githubusercontent.com/1187276/114886421-cc087c80-9e07-11eb-9546-f02e123ecdf0.jpg)

**Comment by myfunnyandy** [comment]
Thanks for reporting this. We opened the issue at taiga: https://tree.taiga.io/project/penpot/issue/1552
