### ISSUE TITLE
Script manage.sh wont work after install

### ISSUE THREAD

**Issue by kico-itexto** [penpot/penpot#854]
**Describe the bug**
After starting the application using Docker the command manage.sh don't accept any parameters

This error occurs after executing the steps described on this link: https://help.penpot.app/technical-guide/getting-started/#start-penpot

**To Reproduce**
1.  Execute the steps described on (https://help.penpot.app/technical-guide/getting-started/#start-penpot) until the section "Configuration"
2. Try to execute `docker exec -ti penpot_penpot-backend_1 ./manage.sh create-profile`

**Expected behavior**
You should be able to pass the options like --email, --password --name, etc. All those parameters are ignored.

Reading the source of the script (https://github.com/penpot/penpot/blob/develop/backend/src/app/cli/manage.clj) we can see that it should work interactively, but it does not.

The only result are the instructions as seen on the print below

**Screenshots**

![image](https://user-images.githubusercontent.com/12414848/115622853-c6f77180-a2ce-11eb-98c4-bf9369d46408.png)

**Desktop (please complete the following information):**

-   OS: Ubuntu 20.04

**Environment (please complete the following information):**

Self hosted

-   OS Version: Ubuntu 20.04

Also provide Docker commands or docker-compose file if possible and if proceed.x

**Additional context**

Found the problem while trying to run it locally.

**Comment by niwinz** [comment]
I confirm that manage.sh in the latest image has a bug. The fix is already landed in `main` branch and the latest docker images are building. I verify it after, and close this issue when is fixed.

Thanks for reporting it.

**Comment by niwinz** [comment]
The latest image is up and has the issue fixed.
