### ISSUE TITLE
Not possible to reach menu of last file in projects overview

### ISSUE THREAD

**Issue by jancborchardt** [penpot/penpot#856]
**Describe the bug**
The menu of the last file in the projects overview opens downwards and is thus inaccessible:

**To Reproduce**
1.  Create at least a few projects
2.  Have one file in each
3.  Try to open the menu of a file which is at the bottom of the viewport
4.  Be unable to actually interact with the options

**Expected behavior**
Some options there:
- The nicest in my view is to have some whitespace at the end of this list by default. That way the last row of entries doesn’t stick to the bottom of the screen but can scroll a bit up towards the middle. This is often done in text editors too.
- The menu could open upwards
- As soon as the menu opens, whitespace can be inserted – worst solution since then you have to realize that it did this, and scroll

**Screenshots**
![impossible to reach menu of last item](https://user-images.githubusercontent.com/925062/115749656-9b8c8980-a397-11eb-814a-4fd6b4d764bb.png)

**Desktop (please complete the following information):**

-   OS: Ubuntu 20.04
-   Browser: Firefox
-   Version: 87

**Environment (please complete the following information):**
Using https://design.penpot.app

**Comment by elhombretecla** [comment]
Thank you again!

We will manage this on Taiga and solve it as soon as possible :)

[https://tree.taiga.io/project/penpot/issue/1605](https://tree.taiga.io/project/penpot/issue/1605)
