### ISSUE TITLE
Menu of a page doesn’t stick to its place when scrolling

### ISSUE THREAD

**Issue by jancborchardt** [penpot/penpot#857]
**Describe the bug**
When you open the menu of a page and then scroll, the menu hovers in place.

**To Reproduce**
1. Create a page
2. Open its menu
3. Scroll

**Expected behavior**
Should probably stick with the 3-dot menu icon button which triggered it?

**Screenshots**
![Menu scrolls away from what it belongs to](https://user-images.githubusercontent.com/925062/115750415-70ef0080-a398-11eb-99f0-70697ac8b45f.png)

**Desktop (please complete the following information):**

-   OS: Ubuntu 20.04
-   Browser: Firefox
-   Version: 87

**Environment (please complete the following information):**
Using https://design.penpot.app

**Comment by elhombretecla** [comment]
You are awesome!!!

New issue on Taiga [https://tree.taiga.io/project/penpot/issue/1606](https://tree.taiga.io/project/penpot/issue/1606)

Thank you so much!
