### ISSUE TITLE
Counter in team settings shows wrong (negative) number

### ISSUE THREAD

**Issue by jancborchardt** [penpot/penpot#859]
**Describe the bug**
Even though we have 3 projects (and 1 drafts section) where 2 projects have 1 file each, in the settings it shows "-1 projects".

**To Reproduce**
No idea to be honest, has always been this way though.

**Expected behavior**
Shows the correct number of projects. ;)

**Screenshots**
![confusing icon](https://user-images.githubusercontent.com/925062/115751293-58331a80-a399-11eb-8ef0-aa63be2f3a8c.png)

**Desktop (please complete the following information):**

-   OS: Ubuntu 20.04
-   Browser: Firefox
-   Version: 87

**Environment (please complete the following information):**
Using https://design.penpot.app

**Comment by violoncelloCH** [comment]
I can reproduce this issue. For me it appears as on the screenshot when first opening the Team Settings. Once I've used the tab "Members" at the top to navigate away and then go back to "Settings" the numbers are displayed correctly.
(From then on it's displayed correctly as long as the values seem to be cached. If I delete the cache I can reproduce the issue again.)

**Comment by elhombretecla** [comment]
We will try to reproduce this and fix it for the next release :)

Taiga issue [https://tree.taiga.io/project/penpot/issue/1608](https://tree.taiga.io/project/penpot/issue/1608)
