### ISSUE TITLE
Confusing icon in team settings

### ISSUE THREAD

**Issue by jancborchardt** [penpot/penpot#860]
**Describe the bug**
Whenever I hover over the team picture, I am confused about the icon which shows. It looks like "Leaving the team" and I get scared.
The icon is even called "exit". ;)

But turns out it is just for uploading a new team picture.
There’s also no other feedback like a tooltip or anything of the sort. I didn’t test this but there likely also is an accessibility issue here.

**To Reproduce**
1. Go to team settings
2. Hover over the team picture

**Expected behavior**
I would expect a simple upload icon instead, like https://fonts.google.com/icons?selected=Material+Icons:upload

**Screenshots**
![confusing icon](https://user-images.githubusercontent.com/925062/115751482-844e9b80-a399-11eb-84e9-45cc61094b56.png)

**Desktop (please complete the following information):**

-   OS: Ubuntu 20.04
-   Browser: Firefox
-   Version: 87

**Environment (please complete the following information):**
Using https://design.penpot.app

**Comment by elhombretecla** [comment]
We will review this with the design team and use a proper icon for this case.

Thank you!

Taiga issue [https://tree.taiga.io/project/penpot/issue/1609](https://tree.taiga.io/project/penpot/issue/1609)

**Comment by myfunnyandy** [comment]
The icon was changed some time ago for something "less scary" ;) 
Thanks for the suggestion!

![image](https://user-images.githubusercontent.com/708713/152952224-834253f7-49b7-4c83-8c3d-10e330e44e65.png)
