### ISSUE TITLE
Ability to set radius for imported images

### ISSUE THREAD

**Issue by jancborchardt** [penpot/penpot#861]
**Is your feature request related to a problem? Please describe.**
So I know it’s possible to crop an imported image using the mask functionality, ref https://github.com/penpot/penpot/issues/692
But something where masking is quite cumbersome is e.g. when you make a mockup and you’d like all avatars to be round and e.g. all file previews to have slightly rounded corners.

**Describe the solution you'd like**
What would be much nicer is to have this corner control for images too:
![image](https://user-images.githubusercontent.com/925062/115753131-2327c780-a39b-11eb-9c7e-3e51c4150899.png)

**Comment by elhombretecla** [comment]
We already have this one on our issues list :) [https://tree.taiga.io/project/penpot/issue/1323](https://tree.taiga.io/project/penpot/issue/1323)

By the moment you can use a mask (shape + border radius) to do this. We know that it is not the same but it is what we have until we solve this enhancement.

Thank you!

**Comment by myfunnyandy** [comment]
Closing the issue as this is done.
