### ISSUE TITLE
Could be easier to invite new team members

### ISSUE THREAD

**Issue by jancborchardt** [penpot/penpot#862]
**Is your feature request related to a problem? Please describe.**
When inviting new team members, you _always_ have to pick the "Role" from the dropdown. Until then, the "Send invitation" button is inactive.

**Describe the solution you'd like**
Since in most cases the role will simply be "Editor", this could be the default.

**Describe alternatives you've considered**
Both roles could even be shown at the same time for now, as a simple grouped radio switch.

**Additional context**
![invite to team role chooser](https://user-images.githubusercontent.com/925062/115753208-3dfa3c00-a39b-11eb-873d-11bcde8d0d10.png)

**Comment by elhombretecla** [comment]
Thank you again for your feedback!!! You are on fire!!!

We will review this and take a decision about it soon. [https://tree.taiga.io/project/penpot/issue/1610](https://tree.taiga.io/project/penpot/issue/1610)

**Comment by jancborchardt** [comment]
Yeeeah this already made my life easier today when adding a new member. :D Thank you!
