### ISSUE TITLE
When linking group of elements via prototype, only the elements of the group are interactive, not the area of the group

### ISSUE THREAD

**Issue by jancborchardt** [penpot/penpot#863]
**Is your feature request related to a problem? Please describe.**
Currently when you link a group of elements via prototype with another artboard, only the _elements_ of the group are interactive, not the area of the group itself. So when you click on the space inbetween, nothing happens.

**Describe the solution you'd like**
It would be nice that if you link a group of elements, the whole bounding box area would be interactive.

**Describe alternatives you've considered**
Not sure on this one – could be cases where you don’t want the area inbetween to be interactive.
But right now I always need to create a rectangle just for making it ready for the prototype, which is sort of redundant.

**Additional context**
The first row is the bounding box of the group, and what I linked for the prototype – and what I would expect is interactive.
In the second row is what is actually interactive – namely each of the elements of the group only, but not the space between.
![interactive](https://user-images.githubusercontent.com/925062/115769860-51fa6980-a3ac-11eb-9804-8f77613e3ccb.png)

**Comment by elhombretecla** [comment]
Thank you very much for your time. Your feedback is really good and very valuable to us :)

We totally agree with your proposal. We will try to improve the prototyping or as soon as possible.

[https://tree.taiga.io/project/penpot/issue/1611](https://tree.taiga.io/project/penpot/issue/1611)

**Comment by hirunatan** [comment]
We have solved it, as you said,  @jancborchardt. It will be available in the next release. Thanks for the suggestion.

**Comment by jancborchardt** [comment]
Yeeeeah, so cool @hirunatan! :) Thanks a lot
