### ISSUE TITLE
can't see uploaded images inside of penpot

### ISSUE THREAD

**Issue by Aicha-cher** [penpot/penpot#867]
Hi Thank you for the great product,

I'm self hosted  penpot deployed using docker,

 everything seems fine the only problem is that i can't see the uploaded images i only see a transparent frame 

thx

**Comment by kico-itexto** [comment]
I'm facing the same problem here

Here's how to reproduce it.

1. Add an image to any penpot page.
2. Upload the file
3. You won't see the file, as shown on the following print in which I selected the image

![image](https://user-images.githubusercontent.com/12414848/115996863-5f377400-a5b7-11eb-97f4-44f3cf5deebc.png)

**Comment by niwinz** [comment]
Probabaly some misconfiguration on the docker compose maybe, I will check it tomorrow, thanks for report it.

**Comment by niwinz** [comment]
Have you changed the configuration related to file storage?

Right now, if start fresh containers using the exactly configuration from the repository and compose file, everything works as expected.

**Comment by Aicha-cher** [comment]
Hi @niwinz i didnt change anything about the storage, the only thing i changed was the db user, and password  while keeping the db url in the default ie PENPOT_DATABASE_URI=postgresql://penpot-postgres/penpot

**Comment by Aicha-cher** [comment]
working now, i had to use this compose file instead of  one that comes with taiga although they are almost identical the only apparent difference i found was this env variable PENPOT_LOCAL_ASSETS_URI=http://penpot-frontend/internal/assets that does come with penpot docker-compose that comes with taiga 
Thanks for the web app and the support

**Comment by niwinz** [comment]
@Aicha-cher thanks!, Looks like we have outdated compose file on taiga repo, I will fix it.

**Comment by dichterD** [comment]
I have the same Problem. I used the official [compose File](https://github.com/penpot/penpot/blob/develop/docker/images/docker-compose.yaml) and just edited: Port, database-name, db-username and password, 

`PENPOT_FLAGS=enable-registration enable-login-with-password disable-email-verification disable-smtp enable-prepl-server disable-secure-session-cookies enable-insecure-register
`
i tried different things but i cant see the assets im uploading.
the frontend log shows several errors uploading and getting the thumbnail

`2023/02/10 11:05:16 [error] 10#10: *18 open() "/opt/data/assets/41/26/75666ed24bb996c05fa94ac94e37" failed (2: No such file or directory), client: XXX.XXX.XXX.XXX, server: _, request: "GET /assets/by-file-media-id/e944452e-77bb-81e0-8002-0a0427721e93/thumbnail HTTP/1.1", upstream: "http://172.27.0.6:6060/assets/by-file-media-id/e944452e-77bb-81e0-8002-0a0427721e93/thumbnail", host: "XXX.XXX.XXX.XXX:7001", referrer: "http://XXX.XXX.XXX.XXX:7001/"
`
Also when Importing e.g. a Designsystem at the main Screen, it imports all colors, Design Elements (everything that seems to go to DB) but doesnt import Graphic/Image Assets. 

Installed on Ubuntu Server VM, using IP Adress. Could this be a Problem because of localhost Config?

**Comment by niwinz** [comment]
Looks unrelated, consider open a separate issue providing the volume configuration, the version, etc.. all information that can be useful for debug the problem,

**Comment by niwinz** [comment]
In any case we still have some issues there, I'm looking on it right now

**Comment by niwinz** [comment]
I think I have fixed the issue, and I'm building new images right now. In any case your issue should be with two steps:

1. Ensure you have correct mount point on backend (on the compose file, it was incorrectly set, already fixed on the main branch); It should be **`/opt/data/assets`** and not `/opt/penpot/assets`.
2. Fix the permissions that are incorrectly set and that I'm currently working to fix with:

```
docker exec -u 0 penpot-backend_1 chown -R penpot:penpot /opt/data
```

where the penpot-backend_1 is the container name.

**Comment by kobimx** [comment]
Had the same issue but also had to modify the frontend mount point and PENPOT_STORAGE_ASSETS_FS_DIRECTORY env var to fix it
This seems like big a breaking change that should be mentioned somewhere more clearly

**Comment by niwinz** [comment]
I have reverted it to the previous value, so there should be no breaking changes for now. If you have modified the that value, can you share it? maybe we still have issues and this may help us

**Comment by niwinz** [comment]
It is true that the changes we had made were not entirely correct and you are right about it, and instead of forcing everyone to change we preferred to revert the change but even so, it was not without its problems.

**Comment by kobimx** [comment]
Yeah i meant that i was upgrading from the old docker-compose file that still had `/opt/penpot/assets` in `PENPOT_STORAGE_ASSETS_FS_DIRECTORY`, frontend mount point and backend mount point

Changing those to `/opt/data/assets` fixed the asset issues on 1.17-1 for me that's why i said that it should be a bit more clear. If someone is upgrading and doesn't check the new docker compose file it can miss it easly

**Comment by niwinz** [comment]
The `/opt/penpot/assets` mount point existed for a very little period of time, that was the breaking change. Before 1.17.0 the default mount point was `/opt/data...` and as the change has turned to be problematic we reverted to /opt/data

Sorry for any possible confusion this may have caused.

**Comment by kobimx** [comment]
Oh i see i was already on the breaking change version of the compose file then, a double reverse kind of situation 😁
No problem then! Hoping someone will find this useful if they encounter the same issue

**Comment by dichterD** [comment]
i removed all containers and used the newest docker compose - now it works (without changing any permissions). i can't believe that i have overseen this little "penpot" instead of "data". thank you. i will test now with some colleges. This is awesome work.

**Comment by hsiong** [comment]
> The `/opt/penpot/assets` mount point existed for a very little period of time, that was the breaking change. Before 1.17.0 the default mount point was `/opt/data...` and as the change has turned to be problematic we reverted to /opt/data
> 
> Sorry for any possible confusion this may have caused.

My penpot version is 1.17.0. The penpot works fine finally while uploading image, after i changed the mount point to `/opt/penpot/assets`

Truely, thanks a lot

**Comment by FriesI23** [comment]
> I think I have fixed the issue, and I'm building new images right now. In any case your issue should be with two steps:
> 
>     1. Ensure you have correct mount point on backend (on the compose file, it was incorrectly set, already fixed on the main branch); It should be **`/opt/data/assets`** and not `/opt/penpot/assets`.
> 
>     2. Fix the permissions that are incorrectly set and that I'm currently working to fix with:
> 
> 
> ```
> docker exec -u 0 penpot-backend_1 chown -R penpot:penpot /opt/data
> ```
> 
> where the penpot-backend_1 is the container name.

Only fix user and group can fix the upload problem, but images and thumbnails do not display, and backend log shows 403 error.

```log
2024/10/17 07:03:12 [error] 10#10: *152 open() "/opt/data/assets/7d/ea/1988448945ecbd56a8080d918f38.gz" failed (13: Permission denied), client: 172.24.0.4, server: _, request: "GET /assets/by-file-media-id/bdff0560-2584-8181-8005-2195c595fa15 HTTP/1.1", upstream: "http://172.24.0.6:6060/assets/by-file-media-id/bdff0560-2584-8181-8005-2195c595fa15", host: "my.pentpot.domain:25443"
2024/10/17 07:03:12 [error] 10#10: *152 open() "/opt/data/assets/7d/ea/1988448945ecbd56a8080d918f38" failed (13: Permission denied), client: 172.24.0.4, server: _, request: "GET /assets/by-file-media-id/bdff0560-2584-8181-8005-2195c595fa15 HTTP/1.1", upstream: "http://172.24.0.6:6060/assets/by-file-media-id/bdff0560-2584-8181-8005-2195c595fa15", host: "my.pentpot.domain:25443"
172.24.0.4 - - [17/Oct/2024:07:03:12 +0000] "GET /assets/by-file-media-id/bdff0560-2584-8181-8005-2195c595fa15 HTTP/1.1" 403 117 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:131.0) Gecko/20100101 Firefox/131.0"
```

```shell
# /opt/
drwxr-xr-x 1 penpot penpot 4096 Oct  1 09:06 data

# /opt/data/assets/
drwxr-x---+ 1 penpot penpot  4 Oct 16 14:19 f1
```

~It seems `750` is not enough for `/opt/data/assets` and it's child dirs. Changing to `755` fixes this problem.~

Found problem,  the backend container uses the `penpor` user to start service, while frontend container uses `www-data`  to start Nginx.  `www-data` user doesn't have permission to access `/opt/data/assets/xxx`.

```shell
getfacl assets/fe
# file: fe
# owner: penpot
# group: penpot
user::rwx
group::rwx                      #effective:r-x
group:penpot:r-x
mask::r-x
other::---
default:user::rwx
default:group::rwx
default:group:penpot:r-x
default:mask::rwx
default:other::---
```

Thus, granting `read` and `execute` permissions to `www-data` can fix this issue. Container doesn't pre-install ACL; it needs to be executed on the host/

```shell
# www-data id=33
setfacl -R -d -m g:www-data:r-x /path/where/your/assets/mounted
setfacl -R -m g:www-data:r-x  /path/where/your/assets/mounted

$ getfacl /path/where/your/assets/mounted
# file: fe
# owner: penpot
# group: penpot
user::rwx
group::rwx                      #effective:r-x
group:www-data:r-x
group:penpot:r-x
mask::r-x
other::---
default:user::rwx
default:group::rwx
default:group:www-data:r-x
default:group:penpot:r-x
default:mask::rwx
default:other::---
```
