### ISSUE TITLE
the penpot instance stop working 

### ISSUE THREAD

**Issue by Aicha-cher** [penpot/penpot#873]
Hi, 
I have a self-hosted dockerized penpot that was working fine intill this morning when i start to have the following error 

ps: no errors in the containers  log 
![image](https://user-images.githubusercontent.com/47347896/116252991-5ccc4a00-a770-11eb-811b-e251f16f85e7.png)

**Comment by niwinz** [comment]
Unfortunately @Aicha-cher, without more info, there are very little that I can do/guess what happens.
- All docker containers are up and running?
- Browser DevTools shows errors, or logs bad requests (HTTP 500 errors).
- Containers logs something relevant?

Keep in mind that without some information it is practically impossible to know what may be happening.

**Comment by Aicha-cher** [comment]
@niwinz  sorry for the post missing some details,i didn't know where to look since 

- the docker containers all are fup and running without any relevant log  except the reddis that have a warning : ` WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.`

- Firefox was complaining about Mixed content since i was serving the app over ssl, i solved by temporally serving it instead over http  even thogh the problem wasnt solved instead error 502 raised

**Comment by niwinz** [comment]
So you can confirm that you getting 502 requests?, maybe a screenshot of the request  on the devtools. 

502 errors means that some container is not running...

**Comment by Aicha-cher** [comment]
sorry for the delay , here is the error this is with access over https , btw the containers still running and healthy 

![image](https://user-images.githubusercontent.com/47347896/116551328-1efa2d80-a8f8-11eb-853f-610aa446729d.png)

**Comment by niwinz** [comment]
Looks like some configuration issue, because the internal http error marks the connection as offline. And the browser  blocks loading mixed content. Are you serving it under HTTPS?, in this case you probably need to update the `PUBLIC_URI` on the config.env file to point a correct https url; and then, restart the containers.

**Comment by Aicha-cher** [comment]
yes i am serving it under https ,and behind a reverse proxy. I tried with PUBLIC_URI pointing to the https , but still the same issue, what i don't understand is why i have an error now, everything was working perfectly with the same stack :(

**Comment by niwinz** [comment]
I will check tomorrow if setting PENPOT_PUBLIC_URI has some effect or if it has some bugs. 

In any case, there are no doubts that the problem is related to how the app is served (HTTPS but issues requests on HTTP).

**Comment by niwinz** [comment]
I have checked, and the config is correctly handled. Please, make sure you have `PENPOT_PUBLIC_URI` in the config.env or on docker-compose.yaml file properly set for both backend and frontend services. The devtools error clearly says that this config is not properly set to the correct value.
