### ISSUE TITLE
Predefined shapes/ "widget libraries"

### ISSUE THREAD

**Issue by jdittrich** [penpot/penpot#88]
**Story:** As a designer, I like to quickly use recurring elements. 
**Problem:** Currently, I can only use shapes and need to use them to compose more complex elements which adjustment is also complex because I need to dig in nested structures.
**Possible Solution**: Allow to add predefined shapes with the possibility to adjust text and possibly adjust basic parameters.

Example solutions: 
* Axure widgets
* [Quick Mockup](https://jdittrich.github.io/quickMockup/)

**Comment by niwinz** [comment]
Thanks @jdittrich 

That is on our plans :D

**Comment by jdittrich** [comment]
Great – if there is any need, I can support as UX Designer, some JavaScript/HTML/CSS, and my knowledge of how libreoffice and draw.io (latter is open source, too) solve (or not solve…) custom widgets/shapes :)
