### ISSUE TITLE
Related instance copies

### ISSUE THREAD

**Issue by grivasgervilla** [penpot/penpot#881]
Hi,

first of all many thanks for this awesome project :smiley: , I think that I will use it to design or my projects. I have a suggestion to increase the productivity of this tool.

Let's image that I have two artboards _A1_ and _A2_, _A2_ is a copy of _A1_, because I use _A1_ and _A2_ to represent a transition in my app. Imagine that there is a button B1 in _A1_, and the corresponding copy of B1, B2, in _A2_. B1 and B2 are instances of a main component *B*.

If I modify a colour or dimension of B1, in order to maintain consistency in my transition, I should make the same changes in B2. I could use the option `Update main component`. However, this would modify other instances of the component *B* that I may have in my project.

On the other hand, I could create a new component, *newB*, from B1, so B1 and B2 are now instances of the component *newB*, and now the option `Update main component` will have the desired effect.

I think that this option is not efficient, because we are not interested in reuse the component *newB* to create other copies of it, we only want consistency between B1 and B2. From my point of view, it does not make sense to create a new component each time that we want to maintain consistency between two related instances.

My proposed solution is to make all the copies of a certain instance linked between them, such that when one of them is changed, the rest of the linked copies change. In addition, we could add a new option `Unlink copy`, to unlink a copy from the rest of copies, so the changes made on the unlinked copy do not have an effect on the rest of the copies, and vice-versa.

The process could be described as follows, for a given component *B*, as explained before. I will show the groups of linked copies and I will use different emojis to represent the effect of the changes on these copies. Let's assume that the basic form of the main component is :red_circle: then.

1. Create a new instance of *B* -> B1:
[B1 :red_circle:]
2. Create a new instance of *B* -> B2:
[B1 :red_circle:] [B2 :red_circle:]
3. Create a copy of B1 -> B3:
[B1 :red_circle: B3 :red_circle:] [B2 :red_circle:]
4. Create a copy of B1 or B3 -> B4:
[B1 :red_circle: B3 :red_circle: B4 :red_circle: ] [B2 :red_circle:]
5. Change the color of B1 (or B3 or B4) to blue:
[B1 :large_blue_circle:  B3 :large_blue_circle: B4 :large_blue_circle:] [B2 :red_circle:]
6. Unlink B3 from the rest of copies:
[B1 :large_blue_circle:  B4 :large_blue_circle:] [B2 :red_circle:] [B3 :large_blue_circle:]
7. Change the colour of B3 to green:
[B1 :large_blue_circle:  B4 :large_blue_circle:] [B2 :red_circle:] [B3 :green_circle:]
8. Change the colour of B4 (or B1) to white:
[B1 :white_circle:  B4 :white_circle:] [B2 :red_circle:] [B3 :green_circle:]

I think that this would improve the use of Penpot. I hope this suggestion to be useful for you. Many thanks for your time.

Regards.

**Comment by hirunatan** [comment]
Hello @Griger. Thanks for your suggestion. It's a possibility that we didn't think of, but it's an interesting possibility.

It's not trivial, on the other hand. We have currently scheduled other advances in the components system, such as size constraints and component variants, that are also important. We have created a user story to track this idea, and will be priorizing it as we advance with the project.

https://tree.taiga.io/project/penpot/us/1627

**Comment by jdittrich** [comment]
The difficulty seems to be that the behavior of the style overwrites will depend on the history of what got copied from what. Which means that the effects of an overwrite will be hard to predict and might not be noted until much later.

**Comment by hirunatan** [comment]
In the way we think this could be done, this would not be a problem. I imagine a system in that all the related instances are in fact the same object. So when you change any of them, all of them reflect the change immediately, independently of the order you created the copies.

This sould be enough for some of your use cases. More elaborated cases perhaps may be carried on with component instances that are in term components.

I don't think that the full solution you describe is feasible, mainly as you say because of the complexity of knowing what instance is related to what.
