### ISSUE TITLE
Ctrl + B does not work as shortcut for toggling text boldness

### ISSUE THREAD

**Issue by jancborchardt** [penpot/penpot#886]
**Is your feature request related to a problem? Please describe.**
When selecting text, the common shortcut `Ctrl + B` to make the text bold does not work.

**Describe the solution you'd like**
It would be nice if `Ctrl + B` could be used to toggle bold text on and off, depending on if the selected text is bold or not.

**Comment by elhombretecla** [comment]
Hi @jancborchardt !!!

We wil manage this enhancement as soon as we can. Thank you for your feedback :)

Track it at Taiga [https://tree.taiga.io/project/penpot/issue/1628](https://tree.taiga.io/project/penpot/issue/1628)

**Comment by pabloalba** [comment]
Fixed :)
