### ISSUE TITLE
Accessibility: Interactive area of buttons in the right sidebar is too small

### ISSUE THREAD

**Issue by jancborchardt** [penpot/penpot#888]
**Describe the bug**
You have to be too exact to click/tap on the actions in the right sidebar, for example the text alignment options. They are each only 20×20px in size whereas the recommendation is 44×44px.

**To Reproduce**
1. Work on some text
2. Open the sidebar to change some details
3. Miss hitting the button, e.g. click inbetween 2 of the buttons and nothing happens

**Expected behavior**
In this case there’s 8px of margin to either side of the actions. Instead of having this margin, why not increase the interactive area to the button so it spans that area? That way it would already be much larger: 28×28px – while the visuals do not change at all. :)

**Screenshots**
![Small clickable area](https://user-images.githubusercontent.com/925062/116713501-25aaa280-a9d5-11eb-9784-15a1d25aa909.png)

**Comment by elhombretecla** [comment]
Thanks for your feedback! We will review this interaction area and study your proposal :)

Taiga issue [https://tree.taiga.io/project/penpot/issue/1629](https://tree.taiga.io/project/penpot/issue/1629)

**Comment by claragvinola** [comment]
With our new UI we've increased our clicking area. You can try it :)
