### ISSUE TITLE
Help setting it up and running

### ISSUE THREAD

**Issue by pedrozamuner** [penpot/penpot#89]
Hey guys, I've tested UXBOX online and wanted to run it on my machine but was not able to do so.

My host: Debian GNU/Linux 8.8 (jessie)
Docker version 17.03.1-ce, build c6d412e

To get uxbox I run:
git clone https://github.com/uxbox/uxbox.git uxbox
So I got the revision 43f3c43

I run manage.sh script as root.
The build process took a few moments but responds that build was successful.
Then, when I run manage.sh run I got the following

Screen 0: Gulp Failure
![gulp](https://cloud.githubusercontent.com/assets/1319295/26788835/d8069cea-49e4-11e7-8146-54e836e23868.png)

Screen 1: Fightwheel Failure
![figwheel](https://cloud.githubusercontent.com/assets/1319295/26788910/14a61040-49e5-11e7-9d13-ac4efd714187.png)

Screen 2: Backend Failure
![backend](https://cloud.githubusercontent.com/assets/1319295/26788953/2d3f8276-49e5-11e7-8767-3d39578013e4.png)

Then, I managed to run the backend with:
sudo ./scripts/lein repl

It did not work without sudo.

![backend_running](https://cloud.githubusercontent.com/assets/1319295/26789945/53bb7c5e-49e8-11e7-93b8-5006ddba9d1c.png)

I run docker container ls to check which port to connect
![docker_running](https://cloud.githubusercontent.com/assets/1319295/26789975/78b4da50-49e8-11e7-816e-9969acb6308d.png)

I tried to connect to my host on the given ports but got no response.

Is the backend really running?
Any ideas?

**Comment by photonsphere-org** [comment]
I also had that error and fixed it by adding python to the list of installed packages (in the Dockerfile) --which is apparently required somewhere and probably no longer installed as a default-- and rebuilding the UXBOX Docker container. 

You can also install it manually in your UXBOX Docker container (via `apt-get install python`) but in that case you'll need to also manually remove the ~/uxbox/node_modules folder and re-run `npm install` and subsequently `npm run watch`.

Also see: [UXBOX source code browsing with Emacs+Cider](http://www.photonsphere.org/posts-output/2018-03-12-uxbox-emacs-cider/).

Alternatively you can use this Dockerfile (which is based on Debian Stretch instead of Ubuntu):

```
FROM debian
MAINTAINER Andrey Antukh <niwi@niwi.nz>

RUN apt-get update && \
    apt-get install -yq locales ca-certificates wget sed gnupg gnupg2 && \
    rm -rf /var/lib/apt/lists/*
RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
RUN locale-gen && update-locale LANG=en_US.UTF-8 LC_ALL=C.UTF-8
ENV LANG en_US.UTF-8
ENV LC_ALL C.UTF-8

RUN sed -ie 's# main# main contrib#' /etc/apt/sources.list

RUN apt-get update -yq &&  \
    apt-get install -yq bash git tmux vim openjdk-8-jdk rlwrap build-essential \
                        postgresql-9.6 postgresql-contrib-9.6 imagemagick webp \
                        sudo python imagemagick

RUN mkdir -p /etc/resolvconf/resolv.conf.d
RUN echo "nameserver 8.8.8.8" > /etc/resolvconf/resolv.conf.d/tail

RUN useradd -m -g users -s /bin/bash uxbox
RUN passwd uxbox -d
RUN echo "uxbox ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

COPY files/pg_hba.conf /etc/postgresql/9.6/main/pg_hba.conf
# COPY files/postgresql.conf /etc/postgresql/9.5/main/postgresql.conf
COPY files/bashrc /root/.bashrc
COPY files/vimrc /root/.vimrc

RUN /etc/init.d/postgresql start \
    && createuser -U postgres -sl uxbox \
    && createdb -U uxbox uxbox \
    && createdb -U uxbox test \
    && /etc/init.d/postgresql stop

EXPOSE 3449
EXPOSE 6060
EXPOSE 9090

USER uxbox
WORKDIR /home/uxbox

RUN git clone https://github.com/creationix/nvm.git .nvm
RUN bash -c "source .nvm/nvm.sh && nvm install v7.7.1"
RUN bash -c "source .nvm/nvm.sh && nvm alias default v7.7.1"

COPY files/lein /home/uxbox/.local/bin/lein
RUN bash -c "/home/uxbox/.local/bin/lein version"

COPY files/bashrc /home/uxbox/.bashrc
COPY files/vimrc /home/uxbox/.vimrc
COPY files/start.sh /home/uxbox/.start.sh
COPY files/tmux.conf /home/uxbox/.tmux.conf

CMD /home/uxbox/.start.sh
```

**Comment by leuch3rd** [comment]
If anyone else is having problems getting this to run on Ubuntu 16/18, go into the Dockerfile and add 'RUN sudo chown uxbox -R /home/uxbox' below the line 'RUN useradd -m -g users -s /bin/bash uxbox'

Then run './manage build && ./manage run'  
If you already created the docker images, remove them first.

Hope this helps someone!
