### ISSUE TITLE
Label of text layer could automatically be that of the text inside it

### ISSUE THREAD

**Issue by jancborchardt** [penpot/penpot#890]
**Is your feature request related to a problem? Please describe.**
Currently you always need to manually change the title of a text layer. In practice, this basically means typing text twice, because why would you give the layer a different name than what the text is in it? ;)

The current label "Text-1" etc is very generic:
![Text layer titles could be more automatically useful](https://user-images.githubusercontent.com/925062/116715385-f39a4000-a9d6-11eb-8d17-23414f3c3fef.png)

**Describe the solution you'd like**
The label of the text layer could just be the text in it, and change as you type – just like GIMP does it:
![GIMP automatic text label](https://user-images.githubusercontent.com/925062/116715475-0b71c400-a9d7-11eb-94cd-ad1f70b75fd3.png)

**Comment by elhombretecla** [comment]
This is good :) We will see how to solve it!

Taiga enhancement [https://tree.taiga.io/project/penpot/issue/1631](https://tree.taiga.io/project/penpot/issue/1631)
