### ISSUE TITLE
components from library not sycned

### ISSUE THREAD

**Issue by FlorianLudwig** [penpot/penpot#891]
**Describe the bug**

**To Reproduce**
1. create a copy of the "design system", name it "test system"
2. create a second new file "design"
3. add "test system" as library to "design"
4.  edit some compnent in "test system"
5. open "design" again
6. A popup pop up asking if the shared library should be synced -> select yes

**Expected behavior**

1. The component library should be updated
2. Components already inserted should be updated

Neither happen

**Comment by niwinz** [comment]
Hi @FlorianLudwig 

I tried to reproduce the exactly steps with a new files and with the penpot design system file. But everything worked as expected.
Can be a possibility that you have updated/modified component on the wrong library file?

For find the issue we need a deterministically way to reproduce the problem, and after my tests everything worked as expected.

In any case, thank you very much for taking time to report it.

**Comment by niwinz** [comment]
Closed for inactivity.
