### ISSUE TITLE
UX detail: ability to paste full hexadecimal color in color input

### ISSUE THREAD

**Issue by imagoiq** [penpot/penpot#894]
**Is your feature request related to a problem? Please describe.**
As a newbie and with my first trial, I tried to paste a "full" hexadecimal color with a # inside the number input for color (right input under "Couleur de fond du canvas" on the screenshot). It didn't work and didn't display any errors. I thought that I hadn't well copied the hexadecimal color at first. I found out later that I could click on the color button which display a popover with different input and paste the full hexadecimal there. 
![Screenshot 2021-05-02 at 17-53-52 Penpot Design Freedom for Teams](https://user-images.githubusercontent.com/12294151/116819254-9259a480-ab6f-11eb-85f1-56a17a037b70.png)
**Describe the solution you'd like**
Ability to also paste full colors hexadecimal in the displayed input color fields and that a function parse the string and remove the # for me without needing to click one more time to display the popover.

**Comment by niwinz** [comment]
Thansk @imagoiq, i will create an [internal enhancement for it](https://tree.taiga.io/project/penpot/issue/1646).

**Comment by hirunatan** [comment]
This is already done, but forgot to close it...
