### ISSUE TITLE
Group is not getting aligned as per the element inside

### ISSUE THREAD

**Issue by APattjoshi** [penpot/penpot#895]
**Describe the bug**
If the text element is inside the group and the length of the text is changed then the alignment is getting off.

**To Reproduce**
1.  Go to the text where two items are in the group
2.  Click on text to edit
3.  Change the length of the text to more than what it is
4.  Align the text to the artboard
5. The issue will be that alignment will be exceeding the group bounding box
6. If you will come out of the group and realign then the alignment will happen as per the group bounding box and not as per the length of the group elements.

**Expected behavior**
The group length should be the same as the bigger element inside it.

**Screenshots**
![image](https://user-images.githubusercontent.com/47391164/116820525-4c163c80-ab93-11eb-8621-1e73f8245557.png)

**Desktop (please complete the following information):**

-  OS: (Windows 10)
-  Browser (chrome)
-  Version (88.0.4324.182 (Official Build) (64-bit)

**Environment (please complete the following information):**
https://design.penpot.app

**Additional context**
I had to ungroup and regroup again to solve this issue.

**Comment by myfunnyandy** [comment]
Thanks for the report @APattjoshi. We will track [the issue at Taiga](https://tree.taiga.io/project/penpot/issue/1647).

**Comment by niwinz** [comment]
should be fixed in the latest release
