### ISSUE TITLE
Can't multi-select and edit vector nodes

### ISSUE THREAD

**Issue by APattjoshi** [penpot/penpot#896]
**Describe the bug**
I am unable to select more than one node to transform a shape.

**To Reproduce**
1.  Double click to edit a vector shape
2.  Click on one node
3.  press shift or ctrl to click one more node
4.  unable to select more than one node

**Expected behavior**
Able to select more than one node for the purpose of editing the shape

**Screenshots**
![image](https://user-images.githubusercontent.com/47391164/116838888-b65bcb00-abed-11eb-8ffb-6bde7be2ecbc.png)

**Desktop (please complete the following information):**

-  OS: (Windows 10)
-  Browser (chrome)
-  Version (88.0.4324.182 (Official Build) (64-bit)

**Environment (please complete the following information):**
https://design.penpot.app

**Additional context**
Controlling or editing SVG is still an issue with penpot

**Comment by niwinz** [comment]
Hi @APattjoshi 

This is not a bug, the current path edition is a MVP, and does not has many features. The next release comes with many improvements.

In any case thank you for taking time to report this.
