### ISSUE TITLE
Artboards not visible in edit mode on Firefox

### ISSUE THREAD

**Issue by nimishavijay** [penpot/penpot#899]
**Describe the bug**
Artboards and their contents are not visible in the workspace and the layers panel in Firefox (works fine in Chrome).
They can be selected and moved around. On adding content into the artboard, the content disappears as well, and after that the content can't be selected. However, it's all visible properly in view mode.

**To Reproduce**
It's always been this way, so I guess just create an artboard.

**Expected behavior**
Artboards and their contents should be visible properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/52440189/116911202-29a02400-ac64-11eb-8ce7-b235af641c9c.png)
On Firefox

![image](https://user-images.githubusercontent.com/52440189/116911157-19884480-ac64-11eb-9fd2-4fe374336f36.png)
On Chrome (expected)

**Desktop:**
-   OS: Ubuntu 18.04
-   Browser: Firefox
-   Version: 88

**Environment:**
SAAS (https://design.penpot.app)

**Comment by niwinz** [comment]
Hi @nimisha-vijay 

First of all, thanks for reporting it.

Just to confirm; when you create a new artboard, you see it correctly on drawing it, but once you finished drawing it, it becomes invisible? It also does not appears on the layers sidebar?

**Comment by nimishavijay** [comment]
Well, the outline is visible while drawing, but it is not filled (artboards would be filled by default). It looks kind of like I'm creating a transparent artboard.
None of the artboards are visible in the layers sidebar.

**Comment by niwinz** [comment]
Very strange, we need to investigate on it, but looks like it happens on a very strange conditions, because it never happened to us, and we test the app on the chrome, firefox and safari...

**Comment by yannicka** [comment]
I'm using Firefox 88 (on Debian Unstable), and I don't have this problem, the artboards display well.
