### ISSUE TITLE
German language support

### ISSUE THREAD

**Issue by jancborchardt** [penpot/penpot#902]
Let’s start the German language support! :) Doesn’t seem to be there yet.

My Weblate account is https://hosted.weblate.org/user/jancborchardt/, if you add me there I’ll start off.

**Comment by niwinz** [comment]
done, if you have any problem, feel free to ask.

**Comment by girafic** [comment]
Hmm, German translation was already there, missing now in the PO folder 🤔

**Comment by niwinz** [comment]
Agree, I go to investigate.

**Comment by niwinz** [comment]
Hmm, clearly that was my fault, on refactoring the i18n I have ommited the `de` locale WTF. I go to recover it right now.

**Comment by niwinz** [comment]
Done, german lang restored.

**Comment by jancborchardt** [comment]
Heh, was already wondering why German is not there. Thanks both for restoring and adding me then. :)

**Comment by jancborchardt** [comment]
FYI I made 2 suggestions to English source strings, or should I open them as a pull request? https://hosted.weblate.org/translate/penpot/frontend/en/?q=has:suggestion

**Comment by niwinz** [comment]
It is ok with suggestions, we will import and revise everything in weblate. Thank you ;)

**Comment by girafic** [comment]
@niwinz thx for restoring back 👍 
@jancborchardt feel free to review and improve the German translation 😊
