### ISSUE TITLE
Sometimes the file viewport starts in an empty area 

### ISSUE THREAD

**Issue by jancborchardt** [penpot/penpot#908]
**Describe the bug**
In some cases, when opening a file, the viewport starts in an area off to the top left (or bottom right, don’t fully remember), where there’s no content. Initially I get shocked that the work is gone, but then I have to zoom out or Shift+1 and then it’s all still there.

**To Reproduce**
1.  The files list
2.  Open a file
3.  Sometimes the issue happens, sometimes not

**Expected behavior**
I would expect for my last viewport to be saved so I can directly get back into work on what I was working on before.
Alternatively, bringing everything in view like it seems to do now is fine as well.

**Screenshots**
![empty document cause moved off to the side](https://user-images.githubusercontent.com/925062/117285953-e6fb6900-ae68-11eb-8d71-72d5a6f7628c.png)

**Desktop (please complete the following information):**

-   OS: Ubuntu 20.04
-   Browser: Firefox
-   Version 88

**Environment (please complete the following information):**
SAAS (https://design.penpot.app)

**Comment by niwinz** [comment]
Thanks, looks like a race condition in the workspace initialization. I have created [taiga issue](https://tree.taiga.io/project/penpot/issue/1659) for track it.
