### ISSUE TITLE
Entering from main website makes it seem like you have to log in again every time

### ISSUE THREAD

**Issue by jancborchardt** [penpot/penpot#909]
**Is your feature request related to a problem? Please describe.**
When you enter from https://penpot.app, there are the "Log in" and "Sign up" buttons and it always feels like you have to log in yet again:
![Have to log in every single time](https://user-images.githubusercontent.com/925062/117288311-a6e9b580-ae6b-11eb-9139-0b311166a59a.png)

Yes, the credentials are autofilled (redacted here) but still you have to click log in and it just feels a bit like a chore:
![always redirected to log in even if you are already logged in](https://user-images.githubusercontent.com/925062/117288306-a6511f00-ae6b-11eb-9bac-ff59586e2e42.png)

**Describe the solution you'd like**
Step 1: Going to https://design.penpot.app/#/auth/login could just check your auth state and if you are logged in already, just redirect you to https://design.penpot.app
Alternatively, the "Log in" button on the website could direct to https://design.penpot.app instead of https://design.penpot.app/#/auth/login because the former will automatically redirect you either to the dashboard or the log in page depending on your state.

Step 2: Ideally, you might even see your little avatar on the top right of the home page if you already have an account and are logged in, cause the "Log in" and "Sign up" buttons always make it seem like you don’t have an account yet.

**Comment by jancborchardt** [comment]
(Also little remark: The button says "Sign in" even though on the frontpage "Log in" is used – which is also a nicer differentiation between "Log in" and "Sign up". :)

**Comment by niwinz** [comment]
Hi @jancborchardt 
Thank you for this accurate feedback. I will create an [internal taiga issue](https://tree.taiga.io/project/penpot/issue/1658) for approach it.

**Comment by cjreads665** [comment]
facing the same issue. browser - Brave Version 1.25.73 Chromium: 91.0.4472.106 (Official Build) (64-bit)
OS - Lubuntu LTS

**Comment by hirunatan** [comment]
This is fixed now! If you press the "Log in" button in the landing page, you directly go to the dashboard without needing to log in again.

**Comment by hirunatan** [comment]
We are, anyway, planning further reworkings in the landing page, stay tuned.
