### ISSUE TITLE
Color toolbar state resets / is not remembered

### ISSUE THREAD

**Issue by jancborchardt** [penpot/penpot#910]
**Is your feature request related to a problem? Please describe.**
Every time you refresh or load up Penpot newly, the color bar on the bottom is hidden and also reset in the set of colors it shows.

This is how I’d like to have it, with our component colors in there:
![Color component bar resets after reload](https://user-images.githubusercontent.com/925062/117288923-5030ab80-ae6c-11eb-95bc-a8c51b744841.png)

What I always need to do is:
1. Show the color bar again
2. Go to the menu
3. Pick "Nextcloud core components" again
![need to change to pick core components colors](https://user-images.githubusercontent.com/925062/117288902-47d87080-ae6c-11eb-8f93-f60ffacf4a42.png)

**Describe the solution you'd like**
It would be great if the state of the color bar would just be remembered. Shown/hidden, as well as which color set was selected. :)

**Additional context**
On a related note, the same issue happens with the color picker in the sidebar – it always resets to "Recent colors", which results in non-linked colors being used:
![Color picker always resets to recent colors instead of staying on shared library or last selection](https://user-images.githubusercontent.com/925062/117289148-8f5efc80-ae6c-11eb-9280-a9b667b8608c.png)

**Comment by niwinz** [comment]
Reported [enhancement](https://tree.taiga.io/project/penpot/issue/1660) to be reviewed by the design team. Thanks
