### ISSUE TITLE
Invitations sometimes do not work

### ISSUE THREAD

**Issue by jancborchardt** [penpot/penpot#911]
**Describe the bug**
I can’t quite pin it down, but sometimes or in special cases, invitations do not seem to work. Possibly the recipient has to have an account already.
⁨
@erioldoesdesign also mentioned a possibility:
> The bug was when I clicked the invite I had to login and then it went wonky. So invites might not like if you don't register or are already logged in

**To Reproduce**
1.  Invite someone
2.  They might or might not have issues

**Expected behavior**
It "works". :D Sorry that we can’t provide further info. It happened with the Open Source Design team, so maybe looking at server logs is more insightful?

**Environment (please complete the following information):**
SAAS (https://design.penpot.app)

**Comment by jdittrich** [comment]
I had the issue. 

>  Possibly the recipient has to have an account already.

Yes, I had the problem and did have an account before.

This happened: 

[being not logged in in penpot, just to have a clean slate]

1. Click link in mail (XYZ has invited you to join the team ABC)
2. Login-page shows, in the upper right corner I see:
![grafik](https://user-images.githubusercontent.com/3416487/117309267-8e38ca00-ae82-11eb-8dbd-ae9d9786bb48.png)
("something went wrong")
3. I log in
4. I look for the team in the team switch in the upper left corner, but there is no new team.

**Comment by niwinz** [comment]
Ok, thanks, I will look on it ASAP.

**Comment by jdittrich** [comment]
I can provide console output or whatever helps (but I could not find anything so far client side that helped me to understand it)

**Comment by niwinz** [comment]
I have tried  the branch the basic flows and cant reproduce it. So I have some questions:

- How much time passed between link is sent and is used? the link has expiration of 6h.
- You have said you have had account, the invitation is sent to the same email that your account?
- Are you logging using google auth or penpot email/password?

Can you send me the invitation link to the `info@penpot.app` email? It will help check if something wrong happened with link.

In any case, I hope soon this subsystem will rewritten and we will have a more decent approach for handling invitations.

**Comment by jdittrich** [comment]
> How much time passed between link is sent and is used? the link has expiration of 6h.

First attempt probably > 6 hours, 2nd attempt just 2min (got a new link send)

>  the invitation is sent to the same email that your account?

Yes, same mail.

> … google…  penpot email/password

via _penpot email/password_

> send me the invitation link to the info@penpot.app email

yes

**Comment by niwinz** [comment]
After researching a bit more, and looking inside the token metadata, I found that `:exp #app/instant "2021-05-06T05:50:39.085Z"`, I the token you sent me is the first one (the expired)?

As far as I see, seems like everything is related to the token expiration, if you still have problem joining, with a recent token (less than 6h ago), please send me it, this will help a lot for tracing the real problem.

Meanwhile, I will increase the default token expiration to 48h, because 6h is a too small window, and if someone sent invitation on evening, on the morning this link will not work.

**Comment by niwinz** [comment]
Additionally, the error message is incorrect, it should say token is expired. I will fix it also.

**Comment by jdittrich** [comment]
Now it worked with a recent token @jancborchardt  send me.

**Comment by niwinz** [comment]
For now, I have increased the default timeout for prevent confusion, and we already talking internally on how to improve this.
In any case, thanks for reporting \o/
