### ISSUE TITLE
docker image uses demo.uxbox.io as backend

### ISSUE THREAD

**Issue by lukeinator42** [penpot/penpot#92]
Hi,

I just cloned the repo and started the docker image using ./manage.sh build && ./manage.sh run.
It appears however, the app is using the demo server at demo.uxbox.io as the backend instead of the local backend. Is there an easy way to use the local backend instead?

Any help would be greatly appreciated!

Thanks,
Lukas

**Comment by photonsphere-org** [comment]
In uxbox/frontend/scripts/figwheel.clj

(def options
  {;;"uxbox.config.url" "http://127.0.0.1:6060/api"
   "uxbox.config.url" "https://demo.uxbox.io/api"
   })

Uncomment the first and comment the second line with a single ;
