### ISSUE TITLE
Norwegian Bokmål translation

### ISSUE THREAD

**Issue by comradekingu** [penpot/penpot#921]
I want to help to maintain and enhance the existing(?) Norwegian Bokmål translation. My Weblate profile is https://hosted.weblate.org/user/kingu/

**Comment by niwinz** [comment]
There are no Norwegian lang right now, but feel free to create it and if you have any problem, just ask.
Thanks

**Comment by comradekingu** [comment]
@niwinz Getting access denied trying to create it in https://hosted.weblate.org/projects/penpot/frontend/

**Comment by niwinz** [comment]
created
