### ISSUE TITLE
'Internal error: assertion' when Path tool selected and Delete key is pressed

### ISSUE THREAD

**Issue by guidimas** [penpot/penpot#923]
**Describe the bug**
The 'Internal error: assertion' banner appears when Path tool is selected, nothing is drawn and Delete key is pressed.

**To Reproduce**
1.  On the left menu bar, click on 'Path (P)' tool
2.  Do not draw anything
3.  Press 'Delete' key

**Expected behavior**
The error should not appear, since nothing should be done.

**Screenshots**
![internal_error](https://user-images.githubusercontent.com/25866601/117437449-9c302e80-af06-11eb-8a3b-8401ae558e9f.jpeg)

**Desktop (please complete the following information):**

-   OS: Ubuntu 18.04
-   Browser: Mozilla Firefox / Google Chrome
-   Version: 88.0 / 90.0.4430

**Smartphone (please complete the following information):**
N/A

**Environment (please complete the following information):**
Using SAAS (https://design.penpot.app).

**Frontend Stack Trace (if self-hosted)**

<details>

```
-- Spec failed --------------------

  nil

should satisfy

  vector?

-- Relevant specs -------

:app.main.data.workspace.path.spec/content:
  (cljs.spec.alpha/coll-of
   :app.main.data.workspace.path.spec/content-entry
   :kind
   cljs.core/vector?)

-------------------------
Detected 1 error
```

</details>

**Backend Stack Trace (if self-hosted)**
N/A

**Additional context**
N/A

**Comment by Alotor** [comment]
Thanks for the report. We'll adress it ASAP. 
Regards,

**Comment by niwinz** [comment]
Should be fixed.
