### ISSUE TITLE
Releases?

### ISSUE THREAD

**Issue by lastlink** [penpot/penpot#93]
Could you start doing releases of this?

**Comment by bowmanpete123** [comment]
+1

**Comment by SrimalPriyanga** [comment]
+1

**Comment by SrimalPriyanga** [comment]
Could someone publish the developer preview?

**Comment by cab404** [comment]
Seriously, no releases for over 4 years?

**Comment by niwinz** [comment]
Until beta we don't plan to have regular releases, right now we are working in a "rolling-rellease mode". You can try downloading the latest version from `develop` : https://github.com/uxbox/uxbox/blob/develop/docs/01-Development-Environment.md#start-the-testenv

**Comment by cab404** [comment]
> Until beta we don't plan to have regular releases, right now we are working in a "rolling-rellease mode". You can try downloading the latest version from `develop` : https://github.com/uxbox/uxbox/blob/develop/docs/01-Development-Environment.md#start-the-testenv

Maybe add a bit red button pointing to https://uxbox.github.io/?

**Comment by niwinz** [comment]
That is very outdated version, if you wan't play with latest version you have https://demo.uxbox.io (please use demo users, you can create them from the login page, any registred user in the platform wil be treated as demo user and will become elegible for deletion past 48 hours). 

This demo stil does not have the latest changes in develop, but we deploy it periodically (each month aprox)
