### ISSUE TITLE
Some issues with app in small laptop screens (1366 x 768)

### ISSUE THREAD

**Issue by mdtrooper** [penpot/penpot#931]
**Describe the bug**
There are some issues with app in small laptop screens. For example It is in the "design tools" left panel. In my screen (1366 x 768), the "color palete" button is hidden (it is out the window).

And the footer of register panel is above of the "google button". My laptop screen is 1366x768.

It is a tiny design bug, I think that it has low priority.

**To Reproduce**
1. Load https://penpot.app/
2. Click button "Get started, it's free!"
3. The bug is in the login panel.

or

1. Load https://penpot.app/
2. Start a project
3. Select or create a file
3. The bug is in the left panel.

**Expected behavior**
The "google button" could be separated of footer.

**Screenshots**
![imagen](https://user-images.githubusercontent.com/1285451/117667324-141b8480-b1a5-11eb-8b35-8d59b9759818.png)

**Desktop (please complete the following information):**

-   OS: Debian GNU/Linux bullseye/sid
-   Browser: Firefox
-   Version: 78.9.0esr

**Comment by mdtrooper** [comment]
There is another similar design bug. It is in the "design tools" left panel. In my screen (1366 x 768), the "color palete" button is hidden (it is out the window).

![imagen](https://user-images.githubusercontent.com/1285451/117670451-2cd96980-b1a8-11eb-8fc5-beb1887b0825.png)

Maybe in the small screen...the penpot show a arrow or something such as Inkscape (yes, it is a desktop application sorry). I paste the screen shot:

![imagen](https://user-images.githubusercontent.com/1285451/117671209-d6205f80-b1a8-11eb-9eb2-ff62841bf5f9.png)

**Comment by myfunnyandy** [comment]
Hi, thanks for reporting this. We've raised an issue to tackle the misalingments (you can [see it at Taiga](https://tree.taiga.io/project/penpot/issue/1696)).

About the toolbar, we are already exploring how to better organize them and we hope to release a fix soon to ensure all buttons are available at small screens (https://tree.taiga.io/project/penpot/us/1249).

**Comment by mdtrooper** [comment]
Thanks, I see the issues into taiga, it sounds great.

Well, now it is taiga bugtracker. Do I close this issue?

**Comment by hirunatan** [comment]
> Well, now it is taiga bugtracker. Do I close this issue?

It's not necessary. We leave issues in github open, so people may subscribe and get notified. We use the "managed on taiga" tag for this, and close the github issue when taiga one is closed.

**Comment by EvaMarco** [comment]
We have merged this issue with this one https://github.com/penpot/penpot/issues/941. I'm going to close this due to duplicity.
