### ISSUE TITLE
OpenID Connect name scope

### ISSUE THREAD

**Issue by hrenard** [penpot/penpot#933]
Hi, 
I'm trying to use Authelia as OIDC provider, but it doesn't provide the name scope which I believe is not  [required](https://openid.net/specs/openid-connect-basic-1_0.html#Scopes), nor necessary because the name is included in the profile scope.

**Describe the bug**
I don't really understand Clojure, but the name scope seems hard coded.

**Expected behavior**
I think OIDC name scope should not be in the default scopes or all scopes should be overwritten by PENPOT_OIDC_SCOPES environment variable.

Keep up the good work!

**Comment by niwinz** [comment]
Some scopes are mandatory. If, not how you ensure that `name` and `email` fields comes.

**Comment by niwinz** [comment]
But yeah, you are right, we can proceed only with `profile` scope and compeltly remove `name` from the required list.

**Comment by niwinz** [comment]
The change is already landed to be included in the next release.
