### ISSUE TITLE
Unable to load "Exo 2" Google font in files

### ISSUE THREAD

**Issue by Damillora** [penpot/penpot#940]
**Describe the bug**
I am unable to use the "Exo 2" font from Google Fonts, when I load a project file using that font, the default font (Source Sans Pro) appears instead. When I try to change the font to it, the font will not load.

**To Reproduce**
1.  Add a Text object to a file
2. Type some text
3. Change the font to "Exo 2". 
4. Save, then close and reopen the file

**Expected behavior**
The "Exo 2" font is loaded, and the text changes font to "Exo 2"

**Screenshots**

Self-hosted instance:
![image](https://user-images.githubusercontent.com/5674601/117979889-964ea900-b35d-11eb-909d-7896ca840df6.png)

SAAS instance:
https://design.penpot.app/#/view/30c970a0-b322-11eb-b9e4-c13c371b4289/30c970a1-b322-11eb-b9e4-c13c371b4289?token=9YCnYwM1lzdUvy4px8BW-Q&index=0
![image](https://user-images.githubusercontent.com/5674601/117980677-68b62f80-b35e-11eb-9204-3a6213a0ec2f.png)

**Desktop:**

-   OS: reproduced on Arch Linux and Windows
-   Browser: Microsoft Edge
-   Version: 90.0.818.56

**Environment:**
I reproduced the issue on both my self-hosted instance and the SAAS instance

If self-hosted instance, add OS and runtime information to help explain your problem.

-   OS Version: Ubuntu 20.04

Also provide Docker commands or docker-compose file if possible and if proceed.x

-   Docker / Docker-compose Version: Docker 19.03.8, docker-compose 1.25.0
-   Image: latest
**Frontend Stack Trace**
<details>

No exceptions are thrown, The only I see in the browser is:
```
[debug:fonts]: loading google font gfont-exo-2
```

</details>

**Additional context**
This is the font I use for a lot of my designs, so being unable to use it is a show-stopper. I might consider changing my fonts instead though.

**Comment by niwinz** [comment]
I can confirm that exo2 does not works correctly. We will look on it, thanks for this detailed report.

**Comment by Alotor** [comment]
We've reported the bug to React

https://github.com/facebook/react/issues/21497

**Comment by niwinz** [comment]
Will be fixed in the next release.
