### ISSUE TITLE
Registration Page UI UX Issue

### ISSUE THREAD

**Issue by AmrUIUXD** [penpot/penpot#941]
The page seems to be semi-broken on my screen (1366x768)
![Registration Page 1](https://user-images.githubusercontent.com/82488999/118078383-5e278480-b3b6-11eb-83fb-3dbbda9b9379.png)

Good Job with Penpot so far!

**Comment by elhombretecla** [comment]
Hi @AmrUIUXD thank you for your feedback!

We will fix this as soon as possible. You can follow this issue on Taiga
[https://tree.taiga.io/project/penpot/issue/1693](https://tree.taiga.io/project/penpot/issue/1693)

**Comment by maxelkins** [comment]
Happy to pick this up if you would like to assign me - already started working on a fix it :see_no_evil:
