### ISSUE TITLE
failed to build development docker environmetn

### ISSUE THREAD

**Issue by cinlk** [penpot/penpot#947]
branch develop

command   
      ./manage.sh pull-devenv
      ./manage.sh run-devenv

but frontend service is not working, I rebuild frontend service but something  went wrong.

root@990c4b36b441:/home/penpot/penpot/frontend# sh -x scripts/build 
+ set -ex
+ CURRENT_VERSION=
+ git rev-parse --short HEAD
+ CURRENT_HASH=9afe4990
+ EXTRA_PARAMS=
+ yarn install
yarn install v1.22.10
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.58s.
+ npx gulp clean
[04:04:12] Using gulpfile /home/penpot/penpot/frontend/gulpfile.js
[04:04:12] Starting 'clean'...
[04:04:12] Finished 'clean' after 26 ms
+ npx shadow-cljs release main --config-merge {:release-version "9afe4990"}
shadow-cljs - config: /home/penpot/penpot/frontend/shadow-cljs.edn
[:main] Compiling ...
Failed reading cache for app.main.data.workspace.shortcuts: com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input: expected close marker for Array (start marker at [Source: java.io.FileInputStream@64cc8eaf; line: 1, column: 54344])
 at [Source: java.io.FileInputStream@64cc8eaf; line: 1, column: 247685]
Failed reading cache for app.main.ui.workspace.colorpicker.libraries: com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input: expected close marker for Array (start marker at [Source: java.io.FileInputStream@328982fd; line: 1, column: 207393])
 at [Source: java.io.FileInputStream@328982fd; line: 1, column: 214957]
Failed reading cache for app.main.ui.workspace.context-menu: com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input: expected close marker for Array (start marker at [Source: java.io.FileInputStream@6faadfe2; line: 1, column: 239708])
 at [Source: java.io.FileInputStream@6faadfe2; line: 1, column: 247427]
Failed reading cache for app.main.ui.workspace.colorpicker: com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input: expected close marker for Array (start marker at [Source: java.io.FileInputStream@567599f5; line: 1, column: 257739])
 at [Source: java.io.FileInputStream@567599f5; line: 1, column: 259537]

**Comment by niwinz** [comment]
Hello @cinlk
I think you are using devenv but trying to build a production bundle (deduced because you are executing the `./scriots/build`)

This image is intended to be used with the tmux session that starts automatically on you enter on the devenv shell session (after the `run-devenv`) and this session starts the `npx shadow-cljs watch main` that is responsible to have the dev-http server up and running, without this command running you will not be able to access to the frontend on http://localhost:3449
