### ISSUE TITLE
"Keep aspect ratio" modifier key not consistent

### ISSUE THREAD

**Issue by Chaphasilor** [penpot/penpot#953]
**Describe the bug**

When resizing an layer, there's a key that you can hold so the aspect ratio of the layer stays the same.  
The only problem is that the key isn't always the same:

- When adding a new layer this key is `CTRL`/`CMD`
- When resizing an existing layer, the key is `SHIFT`

**To Reproduce**

1. Inside a file, press `R` to create a new rectangle
2. Click and hold the left mouse button, than drag the rectangle to resize it
3. While still holding the mouse button, press and hold `CTRL`/`CMD` - the rectangle will become a square and you can resize the square.  
  Releasing `CTRL`/`CMD` will allow the aspect ratio to change again.  
  Pressing `SHIFT` doesn't have any effect.
4. Release the left mouse button and `CTRL`. Now click and hold one of the rectangle's four corners to resize the existing rectangle
5. Press and hold `SHIFT` - the rectangle will keep it's previous aspect ratio while resizing.  
  Pressing `CTRL`/`CMD` doesn't have any effect.

**Expected behavior**

The modifier key for keeping aspect ratio while resizing should be the same regardless of the layer being new or existing.

The documentation mentions `CTRL` in both cases. Coming from Figma, I'd personally expect the key to be `SHIFT`, and maybe the docs are wrong, but that's not for me to decide ^^

**Desktop (please complete the following information):**

-   OS: Windows 10
-   Browser: Edge Dev 92.0.884.2
-   Penpot Version: 1.5 Alpha

**Environment (please complete the following information):**

Using https://design.penpot.app

**Additional context**

[The docs say it's `CTRL` in both cases](https://help.penpot.app/user-guide/layer-basics/):

<img alt="Doc on creating layers" src="https://user-images.githubusercontent.com/18015147/118395008-60087680-b648-11eb-8641-670dffd4d1ad.png" height="400"/>
<img alt="Doc on resizing layers" src="https://user-images.githubusercontent.com/18015147/118395035-83cbbc80-b648-11eb-902b-a273ada25da3.png" height="400"/>

**Comment by hirunatan** [comment]
Thanks. This is indeed a bug, as the implementation does not reflect the manual. But also you're true, in that it should be better to use the shift key.

We have created an enhancement issue for this, will be done ASAP: https://tree.taiga.io/project/penpot/issue/1697
