### ISSUE TITLE
Unable to draw grid-aligned 1px lines

### ISSUE THREAD

**Issue by allanday** [penpot/penpot#954]
**Describe the bug**

**To Reproduce**

I'm trying to draw something like this, where the internal strokes have a different colour to the rectangle border:

![image](https://user-images.githubusercontent.com/213068/118457422-a36aef80-b6f1-11eb-88ac-0f39894a15b4.png)

However, I've been unable to find a way to draw those 1px lines so that they are aligned to the pixel grid. As a result, they're rendered fuzzy rather than sharp.

1.  Select the path tool
2.  Click twice to draw a line
3.  In the properties, change the stroke width to 1px

The path nodes are aligned to grid intersections, which means that the path isn't grid-aligned. I'm unable to move it so that the path outline is aligned to the grid, as opposed to its nodes being aligned to the grid.

**Expected behavior**

Figma has a line tool which draws grid-aligned lines by default (default thickness is 1px).

**Screenshots**
Example of fuzzy lines from Penpot:

![image](https://user-images.githubusercontent.com/213068/118458712-f002fa80-b6f2-11eb-8bde-0c8a5e25f73b.png)

**Desktop (please complete the following information):**

-   OS: Fedora 34
-   Browser: Firefox
-   Version: 88.0

**Environment (please complete the following information):**
SAAS (https://design.penpot.app)

**Comment by Alotor** [comment]
Hi @allanday thanks for your feedback.

I've been talking with others on the team and we think a line tool is good but maybe a little bit more mid-term.

At the moment what we can do is when you're doing zoom on a pixel level we can snap to pixels or to "half pixels" that way the paths with a stroke of 1 will be aligned with the pixel grid. 

What do you think?

**Comment by allanday** [comment]
Thanks for the reply! For my use case, snapping the edges/corners of the path to the pixel grid would work. Can't comment on how that would affect other use cases though.

My main experience is Inkscape. There I'd switch the snap behaviour from nodes to bounding boxes. That works, but it's cumbersome and not what I'd want to see here. :slightly_smiling_face:
