### ISSUE TITLE
Unexpected validation error when register user

### ISSUE THREAD

**Issue by jln-brtn** [penpot/penpot#958]
**Describe the bug**
When I try to register a new user on my fresh install, penpot returned : Unexpected validation error (server side).

**To Reproduce**
1.  Create fresh install using docker by following the documentation
2.  Go to the landing page
3.  Click on register and fill information
4.  Validate

**Expected behavior**
The account must be created 

**Screenshots**
![image](https://user-images.githubusercontent.com/67162499/118521655-82c78780-b73b-11eb-84fd-cc39c004e021.png)

**Desktop (please complete the following information):**

-   OS: Windows
-   Browser : Chrome & Firefox
-   Version : 90.0.4430.212 & 88.0.1 

**Environment (please complete the following information):**
-   self-hosted instance
-   OS Version: Ubuntu 18.04.5 LTS
-   Nginx 1.14.0

Also provide Docker commands or docker-compose file if possible and if proceed.x

[docker-compose.txt](https://github.com/penpot/penpot/files/6495274/docker-compose.txt)
[nginx.txt](https://github.com/penpot/penpot/files/6495275/nginx.txt)
[config.txt](https://github.com/penpot/penpot/files/6495276/config.txt)

**Frontend Stack Trace (if self-hosted)**

<details>

172.22.0.1 - - [17/May/2021:15:55:19 +0000] "POST /api/rpc/mutation/register-profile HTTP/1.1" 400 66 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36"

</details>

**Backend Stack Trace (if self-hosted)**

<details>

[2021-05-17 15:55:06.961] [main] I app.worker - action="start worker" name="worker" queue="default"
[2021-05-17 15:55:06.963] [main] I app.main - msg="welcome to penpot" version="1.5.3-alpha-5126-gab799c83"
[2021-05-17 16:00:00.007] [worker-59] D app.worker - action="execute scheduled task" id="storage-recheck"
[2021-05-17 16:00:00.017] [worker-60] D app.worker - action="execute scheduled task" id="file-xlog-gc"
[2021-05-17 16:00:00.025] [worker-59] I app.storage - action="recheck items" deleted="0" processed="0" task="recheck"
[2021-05-17 16:00:00.028] [worker-60] D app.tasks.file-xlog-gc - action="trim file-change table" removed="0"

</details>

**Additional context**
The front server seems to return an 400 code.
I can bypass this error by using the following command in your documentation : 
`docker exec -ti penpot_penpot-backend_1 ./manage.sh create-profile`
After login, the application works fine : can create project, change my password in my profile ... but still can't register users.

**Comment by jln-brtn** [comment]
**Continuation of my investigations**
![image](https://user-images.githubusercontent.com/67162499/118524799-d5ef0980-b73e-11eb-992f-3a78e94c0579.png)

My mail seems to generate the error. I tried with another mail same result.
I double check in my config of PENPOT_REGISTRATION_DOMAIN_WHITELIST, and it's empty for allow all

**Comment by jln-brtn** [comment]
**Continuation of my investigations**

![image](https://user-images.githubusercontent.com/67162499/118525488-86f5a400-b73f-11eb-97b9-10c64a1d1231.png)


My mail seems to generate the error. I tried with another mail same result.
I double check in my config of PENPOT_REGISTRATION_DOMAIN_WHITELIST, and it's empty for allow all

**Comment by niwinz** [comment]
Hi @jln-brtn we have had a bug related to this, but it should be already fixed.

In any case you can try few things for try to fix it locally:
- Remove `PENPOT_REGISTRATION_DOMAIN_WHITELIST` completely from the config.
- Check if you are using the latest docker image (pass us the docker image id for check it)

**Comment by jln-brtn** [comment]
Thank you @niwinz for your response.

I tried to remove `PENPOT_REGISTRATION_DOMAIN_WHITELIST ` and I'm now able to register a new account. However, if I add : `PENPOT_REGISTRATION_DOMAIN_WHITELIST="exemple.com"` I can't register a new account with my address : julien.breton@exemple.com

![image](https://user-images.githubusercontent.com/67162499/118614617-3eca9600-b7c0-11eb-9a78-272956c5a52f.png)

My SHA265 version of docker images :
|name|sha265|
|---|---|
|penpotapp/backend:latest|fa5728edd1b438f76611113e27408ef9d22f9ba875afea146eacaf8525026a20|
|penpotapp/exporter:latest|6fa62d27d690941c99b3302e8c6828bfc7764aa6c0159ed4c41d3fc3c35f7107| 
|penpotapp/frontend:latest|5adb88a33dcd828e2c0fbaee6e03c4c6ad11cfc5dce810cbc13caae63646ab3e|
|postgres:13|293e4ed402bacef9f5be149c15b9eb5d60954a043dd2c0551611d562915f807c|
|redis:6|bc8d70f9ef6cae366eb6423fcb4699597c5a6b99126f3ced35b6b9d6d134375b|

![image](https://user-images.githubusercontent.com/67162499/118618969-75a2ab00-b7c4-11eb-91f7-665a44a5323d.png)

I don't know why, I'm not getting the same sha265/ID between docker hub and my server. I deleted the images and pull again with the same result.

**Comment by niwinz** [comment]
Thank you for this detailed report. Probable we still have the bug (seems like it is not properly fixed). So I keep this issue open until we fix it.

**Comment by niwinz** [comment]
Should be fixed.
