### ISSUE TITLE
 Is there a detailed readme?

### ISSUE THREAD

**Issue by tinybright** [penpot/penpot#96]
Is there a detailed readme? I don't know how to start.

**Comment by madmath03** [comment]
Hi @tinybright,

I played quite a lot with UXBOX  so maybe I can help you with this.
If you want to develop / test UXBOX locally, you can use the [`manage.sh`](https://github.com/uxbox/uxbox/blob/master/manage.sh) script at the root of this repo.

The following will build a docker container and run a development server for UXBOX (note that the [frontend uses demo.uxbox.io](https://github.com/uxbox/uxbox/issues/92) by default): 
```
./manage.sh run_image
```

After that, you will have 4 tmux sessions running each of UXBOX services.
Hope that helps.
