### ISSUE TITLE
Color palette order isn't stable

### ISSUE THREAD

**Issue by allanday** [penpot/penpot#961]
**Describe the bug**
The color palette bar at the bottom of the page is ordered by recency of use, as opposed to the name of the color. I personally find that this makes it really hard to find the color I'm looking for.

My palette is relatively large with different shades of the same color. Generally, I'm either looking for a specific named color, or I'm picking a color based on relative lightness to another shade I already have.

In other apps I've used, the palette has a static order based on the name, and I therefore haven't had this issue.

**To Reproduce**
1.  Create a palette with a decent number of colors (say, 25+), containing different shades of the same color, organised by name
2.  Use the palette for a bit to draw designs
3.  Try to select a specific named color from the palette bar

**Expected behavior**
Based on my experience with Inkscape: the colors in the palette maintain their positions, and can be selected based on position and/or name.

**Screenshots**
What my palette bar looks like currently:

![image](https://user-images.githubusercontent.com/213068/118782252-d47c2900-b885-11eb-9b2b-9e55013ffaec.png)

And the palette in question:

![image](https://user-images.githubusercontent.com/213068/118783987-823c0780-b887-11eb-80a4-06468239d8a1.png)

**Desktop (please complete the following information):**

-   OS: Fedora 34
-   Browser: Firefox 88.0 (also reproduced with Chrome 90.0.4430.212)

**Environment (please complete the following information):**
SAAS (https://design.penpot.app)

**Comment by hirunatan** [comment]
You are true, the order in the color palette is quite random now. We have created an issue to show them in alphabetical order:
https://tree.taiga.io/project/penpot/issue/1702

**Comment by hirunatan** [comment]
This is fixed! You will see it in the new release of Penpot.

**Comment by allanday** [comment]
Awesome, thank you!
