### ISSUE TITLE
Shift+click on file library colors doesn't set the stroke

### ISSUE THREAD

**Issue by allanday** [penpot/penpot#962]
**Describe the bug**
The convention that I've seen for color palettes is that clicking on a color sets the fill, while shift+click sets the stroke.

This is how it works in Penpot for the palette at the bottom of the page. However, with the colors in the file library, while click sets the fill, shift+click selects the color rather than setting the stroke. (It's a bit unclear what multi-select is for here... delete?)

I personally found the current behaviour to be really confusing. Since clicking the color set the fill, I expected shift+click to also work according to the conventions I've seen in other apps. I was left struggling knowing how to set the stroke color; it took me quite a while to figure out that shift+click was supported in the palette on the bottom page edge.

**To Reproduce**
1.  Use a shared library that has a bunch of colors set
2.  Select an object in the workspace
3.  In the sidebar, open assets > file library > colors
4.  Hold down shift and click a color

**Expected behavior**
The stroke color of the selected object to be updated to the color I just clicked.

**Screenshots**
![image](https://user-images.githubusercontent.com/213068/118786489-c3351b80-b889-11eb-8e96-40d2e647e7a4.png)

**Desktop (please complete the following information):**

-   OS: Fedora 34
-   Browser: Firefox
-   Version: 88.0

**Environment (please complete the following information):**
SAAS (https://design.penpot.app)

**Comment by hirunatan** [comment]
Ok, you are true in that it may be counter intuitive. We will think about a better alternative. See this enhancement: https://tree.taiga.io/project/penpot/issue/1703

Multiselection in colors is useful to delete colors in bulk, and also for a new feature we are working on: grouping library assets in folders.
