### ISSUE TITLE
Question: Are there any pre-made UIKits or components I can use?

### ISSUE THREAD

**Issue by sprklinginfo** [penpot/penpot#967]
Hi there, I am a web app developer, not a designer. I am looking for a self-hosted quick prototyping/wireframing tool to test out app ideas with some interactions. I come across your project but tried to sign up a free account. But it looks like I have to make every component myself. For instance, I have to make a button with a text field and a rectangle box.  As I said, I don't do any design, just want to quickly sketch several app screens, e.g. drop some common form fields, buttons, texts and add some interactions among multiple screens. Are there any pre-made UIKits or components I can import without making components myself? Thanks.

**Comment by hirunatan** [comment]
Hi, @sprklinginfo. Right now the only premade components kit you can use is the one that we include, with the own penpot UI system.

But we have in our topmost priorities to enable public shared libraries, and start adding such kind of kits. Keep watching... ^_^

**Comment by ghost** [comment]
This. This is really all that’s missing from making Penpot a true alternative to e.g. Figma or Sketch. Really looking forward to this! Will it be possible to import such libraries that work in other platforms; Apple for instance already offer such libraries for iOS that work in said applications. I have found a library for Bulma that work in Adobe XD, any chance this can be imported/converted to it can easily be imported?
Finally, a HUGE kudos for the excellent work you have done with Penpot!

**Comment by enieber** [comment]
my suggestion is to create one option to share UIKits of community Penpot and the create service private UIKits. The Penpot is amazing software...

**Comment by JPustkuchen** [comment]
Same here, looked for a shared Wireframe component library, but doesn't seem to exist yet. The workaround is to download a template, import it into the workspace and then import into the layout.

The current way makes onboarding hard and I guess many users testing it are lost here :)

**Comment by garrett** [comment]
FWIW: Here's an official page where you can download component libraries: https://penpot.app/libraries-templates.html

I agree it's a workaround and would be nice to be able to browse (probably a curated set of) available libraries from within PenPot. And then they could get updates as well.

**Comment by therealpygon** [comment]
> I agree it's a workaround and would be nice to be able to browse (probably a curated set of) available libraries from within PenPot. And then they could get updates as well.

At the very least, being able to import a shared library rather than download/re-upload would save on both transfer and storage cost. I expect a massive storage cost in just duplicate files for this reason; that alone should be reason enough to focus on streamlining the process (unless somewhere in the backend they have implemented de-duplication, haven't looked).

**Comment by myfunnyandy** [comment]
At the [1.16 beta release](https://community.penpot.app/t/never-gonna-give-you-up-penpot-1-16-beta-release/1865) we've launched an in-app module to directly download a curated selection of files. Being a great improvement in terms of using community file, we are well aware that this feature can be improved (search, filters, etc), thing that we will keep doing.
