### ISSUE TITLE
Incorrect checkbox size

### ISSUE THREAD

**Issue by soultipsy** [penpot/penpot#970]
Describe the bug
When any element, group, or component, with size less than 10px*10px, they checkbox size is incorrect.

To Reproduce

   Create  any element, group, or component
   Resize them to less than 10px*10px
   Check that the selection box and the actual size match

Expected behavior
The selection box should match the actual size, as if the size were greater than 10px*10px.

Screenshots
![2021-05-24-15-06-41](https://user-images.githubusercontent.com/40300919/119310021-c1ac8e80-bca1-11eb-9f90-a92d35e6075c.gif)

Desktop (please complete the following information):

 OS: Windows
    Browser : Microsoft Edge & Firefox
    Version : 91.0.864.33  & 88.0.1

Environment (please complete the following information):
SAAS (https://design.penpot.app)

**Comment by elhombretecla** [comment]
Hi @soultipsy thank you so much for your feedback :)

We already know about this issue so it is fixed in the next upcoming release that will be launched this week ;)
