### ISSUE TITLE
Path error when editing an externally imported svg icon

### ISSUE THREAD

**Issue by soultipsy** [penpot/penpot#971]
Describe the bug
When complex SVG paths are pasted externally, anchor points become stuck, incorrectly merged, incorrectly positioned, and jumbled path lines appear.

To Reproduce

Import any complex svg icon from outside
Go to the layer and double-click to edit the svg path
The svg path appears to be incorrectly merged and cannot be recovered
  

Expected behavior
The svg path should remain as it is, and there should be no incorrect merges or fills.

Screenshots
![2021-05-24-15-13-39](https://user-images.githubusercontent.com/40300919/119315017-f4598580-bca7-11eb-8151-aab21e0fce21.gif)

Desktop (please complete the following information):

   OS: Windows
   Browser : Microsoft Edge & Firefox
   Version : 91.0.864.33  & 88.0.1

Environment (please complete the following information):

SAAS（ https://design.penpot.app ）

**Comment by elhombretecla** [comment]
Hi @soultipsy!

Could you send to us this icon SVG to do some test? This error is unknown to us.
Our email is info@penpot.app

Thank you!

**Comment by soultipsy** [comment]
Ok, @Elhombretecla I have sent you guys an email. In fact, when I tried to edit the demo file of the penpot-design system, something similar happened, I've attached a screenshot to the email, please check it.

**Comment by soultipsy** [comment]
> 
> 
> 好的，我已经给你们发送了一封电子邮件。 实际上，当我尝试编辑penpot-design系统的演示文件时，发生了类似的事情，我已经在电子邮件中附加了屏幕截图，请检查一下。

**Comment by Alotor** [comment]
Thanks @soultipsy we've solved the issue in our local environment. We have a release planned for this week and will be fixed by then. 
Cheers,

**Comment by elhombretecla** [comment]
Taiga issue [https://tree.taiga.io/project/penpot/issue/1727](https://tree.taiga.io/project/penpot/issue/1727)

**Comment by FLOKI-AN1** [comment]
I also have a problem with svg, but in a slightly different way, because BotFather says that there should be at least one "path":
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="512px" height="512px" viewBox="0 0 512 512" version="1.1">
    <style>
        /* Styles for object */
        .object {
            fill: none;
            stroke: black;
            stroke-width: 1.7;
            stroke-linecap: butt;
            stroke-linejoin: miter;
            stroke-miterlimit: 4;
        }
    </style>

    
    <a xlink:href="https://fragment.com" target="_blank">
        <path 
            class="object" 
            id="surface1" 
            transform="matrix(30.117647,0,0,28.444444,0,0)" 
            d="M 1.84005 2.999954 L 15.139977 2.999954 C 15.419998 2.999954 15.639969 3.219955 15.639969 3.499969 C 15.639969 3.590057 15.619995 3.669983 15.580048 3.750046 L 9.250053 14.930008 C 8.980019 15.409973 8.370041 15.579987 7.890022 15.309998 C 7.729973 15.220047 7.590027 15.079971 7.510002 14.919983 L 1.399979 3.740021 C 1.27002 3.499969 1.360031 3.190018 1.599976 3.059967 C 1.68 3.020004 1.760025 2.999954 1.84005 2.999954 Z M 8.5 15.000046 L 8.5 2.999954" 
        />
    </a>

    
    <foreignObject x="0" y="0" width="512" height="512">
        <iframe 
            src="https://fragment.com" 
            width="100%" 
            height="100%" 
            style="border: none;"
        ></iframe>
    </foreignObject>
</svg>
