### ISSUE TITLE
Wrong node merge

### ISSUE THREAD

**Issue by soultipsy** [penpot/penpot#978]
**Describe the bug**
In some cases, when adding nodes to a path, an incorrect node merge occurs, causing the path to appear in the wrong location. (Possible causes are direct node merging with the pen, which is not a problem if you use the join nodes tool)

**To Reproduce**
1.  Drawing some paths with a pen
2.  Connecting two nodes directly with the pen
3.  Adding a new node to a part of a path
4.  Nodes can appear to merge unexpectedly, causing paths to be offset

**Expected behavior**
Newly added nodes should not merge with or replace any old nodes

**Screenshots**

https://user-images.githubusercontent.com/40300919/119590874-2c77da00-be08-11eb-8d6b-6f4967398959.mp4

Error when connecting directly with pen

https://user-images.githubusercontent.com/40300919/119590991-62b55980-be08-11eb-84b6-8216899d216b.mp4

Correct when using the join nodes tool

**Desktop :**

-   OS: Windows
-   Browser : Microsoft Edge & Firefox
-   Version : 91.0.864.33 & 88.0.1

**Environment :**
 SAAS (https://design.penpot.app)

**Comment by Alotor** [comment]
Thanks for the report. Will be fixed in the next release.
