### ISSUE TITLE
OIDC provider not configured

### ISSUE THREAD

**Issue by hrenard** [penpot/penpot#983]
**Describe the bug**
I'm trying to use the OIDC auth but when I click on the `Login with OpenID (SSO)` button, I get a 404 on the `/api/auth/oauth/oidc` endpoint.

**To Reproduce**
Configure an OIDC provider and try logging in.

**Environment (please complete the following information):**
I self-host with docker on Ubuntu LTS.

**Frontend Stack Trace (if self-hosted)**
<details>

```
[26/May/2021:14:41:21 +0000] "POST /api/auth/oauth/oidc HTTP/1.1" 404 103 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0"
```

</details>

**Additional context**
In the HTTP response I get this hint: `provider not configured`.
I believe the issue is a typo here :
https://github.com/penpot/penpot/blob/6489ad4114e19aa202ad4c2d616fe838ccecb28b/backend/src/app/http/oauth.clj#L250-L254
I think ` :provider "oid"` should be ` :provider "oidc"`

**Comment by niwinz** [comment]
Hmm 404 request means it is not properly configured. Ensure you have the proper environment variables set on `config.env` file.

**Comment by hrenard** [comment]
On the backend I have configured:
- PENPOT_OIDC_BASE_URI
- PENPOT_OIDC_CLIENT_ID
- PENPOT_OIDC_CLIENT_SECRET

And on the frontend:
- PENPOT_OIDC_CLIENT_ID

With this It was almost working in 1.5.0-alpha (I had an issue with the scope).
Did I miss something ? Or is there new required env vars ?

**Comment by niwinz** [comment]
After checking it, yes seems like there are a little bug related to default scopes.
I have commited the fix on `main` and will deploy it to check and then bump a new minor release.
Meanwhile, you can workaround it setting, explicitly the scopes in your configuration:

```bash
PENPOT_OIDC_SCOPES="openid,profile,email"
```

For some reason the default scopes on OIDC backend didn't have the email scope, that is required.

**Comment by hrenard** [comment]
I still get a 404. Here is the response:
```json
{"~:type":"~:not-found","~:hint":"provider not configured","~:context":{"~:provider":null}}
```
Is there a way to have more verbose logs on the backend ?

**Comment by niwinz** [comment]
The backend should print something like this on startup:
```
[2021-05-27 11:29:19.943] I app.http.oauth - action="initialize" method="discover" provider="oid"
```
This indicates that the provider si properly configured.

**Comment by hrenard** [comment]
Interesting, it's not there...
What can I do to troubleshoot this ?

**Comment by hrenard** [comment]
Okay I found the issue ! My DNS were misconfigured, and I have hairpinning trouble with my router, so the auto discovery didn't work...
It might be good to throw an error in the log when that happen (failed auto discovery).
I'm terribly sorry for wasting your time. Thanks !

**Comment by niwinz** [comment]
No no, you don't need to sorry. You helped a lot find the underlying issue with the default scope. And yes, we will improve the logging of this part. Thanks.
