### ISSUE TITLE
Internal error when merging nodes

### ISSUE THREAD

**Issue by soultipsy** [penpot/penpot#990]
**Describe the bug**
Internal error page appears when merging any two nodes.

**To Reproduce**
1.  Edit the path node and select both nodes
2.  Using the merge nodes tool
3.  Node merge fails and an internal error page pops up

**Expected behavior**
Nodes should be merged correctly

**Screenshots**

https://user-images.githubusercontent.com/40300919/119919798-c02edf00-bf9d-11eb-8521-d29e39fc5f0d.mp4

**Desktop (please complete the following information):**

-   OS: Windows
-   Browser : Microsoft Edge & Firefox
-   Version : 91.0.864.36 beta & 88.0.1

**Environment (please complete the following information):**
SAAS (https://design.penpot.app)

**Comment by elhombretecla** [comment]
Hi @soultipsy 

I will create an issue on Taiga to manage this as soon as we can.

[https://tree.taiga.io/project/penpot/issue/1741](https://tree.taiga.io/project/penpot/issue/1741)

Thank you!
