### ISSUE TITLE
Add Desktop Support Since Penpot is web based it can easily be an electron app

### ISSUE THREAD

**Issue by ghost** [penpot/penpot#995]
**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
Use Electron

**Comment by elhombretecla** [comment]
Hi @Abdallah-Moh

Porting to desktop probably is posible using electron or similar technologies. We will evaluate it in a future.

There is a discussion about this topic here [https://github.com/penpot/penpot/discussions/475](https://github.com/penpot/penpot/discussions/475)
