### ISSUE TITLE
Add Real Device sizes list when creating an artboard

### ISSUE THREAD

**Issue by ghost** [penpot/penpot#996]
**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
Add A list of device sizes

**Comment by elhombretecla** [comment]
Hi @Abdallah-Moh 

There is already available a list of preset device sizes when you select an artboard.

Did you mean that?

<img width="207" alt="device-sizes" src="https://user-images.githubusercontent.com/1045247/120094647-e7161e00-c121-11eb-94d0-de883ef4d12c.png">

**Comment by ghost** [comment]
@elhombretecla Yep where can I find this

**Comment by elhombretecla** [comment]
At right sidebar once an artboard is selected. You will find artboard tool at toolbar (left side of the workspace) or using shortcut (A).

They are artboard preset sizes.

**Comment by Dehelssey** [comment]
I think it would be a better experience if those size presets would appear right when the artboard tool is selected... At the moment we have to draw an artboard and only then we can pick its size.
